### ISSUE TITLE
Translation table validation error codes should match targetAttributeType

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#107]
Error codes should be of same type as target type.

i.e. There should not be a mix of text and numeric error codes in a single row.

A row returning text should not have -9999 error code.

**Comment by prvernier** [comment]
Marc - can you point to an example? Thanks.

**Comment by edwardsmarc** [comment]
CAS_ID, SOIL_MOIST_REG and DIST_1 in most of the AB16 tables have mixed text and int error codes.

DIST rows in BC DST table has mixed error codes.

DIST_1 in NB DST table has mixed error codes

BC LYR file has some NOT_NULL that should be changed to NULL_VALUE

**Comment by prvernier** [comment]
All identified problems and a couple additional ones have been fixed.
