### ISSUE TITLE
Fix ab16 dst DIST_EXT_UPPER_1 and DIST_EXT_LOWER_1

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#108]
Translation rules use mapInt but the mappings and return value vectors are different lengths.

i.e. '0,1,2,3,4,5' has 6 values
'25,50,75,95,100' has 5 values

**Comment by prvernier** [comment]
The two lists now have the same number of values. The value 0, which is not assigned a value in the CASFRI specs, has been assigned a value of -8885, similar to the EMPTY STRING code for text attributes.
