### ISSUE TITLE
Standardize dealing with invalid photo year tables

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#115]
- We currently have working helper functions to do photo year intersections.

- We will also develop a validation step that validates each row of the photo year file and reports any invalid geometries or values - #103 

- **The question here is what to do to fix any invalid columns.**

- For example, the ab_photoyear file currently has some invalid geometry rows. These could be fixed using TT_MakeValid() which fixes invalid geometries and returns a fixed column. We would need to run this outside of the engine, just in regular postgres.
  - if we do this, can we simply overwrite the existing geo column with the new column?
  - We would need to do this on every machine that is using the engine.

- A second issue is that the photo_yr column (the value that is returned after the intersection) in the ab_photoyear table is a text column including years (e.g. "1996") and "not known".
  - We can either run the intersection and output a text field (this has been tested and works fine)
  - Or we need a standardized way to change the field to integer and change "not known" to 0. We can then report an appropriate error code by catching the zeros in a validation function. 
  - Again, this would need to be done on all machines to make sure we are all using the same version.

- The only universal option I see for fixing these issues is to write some sql code that fixes the columns during or immediately after loading. ogrinfo for example can pass sql code from our bash/batch files to the loaded table. We could use this to fix the geometries and make an integer photo_yr column.

**Comment by edwardsmarc** [comment]
Related to https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/issues/94

**Comment by pedrogit** [comment]
Wasn't the plan to treat photo year like lookup table and write a translation table that would fix them with TT_MakeValid()?

**Comment by edwardsmarc** [comment]
Yes, but we need a workflow for creating/updating the photo year table. Running it through the engine would output a valid geometry column. Do we then overwrite the original geometry column with the valid one? And keep the same name?

**Comment by pedrogit** [comment]
I would just add it to the section validating other lookup tables in sampleWorkflow.sql and create a new fixed table. That's the name of the fixed table that would go in the inventory translation table.

**Comment by edwardsmarc** [comment]
Great!

Note: after editing the sample workflow file to create this valid table, we'll need to update the translation tables to use the new table name.

**Comment by edwardsmarc** [comment]
UPDATE:

We decide not to fix invalid dependency tables inside the engine. We will validate them using the validation tables and users will be expected to fix them if they are invalid.
