### ISSUE TITLE
Update nb01_nbi01_cas.csv table

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#119]
For some reason, this table is missing most of its attributes.

**Comment by prvernier** [comment]
I've updated the table and pushed it. @edwardsmarc there are 2 attributes that are based on 2 source attributes and thus may need a special function (stand_structure and num_of_layers). Let me know what you think. Also, I'm not quite sure about photo_year - had you developed a function for that one? In the table I used datayr but I'm not sure it's equivalent.

**Comment by prvernier** [comment]
I've updated photo_year (=datayr).

@edwardsmarc we'll need custom functions for:

  1. stand_structure which depends on L1VS and L2VS
  2. num_of_layers which depends on stand_structure (or can be stand alone with more code)

**Comment by edwardsmarc** [comment]
closed with 

fe3423f3c75f7c4f7d0465e2ccdfc0bf116cb04c

and

40c50162bdd21922a126fbc5a137a7723cf7de86
