### ISSUE TITLE
GIS_AREA, GIS_PERIMETER, INVENTORY_AREA

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#129]
1. Does anyone know what the difference between GIS_AREA and INVENTORY_AREA is? Currently, we are populating them with the same value.

2. Also, if GIS_AREA and GIS_PERIMETER are null, should we calculate them?

3. What units should these attributes have. The specs indicate "ha" for both, which is clearly wrong for GIS_PERIMETER. I suggest "ha" and "m".

4. What level of precision should these attributes have? This is not specified and some inventories use 6 decimal places, which seems overkill. Maybe 1 or 2 decimal places?

**Comment by edwardsmarc** [comment]
1. I don't know. Are they not listed in the specs?
2. I'd say no. If it's null and an end user wants to calculate it themselves, they can.
3. This would be a question for Steve I think.
4. 2 seems reasonable. Maybe another Q for Steve. Maybe there's an industry standard.

**Comment by MelinaHoule** [comment]
1. Gis area is calculated at the export stage by the python code. Inventory area comes from the raw inventory. Most of the time, they are the same. 
2. Shouldn’t be null
3. Yes ha and m. This is what they are and what people work with
4. Was 6 before and in 2015, we changed it for 2 for the same reason as you mentioned. Only new inventories had the decimal fixed.

**Comment by prvernier** [comment]
Thanks Melina!

**Comment by MelinaHoule** [comment]
For CASFRI 5, we talked about using inventory_area as the area of the original polygon and GIS_area as the final area. Which means if inventory_area is not the same as GIS_area, we know in the process we made a correction (sliver, overlap, ...).

**Comment by edwardsmarc** [comment]
I added an issue to make functions to do this in CAS05. We can calculate the area and perimeter in the translation of the _cas.csv tables.

https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/issues/146

**Comment by edwardsmarc** [comment]
We also discussed changing the names of these columns in the specs to reflect the fact that INVENTORY_AREA is from the source data, and GIS_AREA is the CASFRI calculation.

Suggestions included:
GIS_AREA changed to POSTGIS_AREA or CASFRI_AREA

and 

INVENTORY_AREA changed to SOURCE_AREA or SOURCE_INVENTORY_AREA

**Comment by prvernier** [comment]
I would go with: POSTGIS_AREA, POSTGIS_PERIMETER, and SOURCE_INVENTORY_AREA

**Comment by pedrogit** [comment]
I don't like the idea of putting "POSTGIS" in the name of a CASFRI attribute. The standard should stay software agnostic even if the project is not. I would go with CASFRI_AREA.

I like SOURCE_INVENTORY_AREA but I would try to make it shorter: SRC_INV_AREA

**Comment by prvernier** [comment]
CASFRI_AREA works. We already have SOURCE_DATA_FORMAT and SOURCE_DATA_PHOTOYEAR so 
SOURCE_INVENTORY_AREA (or maybe SOURCE_DATA_AREA) would be more consistent unless we shorten all SOURCE_* attribute names to SRC_*.

**Comment by pedrogit** [comment]
I vote for shorter column names as far as they are meaningful. INVENTORY can also be shortened to "INV".

**Comment by prvernier** [comment]
We also have INVENTORY_TYPE, INVENTORY_VERSION, and INVENTORY_MANUAL. Maybe we could keep long names unless they have more than 2 components e.g., SRC_INV_AREA?
There's also inconsistency e.g., PHOTOYEAR and PHOTO_YEAR.

**Comment by pedrogit** [comment]
Good idea. Consistency is important.

**Comment by edwardsmarc** [comment]
Added #139 for standardizing casfri attributes.

**Comment by prvernier** [comment]
Done
