### ISSUE TITLE
nb01_nbi01_lyr.csv needs custom function for PRODUCTIVE_FOR

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#134]
Hi @edwardsmarc - we need a custom function for productive_for. You can view the code in the corresponding rmarkdown document.

**Comment by edwardsmarc** [comment]
This code uses the following:

crown_closure_lower %in% c(-8888,-9999) | height_lower==-9999

Do we know what -8888 and -9999 represent in this case? Are they based on our own error codes, or the old error codes used in CAS04?

Currently CROWN_CLOSURE_LOWER does not have a -9999 error code in CAS05.

**Comment by prvernier** [comment]
They should probably both be c(-8888,-9999) or just -8888. The error codes are correct with -8888 being NULL and -9999 OUT_OF_RANGE. I would opt for the former since 0 values are not specified in the NB inventory. I'll update the Rmd with the second -9999.

**Comment by edwardsmarc** [comment]
And for CROWN_CLOSURE_LOWER, should it be -9998? To indicate a value that is not in (1,2,3,4,5)?

For the custom function I can't reference the CASFRI values so I'll be using the actual helper functions used for CROWN_CLOSURE and HEIGHT. I just want to make sure I use the correct ones.

For example to match you logical test:

crown_closure_lower %in% c(-8888,-9999) | height_lower==-9999

I would use (from the translation table):

notNull(l1cc) = FALSE OR matchList(l1cc,{'1','2','3','4','5'}) =FALSE OR notNull(l1ht) = FALSE OR isGreaterThan(l1ht,'0.1') = FALSE OR isLessThan(l1ht, '100') = FALSE

So any case where CASFRI would return -9998 or -8888 for CROWN_CLOSURE_LOWER, or -9999 or -8888 for HEIGHT_LOWER.

**Comment by prvernier** [comment]
I guess -9998 (NOT_IN_SET) is probably a little more appropriate then -9999 (OUT_OF_RANGE) for CROWN but not HEIGHT. Yes, so that makes sense. I've updated the markdown and pushed it.

**Comment by edwardsmarc** [comment]
Note that since every row will be assigned either PP or PF using this function, there is no way to run a validation function. Validation rule should be TT_True().

**Comment by pedrogit** [comment]
Has the function been integrated in the translation file?

**Comment by edwardsmarc** [comment]
Yes just pushed nb01 lyr and eco tables.
