### ISSUE TITLE
Dealing with missing photo year values

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#136]
The AB photo year table contains rows that are labelled as 'not known' for the photo year.

When these are returned as the intersecting row in the engine, the GeoIntersectionInt function will return NULL because 'not known' cannot be cast to an int. This causes the generic translation error to be returned to the CASFRI output table.

Option 1.
Leave as is. We want an error code to be returned in these cases. The only issue is that the error code is not meaningful.

Option 2.
Add new validation helper functions that check the return type of the intersecting row. This would be costly because we would have to run the intersection during both validation and translation for many rows.

Option 3.
Add the type check to the existing geoIntersects() validation function. This function currently just checks that the FRI row intersects with the photo year table. We could add an optional parameter called checkType that checks the intersecting value matches the requested type.

I like option 3 because it limits the number of intersections that have to be run. The maximum would 2 per row, one for validation and one for translation.

**Comment by pedrogit** [comment]
Some more options:

Option 1.1.
Set a project error code in place of the default translation error.

Option 4.
Fix the photo_year file by removing the rows not having a meaningful year.

**Comment by edwardsmarc** [comment]
Following our general philosophy that dependency tables should be validated by the user, option 4 seems more logical than options 2 or 3. The functions we currently have are adequate for doing the translation, so maybe we decide that the photo year table should be fit for purpose instead of adapting the engine to work with the unusual data format?

We did create the photo year file ourselves so there's no reason why we can't just edit it.

**Comment by pedrogit** [comment]
I think solutions involving new validation rules are not necessary since the whole file was already validated once and it failed. We can not expect further validation to "fix" this.
