### ISSUE TITLE
Refactor the way the HDR table is produced

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#140]
The HDR table is a metadata table not constructed from source data but from the inventory list (https://github.com/edwardsmarc/CASFRI/blob/master/docs/inventory_list_cas05.csv).

The inventory list should be loaded in conversion stage and a translation file should translate it to HDR.

**Comment by prvernier** [comment]
The table below compares and matches (where possible) the attributes from the inventory_list_cas05 table and the HDR table. If we stay with the current HDR attributes: we would load the inventory_list_cas05, select the appropriate attributes, and rename them to the proper "HDR" names (using a conversion script and a translation table). However, we may want to consider using the same names in both tables (for the attributes in common). The other consideration is if we want to expand the HDR tables to include all the attributes in the inventory_list_cas05 table.

inventory_list_cas05 | hdr_attributes
-- | --
INVENTORY ID | HEADER_ID
  | JURISDICTION
OWNER TYPE | OWNER_TYPE
OWNER NAME | OWNER_NAME
STANDARD NAME | INVENTORY_TYPE
STANDARD VERSION | INVENTORY_VERSION
STANDARD ID |  
STANDARD REVISION |  
DOCUMENTATION TYPE | INVENTORY_MANUAL
FORMAT | SRC_DATA_FORMAT
DATE_PUBLISHED |  
ACQUISITION DATE | ACQUISITION_DATE
DATA TRANSFER | DATA_TRANSFER
RECEIVED FROM | RECEIVED_FROM
CONTACT INFO | CONTACT_INFO
DATA AVAILABILITY | DATA_AVAILABILITY
REDISTRIBUTION  (derived product) | REDISTRIBUTION
PERMISSION | PERMISSION
LICENSE AGREEMENTS | LICENSE_AGREEMENT
PHOTOYEAR DETAILS |  
PHOTOYEAR START | PHOTO_YEAR_START
PHOTOYEAR END | PHOTO_YEAR_END
COVERAGE IMAGE |  
COMMENT |  
ExportedSourceFiles  Pythonscript (v4) |  
PHOTOYEAR TYPE | PHOTO_YEAR_SRC
LOCATION |  
CAS02 |  
CAS03 |  
CAS04 |  
CAS05_initial |  
CAS05_temporal |

**Comment by pedrogit** [comment]
I would say:

- Renames inventory_list_cas05 attributes to match hdr attributes.
- All hdr attributes should be found in inventory_list_cas05 but not necessarily the opposite (otherwise they would become identical). See inventory_list_cas05 as having everything from the target HDR plus some information useful only to us.

If attribute data is encoded the same way in both tables then there is no need for a translation table. A simple SELECT query selecting the proper columns would do.

**Comment by prvernier** [comment]
I've renamed the inventory_list_cas05 attributes to match HDR attributes. I've also renamed a couple more non-HDR attributes for consistency (e.g., STANDARD_ID --> INVENTORY_ID). See comparison table below. I've also renamed the old file "inventory_list_cas05_older_version.csv" until we're happy with changes. This should be a simple filter and select function to pull out what's need for each HDR table.

hdr_attributes | inventory_list_cas05 | inventory_list_cas05_new | Comment
-- | -- | -- | --
header_id | INVENTORY ID | HEADER_ID |  
jurisdiction |   | JURISDICTION |  
owner_type | OWNER TYPE | OWNER_TYPE |  
owner_name | OWNER NAME | OWNER_NAME |  
inventory_type | STANDARD NAME | INVENTORY_TYPE |  
inventory_version | STANDARD VERSION | INVENTORY_VERSION |  
  | STANDARD ID | INVENTORY_ID |  
  | STANDARD REVISION | INVENTORY_REVISION |  
inventory_manual | DOCUMENTATION TYPE | INVENTORY_MANUAL |  
src_data_format | FORMAT | SRC_DATA_FORMAT |  
  | DATE_PUBLISHED | DATE_PUBLISHED |  
acquisition_date | ACQUISITION DATE | ACQUISITION_DATE |  
data_transfer | DATA TRANSFER | DATA_TRANSFER |  
received_from | RECEIVED FROM | RECEIVED_FROM |  
contact_info | CONTACT INFO | CONTACT_INFO |  
data_availability | DATA AVAILABILITY | DATA_AVAILABILITY |  
redistribution | REDISTRIBUTION  (derived product) | REDISTRIBUTION  (derived product) | Name not consistent
permission | PERMISSION | PERMISSION |  
license_agreement | LICENSE AGREEMENTS | LICENSE_AGREEMENT |  
  | PHOTOYEAR DETAILS | PHOTO_YEAR_DETAILS |  
photo_year_start | PHOTOYEAR START | PHOTO_YEAR_START |  
photo_year_end | PHOTOYEAR END | PHOTO_YEAR_END |  
  | COVERAGE IMAGE | COVERAGE_IMAGE |  
  | COMMENT | COMMENT |  
  | ExportedSourceFiles  Pythonscript   (v4) | ExportedSourceFiles  Pythonscript   (v4) | Name not consistent
photo_year_src | PHOTOYEAR TYPE | PHOTO_YEAR_SRC |  
  | LOCATION | LOCATION |  
  | CAS02 | CAS02 |  
  | CAS03 | CAS03 |  
  | CAS04 | CAS04 |  
  | CAS05_initial | CAS05_initial | Name not consistent
  | CAS05_temporal | CAS05_temporal | Name not consistent

**Comment by pedrogit** [comment]
Seems to me that most of the first ones in inventory_list_cas05, up to DOCUMENTATION TYPE  (INVENTORY ID, STANDARD NAME, STANDARD VERSION, STANDARD ID, STANDARD REVISION, DOCUMENTATION TYPE) were making more sence than the ones in HDR. But they had to have an underscore added.

Maybe STANDARD ID, STANDARD REVISION and STANDARD REVISION sould make it into HDR.

**Comment by prvernier** [comment]
I assume you meant STANDARD_VERSION for your second attribute. I would also consider changing HEARER_ID to INVENTORY_ID since it makes more sense. This would mean that for the first 9 attributes (for both the HDR table and the inventory_list) we would have: INVENTORY_ID, JURISDICTION, OWNER_NAME, STANDARD_TYPE, STANDARD_VERSION, STANDARD_ID, STANDARD_REVISION, INVENTORY_MANUAL

**Comment by edwardsmarc** [comment]
I agree with adding STANDARD_ID and STANDARD_REVISION to the HDR files. This is key information for understanding the CASFRI translation tables.

**Comment by edwardsmarc** [comment]
Since attribute names now match between CASFRI and the inventory_list csv, we can write an SQL script to create all HDR tables from the inventory_list csv.

We can also delete the HDR translation tables.

**Comment by edwardsmarc** [comment]
This code would be more appropriate in the sample workflow file since we do not currently save the translated tables for each FRI individually. We append them all together directly in the sample workflow script.

**Comment by edwardsmarc** [comment]
closed with 29839d560d4fcabe1d54e65ff402c6c6a4f389a1
