### ISSUE TITLE
Loading script - NB02

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#143]
Load NB02 FRI.

**Comment by prvernier** [comment]
For NB02, only the forest and non-forest data are new. Waterbody and wetlands are the same. Forest and non-forest are available in geodatabase and shapefile formats but since we only have water and wetlands as shapefile maybe we can stay with all shapefiles.

**Comment by edwardsmarc** [comment]
Yes shapefiles is probably easiest for this one.

**Comment by prvernier** [comment]
Okay, good. I've copied waterbody.shp and wetland.shp from the "nb01" to the new "nb02" folder and downloaded the latest forest.shp and nonforest.shp to the same folder. Note that the names of the latter are actually "geonb_forest-foret.shp" and "geonb_nonforest-nonforet.shp". Do we want to keep these new names or rename to forest and nonforest?

**Comment by pedrogit** [comment]
Better keep the original names for FRIs.

**Comment by prvernier** [comment]
I've also downloaded the latest wetlands even though it's probably the same as the older one. Plus, there's a new hydrology set of maps which seems to have waterbody. I'll explore and include as needed.

**Comment by pedrogit** [comment]
Time to fix #40 before we import too many FRIs?

**Comment by edwardsmarc** [comment]
The new geonb_forest-foret.shp has two layers. All attributes are repeated so that file has e.g. L1DATAYR and L2DATAYR. The other shapefiles (nonforest, waterbody, wetland) just have e.g. DATAYR.

@prvernier Will we need both layers? Or just layer 1? If we are just using layer 1 we can change the photo year column from L1DATAYR to DATAYR during loading so it matches with the other shapefiles. Otherwise we'll need a custom helper function to create the PHOTO_YEAR target attribute during translation (because it'll be copying from two different columns).

**Comment by prvernier** [comment]
We had 2 layers in nb01 and kept them in the same translated tables. I think we should keep both layers but maybe split them into nb02_lyr1.csv and nb02_lyr2.csv rather than have them in the same files. In the FRI, the L1 and L2 attributes are all fields, so the number of polygons is stable. In our translated files, the number of polygons increases by L2 (L1 + L2 stacked). It would make photo year more complicated.

Also, the new inventory has some changes in attributes names from the previous version. Otherwise looks fairly similar.

**Comment by prvernier** [comment]
We now have 4 new files to process for nb02:

- forest = geonb_forest-foret.shp
- nonforest = geonb_nonforest-nonforet.shp
- waterbody = NBHN_0000_02_Wb.shp
- wetland = NBHN_0000_03_Wl.shp

The coverage of New Brunswick is more complete than nb01 and includes less ocean.
