### ISSUE TITLE
Copy all inventory specific documents to new folder structure

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#145]
This includes CAS_04 documentation and any new documentation acquired in CAS05. Do this for focal inventories only.

**Comment by MelinaHoule** [comment]
@prvernier I am working on https://github.com/edwardsmarc/CASFRI/issues/40. What is the difference between issue 40 and this one. To me it looks the same. If it is, this one should be closed.

**Comment by prvernier** [comment]
I agree, looks like a subset of #40. Let's close it.
