### ISSUE TITLE
Add validation function for vri non forest translations

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#147]
TT_vri01_non_for_veg_translation, TT_vri01_nat_non_veg_translation, TT_vri01_non_for_anth_translation should not return 'NULL' string. We should add a validation rule that returns FALSE in this case and allow the error code NOT_APPLICABLE to be returned.

The 'NULL' string in the translation rules should be changed to NULL.

**Comment by pedrogit** [comment]
The 'NULL' string was already changed to NULL in https://github.com/edwardsmarc/CASFRI/commit/6e6e32d8b2436875bd28bf46052155f78f6fb959#diff-150ed55a604bb0009793f436e271480e
