### ISSUE TITLE
Convert CASFRI standard to md

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#15]
Convert CASFRI standard to Rmd. Save all tables as csv's, call from Rmd.
- conversion in progress to bookdown format (rmd and csv files)
- located in doc/specifications (csv in tables folder)
- rmd files can be edited directly; PV will compile the book whenever new edits have been made
- appendices make up the bulk of the document and these will be converted on attribute at a time, prioritizing the ones that were selected for this quarter

**Comment by prvernier** [comment]
Main document translation completed. Appendices are now in a spreadsheet and can thus be edited. A new issue will be opened for converted individual worksheets to csv files in next quarter.
