### ISSUE TITLE
Test logging and fix translation tables

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#151]
Test new logging features using workflow.

Use this to identify and fix errors in translation tables.
e.g. NULL or EMPTY values invalidated by match() instead of notNull() and notEmpty()

**Comment by edwardsmarc** [comment]
Logging is working well for testing and fixing translation tables.

**Comment by pedrogit** [comment]
> Logging is working well for testing and fixing translation tables.

Did you fix any?

**Comment by edwardsmarc** [comment]
Minor fixes detailed in commits to #157 and #180
