### ISSUE TITLE
Implement temporalization

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#155]
Temporalization will be implemented according to the roadmap document. Each polygon will be splitted into many parts, each part being valid for a specific time interval.

Computed time interval for each polygon parts will be based on the STAND_PHOTO_YEAR attribute. It is still to determine what to do when stand_photo_year is not set (leave them or fix them. See issue #249 and #248).

Once issues with STAND_PHOTO_YEAR are solved, implementing temporalization becomes only a matter of writing a function taking the name of a table having a geometry column and a year and to compute all the historical parts of this polygons and their associated VALID_YEAR_START and VALID_YEAR_END values.

SELECT * FROM TT_GeoHistory(schemaName, tableName, uniqueIDColumn, geoColumnName, photoYearColName, hasPrecedenceFct, isValidFct)

will return a SETOF (geom, validYearStart, validYearEnd) for each polygon.

hasPrecedenceFct, if provided, is the name of a function taking two RECORDs. When two overlapping polygons of the same year are compared, TT_GeoHistory() will call this function to determine if the  RECORD corresponding to the first polygon takes precedence over RECORD of the second one. If hasPrecedenceFct returns TRUE, the first polygon takes precedence over the second one. If hasPrecedenceFct returns FALSE, the second polygon takes precedence over the first one. If hasPrecedenceFct is not provided, TT_GeoHistory() always gives precedence to the polygon having the highest uniqueIDColumn.

isValidFct, if provided, is the name of a function taking one RECORD. It is used to determine if a polygon must be taken into account when computing old and future history of the area covered by a polygon. It will typically return FALSE if all significant attributes are NULL, leading TT_GeoHistory() to ignore this polygon. If only one significant attribute is not NULL, isValidFct returns TRUE. If isValidFct is not provided, all poygons are considered valid.

In an alternative version of TT_GeoHistory() hasPrecedenceFct and isValidFct have hardcoded names. There is only need to pass a list of attribute names (e.g. "cas_id, dist_type_1, species_1") to TT_GeoHistory() to activate the precedence and the validation mechanism. The advantage is that since TT_GeoHistory() knows the list of values to pass to both functions, it does not have to blindly and inefficiently pass all of them.

Some questions regarding the values assigned to VALID_YEAR_START and VALID_YEAR_END:

- If the earliest year for the area covered by a polygon part is 2000, should this become its VALID_YEAR_START or should it be assigned an earlier, arbitrary VALID_YEAR_START (e.g. 1940 or 1900) since this is all the info we have for the past of this area?

-  If the latest year for the area covered by a polygon part is 2020, should this become its VALID_YEAR_END or should it be assigned a later, arbitrary VALID_YEAR_END (e.g. 3000 or NULL) since this is all the info we have for the future of this area?

**Comment by kdarndt** [comment]
Have you looked into TimeScaleDB?  https://github.com/timescale/timescaledb

It is focussed on regular time series data, but the query functions could still be used with CASFRI.

**Comment by pedrogit** [comment]
There is a drawing in the Roadmap document (https://docs.google.com/document/d/1m3le0t9blFa0cpWOjYS93cSzHvPr7z5alRthcttRsUE/edit?usp=sharing)

**Comment by pedrogit** [comment]
What happen when a same polygon is repeated two or more times in the same inventory with different CAS_ID (e.g. one carries forest info and the other disturbance info). How can we infer forest info to complement the disturbance info (see #315)?

**Comment by kdarndt** [comment]
Interesting thought.  A similar question comes to mind:

If you have a smaller polygon that is totally enclosed by a larger, older one -- but the larger one has a richer attribute set, do you include the attributes from the larger polygon for the years when the smaller one is valid?

**Comment by pedrogit** [comment]
The algorithm use a TT_RowIsValid() function to determine if a polygon is associated with meaningfull attributes or not. So a polygon is only valid or invalid. In your case if a bigger, older polygon encloses a smaller, newer polygon but both are valid, oldest info are replaced by new ones. If the newer polygon is invalid, the older has precedence. Similarly if the older is invalid, the newer replace the older in the past.

We could implement a "more rich/less rich" function instead of a simple "valid/invalid", but then we would have the difficult problem of defining what are the conditions making a set of attribute "richer" than another one.

**Comment by kdarndt** [comment]
What if the smaller polygon has most attributes, but is missing 1 or 2 -- and the older has the attributes missing from the smaller one.

Is there provision for "filling-in" missing attributes from overlapping polygons that might be older/lesser priority?  This might be solved using whatever methodology you might develop to cover your earlier comment.

**Comment by pedrogit** [comment]
Nothing like this is planned for now.

It's true that that would solve the "depletion update" issue. i.e. newer disturbance only rows would get filled with missing forest info from older polygons.

That would make the inventory "cumulative" in that it would cumulate old information.

But then we can ask the opposite question: Why not try to "fill-in" old polygons with newer info when it's missing in the old one? These is no apriori reason not to do it in this direction as well.

Wondering if that would not lead to some row inconsistencies.

**Comment by pedrogit** [comment]
I guess we might let this to the user. After all that's just a big aggregate query over all the current and older polygons using coalesce().

There is also the fact that "fill-in" newer records with older record is not necessarily related to the temporalisation problem. We could decide to have an aspatial version of the database "fill-in" newer inventories with older ones that has nothing to do with the geometries.

It's less interesting because older info not complementing newer info would be lost, but such a version would definitely also have some value.

**Comment by kdarndt** [comment]
Let me check with Brian and Graham on the meaning of the deliverable:

"a CASFRI query script that combines the best (most complete attribution) ...."

That's where I was taking this requirement from.  Like you said, it might be as simple as a COALESCE query.

**Comment by pedrogit** [comment]
Interesting. That was not in previous versions of the contract. I guess we have always assumed that newer inventories always carries older information when it's possibe. Obviously they don't always do it. 

I would still interpret "most complete attribution" by "most up to date".

**Comment by kdarndt** [comment]
It was on the original contract (task 4), but not shown beside the milestone dates -- a bit confusing.

There's some question in our team about how/whether this should be implemented ("complete attribution" deliverable), so I'll arrange a meeting to discuss.

**Comment by pedrogit** [comment]
What I understand from TimeScaleDB is that it's made for huge time series having hundreds of millions of time entries. Historical CASFRI should not have very many time entries for each single point in space. Maybe ten or twenty (overlapping updates).

If we would call TimeScaleDB's time series huge "vertical" datasets, then CASFRI is the opposite: it's a huge "horizontal" dataset with many entries spread spatially but with few vertical entries.

I would think about TimeScaleDB as the vertical or time version of PostGIS. TimeScaleDB is good at partitionning in time. PostGIS at partitionning in space.

**Comment by kdarndt** [comment]
Hi Pierre, that seems like a good analysis.  CASFRI isn't really time-series data, and it will need to accommodate backfilling information (loading old inventories) which TimeScaleDB isn't really focused on.  I had thought the built-in query mechanism and automatic partitioning might be useful to improve performance.
But, if you feel it isn't a good fit, it might be more straight forward to, in the future, develop a custom partitioning structure to improve performance.

**Comment by pedrogit** [comment]
Just so we remember, here is a copy of the email from KA summarizing what was agreed about the definition of "most complete attribute" and the treatment of "depletion updates":

1. The meaning & expectations of the deliverable “a CASFRI query script that combines the best (most complete attribution) and most relevant (inventory date closest to user-specified date of interest) available FRI data into a topologically clean dataset with no overlaps for the user-specified area of interest.”  

We agreed that “most complete attribution” simply means choosing the most attribute-rich polygon (ie: among overlapping polygons within the same year) within the historical database.  No attributes from different polygons will be carried “forward” or “backward” in time to fill in gaps in other polygons.

2.  Incorporating “depletion” inventories into CASFRI.  Depending on the nature of depletion inventories, this topic may be related to topic (1).

Depletion updates and disturbance information contained in regular inventories are desirable in CASFRI.  We want a user, when querying the historical database, to know when a disturbance has affected a particular polygon and be able to also query the stand information for that polygon as it existed prior to the disturbance.  There are several technical ways to implement this which were not fully discussed in the call as that was out of scope of this meeting.  Disturbance information and regular inventory information will remain separate in the “raw” (non-historical) CASFRI tables.

**Comment by pedrogit** [comment]
Closing as code associated with producing the historical database is now fully functional and works very well on pg13/PostGIS 3.1. Further issues will be documented separately.
