### ISSUE TITLE
Should loading scripts always use source files?

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#162]
* For NT01, the source data are provided in two overlapping shapefiles. One of these has the geometries and attributes separated.
* For CAS03 the attributes were joined to the geometries, then the two files were merged and a photo year table was joined. The resulting pre-processed shapefile was then loaded. We have a copy of this pre-processed shapefile.
* The source data geometry we have stored already has the attributes joined, I expect this was done manually and the original un-joined geometries were lost. The path from source data to loaded data is now broken. i.e. we can't provide a script that completes the full procedure unless we re-create or re-request the original separated geometries.
* Since this is an old dataset, there's also no guarantee the client will receive it in the same format we did.

* Should we try and write a script that loads the data from scratch using the original source data?
* Or should we just load the pre-processed shapefile that was made for CAS03?

**Comment by pedrogit** [comment]
Just load the preprocessed for now. We can remake a loading script loading the original if the client ever need it.
