### ISSUE TITLE
Allow multiple NFL values per polygon

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#164]
Currently translation tables select only one NFL component per row.

It's possible there could be more than one. For example in BC a polygon could contain a river as well as some bryoid and shrub cover (we should run some tests to check this is the case).

Should we accommodate this by using multiple NFL translation tables. This would create multiple NFL output rows in separate tables that could then be merged into a one-to-many NFL table.

We would need as many translation tables as there are possible NFL outputs. For BC this would be at least 3 tables, one for NNV, NFV, NFA. 

However NFL values are defined from land_cover_class_cd_1, there are also land_cover_class_cd_2 and land_cover_class_cd_3 which could be included. Similarly there are non_veg_cover_type_1, non_veg_cover_type_2, and non_veg_cover_type_3.

Since CASFRI does not define percentages for NFL values, is there any point in including multiple NFL attributes? Or should we just stick to one as we have been doing?

As an example, a BC polygon we have been reviewing contains 55% Bryoid and 45% Shrub defined in land_cover_class_cd_1 and land_cover_class_cd_2. Currently the NFL table just reports the Bryoid. But not the Shrub, and there is no associated percentage.

**Comment by pedrogit** [comment]
I wonder if CASFRI was intented to allow more than one row for NFL component. We could probably allows more than one in the current schema and use structure_per (normally reserved for horizontal structure) to store the percentage. CASFRI 4 did sometimes model more than one NFL component per stand but it was putting then in different layers. Was that a bug or a wrong implementation? No idea...

**Comment by edwardsmarc** [comment]
Closing. We can now add multiple NFL layers if they exist using the attribute_dependencies.csv table. In BC we are sticking with the CAS04 translation that creates one NFL value per polygon.
