### ISSUE TITLE
QC01 map tiles do not all have matching attributes

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#167]
The map tiles beginning in '11' have a different set of attributes.

Are these using a different standard? Do they have all the attributes we need for translation?
* If yes, just append them after the others are done and the matching attributes will be loaded.

**Comment by MelinaHoule** [comment]
Tiles starting with 11 are îles de la Madeleine. They are using the same standard and they have all the attributes needed for translation. It happens with old inventories that format between tiles were not perfectly standardized prior to send them to us.

**Comment by pedrogit** [comment]
Closed with #187.
