### ISSUE TITLE
Some translation tables are identical and should be replaced with VIEWs

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#168]
Whenever possible, when a translation file is basically a copy of another one but for another set of source attributes sharing the same specifications (e.g. dist1, dist2, dist3 or species_1, species_2, species_3, etc...), it is preferable to make a VIEW mapping the second and third set of attribute to the first one and reuse the first translation file instead.

Right now this applies to nb02_nbi01_dst2.csv and nb02_nbi01_lyr2.csv. These files should be replaced with VIEWs in the workflow.

This method should also be used to produce translation layer 2 values for NB01. Here is a complete SQL workflow example for this case:

-- Prepare the translation function
SELECT TT_Prepare('translation', 'nb01_nbi01_lyr', '_nb01_lyr');

-- Translate the first set of attribute
INSERT INTO casfri50.lyr_all
SELECT * FROM TT_Translate_nb01_lyr('rawfri', 'nb01', 'ogc_fid');

-- NEW PART
-- Create a slightly modified copy of the translation table
CREATE TABLE translation.nb01_nbi01_lyr2 AS
SELECT * FROM translation.nb01_nbi01_lyr;

UPDATE translation.nb01_nbi01_lyr2 
SET translationrules = 'copyInt(''2'')' 
WHERE rule_id = '4' OR rule_id = '5';

SELECT * FROM translation.nb01_nbi01_lyr2;

-- Prepare the transltion function for layer 2
SELECT TT_Prepare('translation', 'nb01_nbi01_lyr2', '_nb01_lyr2');

-- Create a view mapping the second layers disturbances attribute on the first
CREATE OR REPLACE VIEW rawfri.nb01_lyr2 AS
SELECT src_filename, stdlab, ogc_fid, fst,
           l2estyr l1estyr,
	   l1trt, l2trt, 
	   l2cc l1cc, l2ht l1ht, 
	   l2s1 l1s1, l2pr1 l1pr1, 
	   l2s2 l1s2, l2pr2 l1pr2, 
	   l2s3 l1s3, l2pr3 l1pr3, 
	   l2s4 l1s4, l2pr4 l1pr4, 
	   l2s5 l1s5, l2pr5 l1pr5
FROM rawfri.nb01;

-- Add to the translate using this view to add layer 2 values
INSERT INTO casfri50.lyr_all
SELECT * FROM TT_Translate_nb01_lyr2('rawfri', 'nb01_lyr2', 'ogc_fid');

**Comment by edwardsmarc** [comment]
What is the advantage of this over just using a second translation table? It seems simpler to just have one translation table for each layer. 

I understand that using VIEWs eliminates a table, but it also adds a lot of code to the workflow. We also lose the documentation of rules provided by the translation table. Now the only way to understand the translation for layer 2 is to work backwards through the SQL code to link the mapped attributes to the translation rules in layer 1.

**Comment by edwardsmarc** [comment]
For NB02, the layer 1 and layer 2 tables are identical. Layer 2 should use a view.

NB01 and NB02 LYR translation tables are identical, except for attribute l1estyr changes to l1estabyr, and the PRODUCTIVE_FOR validation and translation rules change.

We can use a VIEW on NB01 for translating NB02. The attribute can be changed in the VIEW as demoed above. 

Question is, should we update the PRODUCTIVE_FOR validation and translation rules using SQL as demoed above, or should we have an NB02 translation table just including this row, and copy the row into the VIEW from the table? That way we maintain the documentation of the rule and the description in the translation table.

**Comment by pedrogit** [comment]
> What is the advantage of this over just using a second translation table? It seems simpler to just have one translation table for each layer.

The advantage is that, when you fix a bug or add a feature, you don't have to fix (mostly importantly you don't FORGET to fix) the other table. That means also less maintenant since you have only one table to modify. This advantage exists only if you can modify the base translation table without having to modify the SQL code (which is normally the case here).

> I understand that using VIEWs eliminates a table, but it also adds a lot of code to the workflow.

But this code is normaly invariant when you fix bugs or make changes to the table. 

> We also lose the documentation of rules provided by the translation table. Now the only way to understand the translation for layer 2 is to work backwards through the SQL code to link the mapped attributes to the translation rules in layer 1.

You could write the table and the translation description as a generic standard multi-inventory translation table instead of an inventory specific translation table. This way the explanation stand for any specific inventory. e.g. you can name it based on the standard instead of the inventory and you can refer to both source field instead of only NB01 fields.

**Comment by pedrogit** [comment]
> Question is, should we update the PRODUCTIVE_FOR validation and translation rules using SQL as demoed above, or should we have an NB02 translation table just including this row, and copy the row into the VIEW from the table? That way we maintain the documentation of the rule and the description in the translation table.

Could you have a generic rule that works for both?

**Comment by edwardsmarc** [comment]
At present they are completely different. But given the attributes are mostly the same I don't see why we can't use the same rules for both. In fact I'm confused as to why we are not currently using the same rules for both.

See #182 for details.
