### ISSUE TITLE
Empty NFL, ECO and DST rows should be filtered out with a VIEW

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#170]
The best way to filter out NFL, ECO and DST empty rows is to create a view on the source table filtering out the rows not having meaningfull values for those target tables. e.g.

CREATE OR REPLACE VIEW rawfri.ab06_dst AS
SELECT src_filename, ogc_fid, poly_num, 
       mod1, mod1_ext, mod1_yr, mod2, mod2_ext, mod2_yr, trm_1
FROM rawfri.ab06
WHERE TT_NotEmpty(mod1) OR (NOT mod1_yr IS NULL AND mod1_yr != 0) OR (NOT mod1_ext Is NULL AND  mod1_ext != 0) OR
TT_NotEmpty(mod2) OR (NOT mod2_yr IS NULL AND mod2_yr != 0) OR (NOT mod2_ext IS NULL AND mod2_ext != 0);

-- Use the view as source table (no need to re-prepare the translation table)
SELECT * FROM TT_Translate_ab06_dst('rawfri', 'ab06_dst', 'ogc_fid'); -- 5 s.

**Comment by edwardsmarc** [comment]
This makes sense and will save a lot of processing time.

**Comment by pedrogit** [comment]
Here is what I propose:

The original idea was to filter out non contributing rows to LYR, NFL, DST and ECO with VIEWs.

However we already have TT_CreateMappingView()  which create VIEWs for us for similar inventories and extra layers. The idea is to generalise the use of TT_CreateMappingView() so that it can also create VIEWS that filter out non contributing rows.

TT_CreateMappingView() would have an extra parameter accepting 'LYR', 'NFL', 'ECO' or 'DST'

When set to 'LYR', all rows having all attributes used to translate all SPECIES_X set to NULL or EMPTY with be filtered out.

When set to 'NFL', all rows having all attributes used to translate NAT_NON_VEG, NONFOR_ANTH or NON_FOR_VEG set to NULL or EMPTY with be filtered out.

When set to 'DST', all rows having all attributes used to translate DIST_TYPE_1, DIST_YEAR_1, DIST_TYPE_2, DIST_YEAR_2, DIST_TYPE_3, DIST_YEAR_3 set to NULL or EMPTY with be filtered out.

When set to 'ECO', all rows having all attributes used to translate WETLAND_TYPE set to NULL or EMPTY with be filtered out.

In some cases (BC), some attributes (INVENTORY_STANDARD_CD) are always not NULL even when the row is not contributing and should be filtered. We can handle thoses case by passing a comma separated list of significant attribute instead ({land_cover_class_cd_1, non_productive_descriptor_cd, non_veg_cover_type_1}).

**Comment by edwardsmarc** [comment]
I agree with the last sentence. We would need a parameter of attributes to ignore. All other attributes would be pulled from the dependencies table. And I guess we would hard code which CASFRI attributes (i.e. columns in the dependency table) to use for 'LYR', 'NFL' etc. into the function?

**Comment by pedrogit** [comment]
Yes we would hardcode them.

**Comment by edwardsmarc** [comment]
I'm in favor, I like that we will have one function and one table for creating all the VIEWs. And good documentation once #212 is done.
