### ISSUE TITLE
ogr2ogr geometry column should be hard-coded to avoid version differences

### ISSUE THREAD

**Issue by kdarndt** [edwardsmarc/CASFRI#174]
### Issue

Different versions or configurations of GDAL can result in different PostGIS geometry column names (ie: "wkb_geometry" vs "shape").  This results in the translation files (which expect a specific column name) marking the polygon as empty.

### Suggested Solution

Hard-code a name of the geometry column in the ogr2ogr load scripts in order to be explicit and consistent.  See: "GEOMETRY_NAME" in https://gdal.org/drivers/vector/pg.html

### See also

See also bug https://github.com/edwardsmarc/CASFRI/issues/34 which is related to GDAL versions:

**Comment by pedrogit** [comment]
.bat needs to be updated as well...
