### ISSUE TITLE
Plan a denormalized (or "flat" table) version of CASFRI

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#176]
What should be the structure of this denormalized version of CASFRI (attributes, structure)?

Roughly I can see a certain number of species (10), a certain number of NFL components (3?) and a certain number of disturbances (3?) and one flat table per layer, but we have to produce an exact schema.

**Comment by pedrogit** [comment]
What is better:

A) One row per layer per cas_id (i.e. up to four rows per polygons, no LYR info on the same row as NFL)

or

B) Only one row per cas_id with 2nd, 3rd and 4th layer as additional columns (one overstory set od columns for LYR layer 1, one understory set for LYR layer 2, two sets for NFL components for layer 3 and 4)

**Comment by edwardsmarc** [comment]
Note that for SK we could have up to 5 or 6 layers in total. Three LYR and two or three NFL. So maybe A is better?

**Comment by pedrogit** [comment]
Ok. I'll implement A).

**Comment by pedrogit** [comment]
It's just strange that, for a particular row, LYR info will always be empty when there is NFL info and vice versa.

**Comment by pedrogit** [comment]
DST info will always be stored in the layer = 1 row. Additional layers will have NULL DST info as well (as LYR info for NFL rows and vice versa).

**Comment by pedrogit** [comment]
It seems to me that a true flat table would attempt to flatten one-to-many relations between CAS and LYR and NFL as well, putting everything on the same row. THe ned result is only one row per polygons. For SK we could just forget LYR layer 3 and NFL layer 3 the same way we forget about the last species.

**Comment by kdarndt** [comment]
Looking at the past comments, I think having NULL columns is a normal byproduct of creating a denormalized table.  
I wouldn't worry about, for example, the LYR info always being empty when there is NFL info (and vice versa).

The important thing, for me, is that this denormalized table is derived from the regular CAS schema (that updates do not happen to the denormalized table).  Perhaps a Materialized View would be appropriate here.

I would tend to prefer having a row per-layer per-polygon (ie: 1-6 rows per cas_id).  I think that's option (A) above.

**Comment by pedrogit** [comment]
Both options were implemented. Both as MATERIALIZED VIEWs.

Closed with https://github.com/edwardsmarc/CASFRI/commit/02797823752c9ca3aedc8775a77732e9de1e0f51
