### ISSUE TITLE
Review implementation of STRUCTURE_PER in existing translation tables

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#178]
This affects: AB06, AB16, BC08, BC09, NB01, NB02

**Comment by prvernier** [comment]
**From Cosco 2011:**

The attribute structure_per is assigned when a complex or horizontal structured polygon is identified. Stand structure percent is used with horizontal stands and identifies the percentage of stand area, assigned in 10% increments, attributed by each stratum within the entire polygon and must add up to 100%. Any number of horizontal strata can be described per horizontal polygon.

- Structure_per: Used with horizontal stands to identify the percentage, in 10% increments, strata within the polygon. Must add up to 100%. Only two strata represented by each homogeneous descriptions are allowed per polygon.
- Values: 1 - 9

**Comments:**

- The original specification has a couple inconsistencies. First, it says that percentages must add up to 100% but that permitted values should be 1-9 (although these are easily converted). Second, it states in the overview paragraph that any number of strata can be used but then also states in the table that only two are allowed per polygon.
- This attribute is relevant to AB and NB inventories but not the BC inventory. Also relevant to NT01 inventory (#177)
- From CAS04, NT_002.lyr has values 0,10,20,...90,100. Otherwise -8888.

Decisions needed:

- Should this attribute stay with 1-9 or use 1-100 or 0-100? CAS04 seems to use 0-100.
- Should 0 be translated to 0 and NULL to -9999?
- Should inventories with no structure_per information (e.g., BC08, BC09) be assigned a value of 100% (or 9) or NULL? Conversely, if inventory is not NULL, specify percentage.

Notes and inventory-species issues:

- AB06: the source attribute struc_val has values ranging from 0-9; currently we keep those values except for 0 which we translate to -9999.
- AB16: the source attribute std_struct has values that include (“”, “ 0”, “0”, “C4”, “C5”, “M”, “M0”, “MO”). Does C mean complex and are 4 or 5 percentages*10? Does M mean multilayered?
- BC08, BC09: no source attribute; assign a value of 100 (%) or -9999?
- NB01, NB02: Is there a source attribute for this? We currently assign this attribute -8887.
- NT01: use source attribute strc_per but note that, while the NT manual specifies values 1-9, values of 0, 10 and 12 also occur. Should 0 be -9999 and 10 and 12 -8887?

**Comment by edwardsmarc** [comment]
One other note on structure_per from our meeting with JC:

When stand structure is C for complex structure, STRUCTURE_PER is used to show the range of heights within the stand. Otherwise it's used to show the percentage of the polygon taken up by each horizontal component.

**Comment by pedrogit** [comment]
> One other note on structure_per from our meeting with JC:
> 
> When stand structure is C for complex structure, STRUCTURE_PER is used to show the range of heights within the stand. Otherwise it's used to show the percentage of the polygon taken up by each horizontal component.

Could you give an example of how they store a range of heights in this attribute?

I guess this is modeled at the VERTICAL_COMPONENT level in our case.

STRUCTURE_PER  looks more and more like a tote bag for many unrelated things...

**Comment by pedrogit** [comment]
> Decisions needed:
> 
> * Should this attribute stay with 1-9 or use 1-100 or 0-100? CAS04 seems to use 0-100.
> * Should 0 be translated to 0 and NULL to -9999?
> * Should inventories with no structure_per information (e.g., BC08, BC09) be assigned a value of 100% (or 9) or NULL? Conversely, if inventory is not NULL, specify percentage.

I think true percentage are better and more flexible and that, to ease the computation of areas covered by specie and NFL components, we should default the value to 100%.

What is the meaning of 0%? Is that an error? Why would a structure represent 0% of the polygon?

**Comment by prvernier** [comment]
An example for the 0% issue is from the NT01. The corresponding source attribute is STRC_PER and it has values of 0,1,2,3,4,5,6,7,8,9,10,12 in the inventory. However, both the NWT manual and the CASFRI specs state that this attribute (STRC_PER and STRUCTURE_PER, respectively) should only have values of 1-9. If we agree to use true percentages (0-100), should source 0's be converted to 0%, NULL, or an error code? For the values 10,12, these are treated as errors.

**Comment by pedrogit** [comment]
NTFVIstand_v3_Mar06.pdf page 66 state that allowable values for STRC_PER are 1-9. So 0 should be an error!

**Comment by prvernier** [comment]
Yes, that's the same manual I was referring to. The problem is that there are 267708 0's which seems unlikely for an error. Although, strictly speaking if we follow the manual it is an error. Conversely there are only 16 and 3 polygons with values of 10 and 12, which are clearly errors.

**Comment by prvernier** [comment]
See "Notes and inventory-species issues" section in the beginning of this issue for values for various inventories. For AB06, which also had lots of 0's, we converted to -9999 (out of  range). AB16 is more problematic...

**Comment by pedrogit** [comment]
I don't see any case in AB06 where (struc=H or struc=C) and struct_val=0. 0 happens only for other values (M=5758, ' '=4702). ' ' seems to be unproductive areas. I think we should also convert them to 100 to be consistent.

**Comment by prvernier** [comment]
I was probably away when this was discussed but could you explain the logic for using 100. How would we distinguish between a true 100 representing a 9 on a 1-9 scale and a 100 representing a 0.

**Comment by pedrogit** [comment]
1) We should replace 1-9 with true percentages.

2) The logic is that a multi-layered component covers 100% of the polygon. Not 0%.

For example, if you want to compute the area covered by a specie in an horizontal structure, you would multiply the species percentage by the crown_closure, then by the structure_per and finally with the polygon area.

This "formula" still works for multi-layered structure if you set structure_per to 100%. It does not work if you set it to 0%.

What is the rationale to set 0% for multi-layered structure anyway? To me it does not make much sense. 

If structure_per is to be interpreted as "the percentage of the polygon area covered by this structure" then multi-layered have to be 100%.

**Comment by prvernier** [comment]
I understand the logic about calculating the various attributes to arrive at an area but I thought STRUCTURE_PER was only used for complex ("C") and horizontal ("H") stands and not multi-layered ("M") or single layered ("S") stands. In NT01, for example, this is the case. However, the majority of stands are "S" and "M" and with a 0 value for STRC_PER instead of something like "null". There are also 0 values for some "C" and "H" stands which should probably be "not in set". In this particular inventory there are also values of "V", "x" and "^" which must be errors. Maybe we should leave this for a hangouts call - and also deal with the AB06 and AB16 (really odd) inventories.

**Comment by pedrogit** [comment]
> I understand the logic about calculating the various attributes to arrive at an area but I thought STRUCTURE_PER was only used for complex ("C") and horizontal ("H") stands and not multi-layered ("M") or single layered ("S") stands. In NT01, for example, this is the case. 

It might be given a meaningless value in provincial inventories for 'M' and 'S' but we can decide to translate it to a meaningful value in CASFRI without falling into "interpretation".
