### ISSUE TITLE
Review CAS_ID for NB01 and NB02

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#183]
CAS_ID currently uses the attribute stdlab as the 4th argument.

This attribute only has values in the Forest dataset. The other three datasets have all zero's for this attribute.

**Comment by prvernier** [comment]
The forest data uses stdlab but this values is not unique.
The non-forest data does not appear to have any id associated with it.
The water and wetlands data both use waterid but in both cases the values are not unique.

Consequently, we may just want to use a sequence of numbers from 1 to n, where n is the maximum number of rows for each data type. The CAS_ID already includes the data type in the name (i.e., src_filename) as well as a unique value for each row in the combined dataset, this system would work.

This would require a new function to do this. If we didn't want a function, we could just generate another sequence similar to ogc_fid.

**Comment by edwardsmarc** [comment]
We can do this during loading.

Just to be clear, each of the 4 original data sets would have a unique id added from 1:nrow(original dataset).

If we call the new attribute 'dataset_id', the loaded dataset in postgresql would have four rows with value = 1. But when combined with the src_filename these would be unique identifiers.

Is that correct?

**Comment by prvernier** [comment]
Yes, that's what I had in mind.

**Comment by pedrogit** [comment]
I don't understand why the concatenation of 'nb01', src_filename, stdlab and ogc_fid does not already make the CAS_ID unique for each row...

**Comment by prvernier** [comment]
Because stdlab has a value of 0 for all polygons which don't come from the forest source dataset i.e., nonforest, wetland and waterbody.

**Comment by edwardsmarc** [comment]
The ogc_fid would provide a unique ID. 

Why do we include stdlab at all then?

**Comment by pedrogit** [comment]
Because ogc_fid does not help to find the original polygon. stdlab does even if it's not strickly unique.

**Comment by edwardsmarc** [comment]
The goal here was to allow identification of the original polygon. Currently stdlab does not do this for a large proportion of the polygons because they are all labelled zero. The postresql table is made up of 4 source tables that are appended together on loading. Only one of those tables has values for stdlab. 

The proposal is to replace stdlab in the cas_id with a new attribute that would have a valid, unique value for every source polygon, and would be created separately for the 4 original tables, prior to loading. This is not the same as the ofc_fid which is made on the appended table after loading.

**Comment by edwardsmarc** [comment]
I've changed my mind on this. I don't see a reason to add a unique id to each polygon during loading, because that doesn't allow us to trace back to the original polygon in the shapefile. I think we should manually add a unique id column to each of the 4 input shapefiles, then use those id's to construct the CAS_ID inside the db.  It only allows tracing back to the shapefile polygon in our specific copy of the source data, but it's better than nothing.

**Comment by pedrogit** [comment]
If this new ID column is named "ogc_fid" then the translation table will work for anyone who is using ogr2ogr to load the dataset. Then I don't know how ogr2ogr will react if there is already a ogr_fid column in the dataset.

**Comment by edwardsmarc** [comment]
This should work. I'll test what happens if you already have an ogc_fid column. Another option would be to add some sql code to the loading script that deleted the ogr2ogr ogc_fid column after loading, and renamed our new column 'ogc_fid'.

**Comment by edwardsmarc** [comment]
If an ogc_fid is already present the one I created gets lost. So we need to add unique IDs with a new column name.

Having thought about, I think there is value in leaving the ogc_fid in place, it makes sense that it is consistent across all loaded tables and always represents an ID added to the table after loading.

I'll try adding our unique ID using ogrinfo in the loading script. This will add the new ID to the shapefile from within the loading script, so it should work for all users.

**Comment by edwardsmarc** [comment]
Simplest solution is to add a srcpoly_id field to each of the 4 source shapefiles. This is done using ogrinfo in the conversion file, before loading to the database.

Since each shapefile can only be accessed in ogr one at a time, I don't see a way to make this ID unique across all 4 files. Instead the ID will start at 1 for each file. This will still create a unique link back to each polygon when combined with the src_filename attribute in the CAS_ID.

**Comment by edwardsmarc** [comment]
Note that when editing shapefiles, only standard SQL or SQLite can be used. When editing the postgresql tables, PostgreSQL can be used.

**Comment by edwardsmarc** [comment]
Problem with space names in the layer name. Layer name is needed in the -sql call. Wrapping names with spaces works when using -sql in the postgres environment, and when using -dialect sqlite. But for editing shapefiles, sqlite does not support dropping columns so we need to use regular sql which does not work with layer names and spaces.

Decision to avoid issues with spaces in table names and just rename the 'Non Forest.shp' source file to 'NonForest.shp'.

Adding #213 to potentially address this in the future.

**Comment by pedrogit** [comment]
Should not be closed until .bat are modified as well.
