### ISSUE TITLE
NB02 translation should copy and edit NB01 translation tables, and use VIEWs based on the NB01 tables.

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#184]
LYR1 - Needs a VIEW based on NB01 LYR with the following mappings. 
* l1estabyr - l1estyr.
* Translation table PRODUCTIVE_FOR row should be removed until we resolve #181. Alter the translation table to use true() and copy(INVALID) for now.
* Translation cas_id should change 'NB01' to 'NB02'

LYR 2 - Needs a VIEW based on NB01 LYR with the following mappings:
* l2cc - l1cc
* l1ht - l1ht
* l2s1 - l1s1
* l2pr1 - l1pr1
* l2s2 - l1s2
* l2pr2 - l1pr2
* l2s3 - l1s3
* l2pr3 - l1pr3
* l2s4 - l1s4
* l2pr4 - l1pr4
* l2s5 - l1s5
* l2pr5 - l1pr5
* l2estabyr - l1estyr
* Translation table PRODUCTIVE_FOR row should be removed until we resolve #181. 
* Translation table LAYER and LAYER_RANK should be set to copy('2').
* Translation cas_id should change 'NB01' to 'NB02'

DST - Needs a VIEW based on NB01 DST1 with the following mappings:
* trt - l1trt
* trtyr - l1trtyr
* Translation cas_id should change 'NB01' to 'NB02'

DST2 should be removed as there is only one treatment column in NB02 (NB01 has one per layer).

CAS - Translation table needs to be edited. 
* 'Forest' should be replaced with 'geonb_forest-foret'.
* Translation cas_id should change 'NB01' to 'NB02'

ECO - same table, no mappings.
* Translation cas_id should change 'NB01' to 'NB02'

GEO - same table, no mappings.
* Translation cas_id should change 'NB01' to 'NB02'

NFL - same table, no mappings.
* Translation cas_id should change 'NB01' to 'NB02'

**Comment by pedrogit** [comment]
Can we not remove PRODUCTIVE_FOR now and return something temporary while we decide on its future in order to not brake the workflow?

**Comment by edwardsmarc** [comment]
Once workflow is updated, delete translation table csv files for NB02.
