### ISSUE TITLE
NB01 and NB02 stand structure translation error

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#186]
# Problem
* NB01 and NB02 translations are failing on rows where l1vs (layer 1 vertical structure) is zero, and l2vs is 1 or 2.
* These cases are not captured in the custom translation rule so TRANSLATION_ERROR is returned.

# Question
* Is it possible for layer 2 (l2vs) to have vertical structure when l1vs = 0?

# If yes...
* The translation rule should be updated to assign a stand structure value in these cases.

# If no...
* A validation rule should be added to catch these cases and return an error code.

**Comment by prvernier** [comment]
The answer to the question is yes. But now, I'm not clear how the l1* and l2* attributes relate to the different vertical structure classes (0, 1, 2, 3) which occur for both l1vs and l2vs. The rules were based on the assumption that there were two layers indicated by l1* and l2*. But does it make sense for each layer to have up to 3 canopy layers?

**Comment by edwardsmarc** [comment]
The data dictionary states:

L1VS - Dominant layer number of canopy layers
L2VS - Secondary layer number of canopy layers

Possible values are:
0 - Not applicable
1 - One canopy layer
2 - Two canopy layers
3 - More than two canopy layers

I agree, it's not clear how the dominant and secondary layers could each have multiple canopy layers. We need some clarification on this.

**Comment by prvernier** [comment]
After staring at the Perl code for a couple hours, I think these are the rules. I used some previously for stand_structure.

if l1vs > 0 & l2vs == 0 | is.na(l2vs) { stand_structure="S" & num_of_layers=1 }
if l1vs > 1 & l2vs > 1 { stand_structure="C" & num_of_layers=2 }
if l1vs > 0 & l2vs > 0 { stand_structure="M" & num_of_layers=2 }
if l2vs == 0 & !is.na(l1s1) & !is.na(l2s1) { stand_structure="M" & num_of_layers=2 }
if l2vs == 0 & !is.na(l1s1) & is.na(l2s1) { stand_structure="S" & num_of_layers=1 }
if l2vs == 0 & !is.na(l1s1) & is.na(l2s1) { stand_structure="S" & num_of_layers=1 }

I will revise the stand_structure, num_of_layers and the code to split the forest data into layer 1 and layer 2 files. Then we can test again.

**Comment by edwardsmarc** [comment]
This still doesn't cover the case where l1vs = 0 and l2vs > 0.

# Remaining questions:

* What is the definition of the 'dominant' and 'secondary' layers in the NB inventory? How can both of these themselves have multiple canopy layers defined in the L1VS and L2VS attributes?

* Is the case where L1VS = 0, and L2VS > 0 a valid entry, or should this be flagged as an error in the source data?

**Comment by prvernier** [comment]
The Perl code seems to generate an error for the case where L1VS = 0 and L2VS > 0. However, this case seems to occur often - see top row of table below. 

> table(x$l1vs, x$l2vs)
   
               0           1          2      3
  0       370 131625    8984      5
  1 375026   96071    6553      0
  2 172003   60455  18079      0
  3     1194       345      271      0

**Comment by prvernier** [comment]
Revised extraction of rules from Perl code (fixing a problem detected in Perl code):

# Cases where L1VS > 0 and L2VS = 0:
if l1vs > 0 & (l2vs==0 | is.na(l2vs)) { stand_structure="S" & num_of_layers=1 }
if l1vs > 1 & l2vs > 1 { stand_structure="C" & num_of_layers=2 }
if l1vs > 0 & l2vs > 0 { stand_structure="M" & num_of_layers=2 }

# Cases where L1VS = 0 and L2VS > 0:
perl code missing for these cases...

# Cases where both L1VS and L2VS are 0 but there are species:
if (l1vs==0 | is.na(l1vs1)) & (l2vs==0 | is.na(l2vs)) & !is.na(l1s1) & !is.na(l2s1) { stand_structure="M" & num_of_layers=2 }
if (l1vs==0 | is.na(l1vs1)) & (l2vs==0 | is.na(l2vs)) & !is.na(l1s1) & is.na(l2s1) { stand_structure="S" & num_of_layers=1 }
if (l1vs==0 | is.na(l1vs1)) & (l2vs==0 | is.na(l2vs)) & !is.na(l1s1) { stand_structure="S" & num_of_layers=1 }
...the last line seems redundant

**Comment by pedrogit** [comment]
I think stand_structure should be derived from l1vs and l2vs and num_of_layers only from l1s1 and l2s2.

stand_structure:

IF l1vs = 0 OR l2vs = 0 THEN stand_structure = 'S'
ELSE IF l1vs = 1 AND l2vs = 1 THEN stand_structure = 'M'
ELSE stand_structure = 'C'

num_of_layers = notNull(l1s1) + notNull(l2s1)

**Comment by edwardsmarc** [comment]
@pedrogit - I'm implementing your suggestion from the table above. Is that table based on real data? From CASFRI 04?

Why is a sum of canopy layers of >4 considered Complex, but 3 is considered Multi-layered?

**Comment by pedrogit** [comment]
If I remember well, it is based on actual data from the inventory.

The decision that 4 = C and 3 = M is kind of arbitrary.

**Comment by edwardsmarc** [comment]
I would argue CASFRI should not assign Complex stand structure unless the source data defines it. If NB have defined 4, 5 or 6 independent layers, then we should assign M based on the following definitions...

L1VS in NB is defined as: Dominant layer number of canopy layers.
L2VS in NB is defined as: Secondary layer number of canopy layers

CASFRI definitions are:

Multilayered - two or more distinct layers of vegetation occur. Each layer is significant, clearly observable and evenly distributed. Each layer is assigned an independent description.

Complex layered stands exhibit a high variation in tree heights. There is no single definitive forested layer as nearly all height classes (and frequently ages) are represented in the stand.

**Comment by edwardsmarc** [comment]
I have added the following rules:

STAND_STRUCTURE: sumIntMapText({l1vs,l2vs}, {1,2,3,4,5,6}, {'S','M','M','M','M','M'})
* This sums the l1vs and l2vs values which are the source count of layers, and returns S or M.

NUM_OF_LAYERS: countOfNotNull({l1s1, l1s2, l1s3, l1s4, l1s5}, {l2s1, l2s2, l2s3, l2s4, l2s5}, {slu}, 3)
* This counts the presence of dominant species, understory species, or nfl info and returns the number of CASFRI layers.

This can result in CASFRI rows with NUM_OF_LAYERS = 1, and STAND_STRUCTURE = M.
The reason is that l1vs or l2vs can be >1 even if only dominant or understory species are provided. 

There is a mismatch between how CASFRI counts layers (using presence of species values) and how CASFRI assigns STAND_STRUCTURE (using sources layer count).

To be consistent with other inventories, I think we should keep the NUM_OF_LAYERS translation as it is. Question is do we change STAND_STRUCTURE to be based on the number of CASFRI layers, or do we keep it as it is to maintain source info and explain the situation in the description column?
