### ISSUE TITLE
Make the reusable translation tables have generic names

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#201]
All translations tables for a given standard should use the base translation table, or a modified version.

Naming conventions:

Option 1 - When a translation table is used for ALL inventories following a standard:
e.g. avi01_cas.csv

Option 2 - When a translation table is used for SOME inventories following a standard:
e.g. avi01_abAA_cas.csv, avi01_abBB_cas.csv
or
e.g. avi01_A_cas.csv, avi01_B_cas.csv
or
e.g. avi01_01_cas.csv, avi01_02_cas.csv

Option 3 - When a translation table is used for onle ONE inventory following a standard (only current scheme):
e.g. ab01_avi01_cas.csv

**Comment by pedrogit** [comment]
Would be a good idea to move the tables into standard or province specific folders at the same time before this folder gets overcrowded. Make sure they still load...

**Comment by edwardsmarc** [comment]
Generic tables needed for AB and BC.
