### ISSUE TITLE
Create helper functions for when reusing translation tables

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#202]
It could be useful to have some function reducing the code necessary to copy translation table for layer 2 and to create VIEWs mapping attributes:

SELECT TT_CreateLayer2TTable('translation', 'nb01_nbi01_dst');
and
SELECT TT_CreateMappingView('NT02', {'trt', 'l1trt', 'trtyr', 'l1trtyr'});

TT_CreateMappingView() would integrate a list of all the useful attribute, map those requested and create the VIEW with a default name.

**Comment by pedrogit** [comment]
So here is what I propose:

There would be a table, equivalent to Pierre V. table, (but transposed so it would be easier to compare attribute names and functions between inventories) named attribute_dependencies.csv in the translation/table folder looking like this:

| inventory_id | attribute_1 | ... | ORIG_STAND_ID | ... | attribute_N |
| NT01 | ... | ... | fc_id_1 | ... | ... |

**Comment by edwardsmarc** [comment]
Are 1 to 3 various options? Or are you proposing a single function that would be able to do 1, 2 and 3?

I like this idea. 

Are the column names just generic names for the source attributes they list? We could simply use 'attribute_1', 'attribute_2', 'attribute_3' etc....

...Or are they CASFRI attributes? In which case, how would we deal with cas_id which takes multiple source values?

**Comment by pedrogit** [comment]
> Are 1 to 3 various options? Or are you proposing a single function that would be able to do 1, 2 and 3?

The function would be able to handle all three cases.

> Are the column names just generic names for the source attributes they list? We could simply use 'attribute_1', 'attribute_2', 'attribute_3' etc....

They would be replaced by other CASFRI attributes. I renamed them in the table. 

> ...Or are they CASFRI attributes? In which case, how would we deal with cas_id which takes multiple source values?

Multiple source attribute would be listed as a comma separated list.

**Comment by edwardsmarc** [comment]
And since some attributes would be duplicated in multiple columns, I guess the function would just ignore duplicates when mapping?

**Comment by pedrogit** [comment]
Closed by https://github.com/edwardsmarc/CASFRI/commit/01624ce49de092157e17e641c2e60b496c72f110
