### ISSUE TITLE
AB translations should have 2 layer tables for LYR and NFL

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#204]
Similar to NT, there are 2 possible slots for data (e.g. sp1 and usp1, nfl and unfl etc.), both could be forest data or nfl data.

Only 274 rows where both are nfl data. 

Adapt workflow scripts to add second layer tables.

**Comment by edwardsmarc** [comment]
Layer 2 tables have layer attributes of 1. Possible problem with TT_CreateMappingView().

**Comment by pedrogit** [comment]
Did you update the translation/test files?

**Comment by edwardsmarc** [comment]
No. I can do that tomorrow.
