### ISSUE TITLE
Merge AB06 and AB16 translation tables into a generic AVI01 translation table

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#206]

**Comment by edwardsmarc** [comment]
Notes:

* ab06 disturbance codes were originally only including 'BU','CC','CL','PL','SC','SN','ST','TH'.
* ab16 has more disturbance codes: 'BU','CC','CL','CU','DT','PL','SC','SL','SN','ST','SU','TH','UK','WF'
* The ab16 codes include all of the ab06 codes and the translations are the same. So we are keeping the longer set of codes to cover both FRIs with the same rule.

**Comment by edwardsmarc** [comment]
We decided to hold off on making a generic AB translation table until we have loaded more AB inventories. It will be easier to deal with all of the AB inventories at the same time.
