### ISSUE TITLE
Remove all single quotes around numbers  in translation tables

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#207]
Following closing of engine #165...

**Comment by edwardsmarc** [comment]
Helper functions fail if decimals used in translation table without single quotes.

The engine thinks the decimal is a comma. For example when I run:

isBetween(val, 0.1, 100)

I get an error saying:

function isBetween(text, text, text, text) does not exist

**Comment by edwardsmarc** [comment]
To recreate, change isBetween(l1ht,'0.1',100) to isBetween(l1ht,0.1,100) in the nb_nbi01_lyr.csv. Then run the NB01.sql devel workflow script.

**Comment by pedrogit** [comment]
Closed by 

https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/commit/3a0ba60b6ef18276c259ac1417246db8b0f1455a
