### ISSUE TITLE
Query source inventories for height range in STRUCTURE_PER attribute

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#208]
How often is the height range specified in the structure_per attribute.

Occurs in AB and possible NWT.

If it occurs, we might want to add STRUCTURE_RANGE or COMPLEX_HEIGHT_RANGE as a new attribute in casfri 5.

**Comment by edwardsmarc** [comment]
AB AVI specifies that when struc = 'C', struc_val is used to indicate the range in median height values within the complex canopy. For example a value of 4 indicates a 4m range in median height values.

This occurs in:
* AB06
  * all 572 complex polygons have a struc_val between 3 - 9.
* AB16
  * only 8 complex polygons
  * instead of a letter for stand structure and a value for the percent/range, ab16 joins them together in the std_struct attribute. e.g. C4 indicates a complex stand with height range 4. Only values are C4 and C5. Also no horizontal structure anywhere in ab16.
* NWT
  * Not clearly defined in the documentation but the complex structure section does describe this usage in the photo labels.
  * 15165 complex polygons with strc_per values ranging from 0 - 12.
  * In NWT the range is in meters but represents range in mean height values rather than medians.

**Comment by edwardsmarc** [comment]
This suggests we should add a new attribute to the casfri 5 schema to record range in height for complex stands.

**Comment by pedrogit** [comment]
Why do HEIGHT_UPPER and HEIGHT_LOWER are not sufficient to describe this range?

**Comment by edwardsmarc** [comment]
The range is a value in meters calculated as the difference between the average or median heights of the upper and lower layers within the complex stand.

To use HEIGHT_UPPER and HEIGHT_LOWER we would have to convert this range into actual height values. It's not clear if this is even possible. The height value assigned to a complex stand is not necessarily at the mid-point of the range. This is clearer if you look at the descriptions of height and complex structure in each of the manuals.

**Comment by prvernier** [comment]
Even though we haven't made a decision yet, I've temporarily added STRUCTURE_RANGE back into the specs with a few notes based on this discussion.

**Comment by edwardsmarc** [comment]
YT manual states there is a height_range attribute used for complex stands, but the attribute is not in the YT02 dataset. Also no stand_structure attribute.
