### ISSUE TITLE
Create conversion .bat and .sh for BC10

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#210]
There are 3 geodatabases that need to be converted, one each for the L1, L2, and D layers. They are located in the D:\FRIs\BC\BC10 folder on the server.

**Comment by prvernier** [comment]
Update: these new datasets are of the same vintage as BC09 i.e., they are both current to 2018. So instead of calling it BC10 we should keep with the BC09 name and replace the files in that folder with the newly acquired datasets.

**Comment by pedrogit** [comment]
And we get rid of all BC09 translation tables?

**Comment by edwardsmarc** [comment]
> And we get rid of all BC09 translation tables?

This will be done as part of #201

**Comment by edwardsmarc** [comment]
Update: we decided to keep BC09 and archive it. It will not be included in CASFRI 5. The new dataset will be named BC10.

**Comment by edwardsmarc** [comment]
This dataset has 3 geodatabase tables: L1, L2, D.

We want to load these into a single table in the database, named BC10.

All three source tables have the same column names, and the same set of polygons. i.e. the attributes are repeated for each polygon, meaning is we loaded them as they are we would end up with a one-to-many relationship between polygon and attribute. 3 attributes per polygon.

This is not what we want for translation. We need a flat source table as input to the engine.

I see two options:

Option 1 - Load each source table as a single table in the database: BC10a, BC10b, BC10c. Run each table through the translation engine. This would give the desired output of a one-to-many relationship in the CASFRI. i.e. one row per layer for each polygon. This option would not work if any translations require values from multiple source tables. e.g. LAYER and NUM_OF_LAYERS might be tricky.

Option 2 - Alter attribute names during loading, and merge attributes into one flat table named BC10. This could be done with some SQL code in the loading script. We would need to manually query all the attributes that would be needed in the translations. At least from the L2 and D tables. These attributes would be renamed to have L2_ and D_ prefixes then appended to the L1 table in the db.

**Comment by edwardsmarc** [comment]
We decided on the following procedure using option 2 above:

1. Load the three gdb into postgresql tables named bc10_layer_1, bc10_layer_2, bc10_layer_d
2. During loading use -sql command in ogr2ogr to change column names. Prefix all L2 and D names with L2_ and D_.
3. Use ogrinfo and -sql to join the three tables into a final table BC10. Delete bc10_layer_1, bc10_layer_2, bc10_layer_d.
