### ISSUE TITLE
Many rows in NT02 produces a NULL cas_id

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#215]
What should be done in this case?

**Comment by edwardsmarc** [comment]
It looks like many rows to me. 421 source rows have null values for fc_id which is used in cas_id.

I think in these cases we should revisit the cas_id and probably create a new column with unique ids for the source polygons. We could set those null values to zero so the function would run, but then we can't link back to the source polygons.

**Comment by pedrogit** [comment]
Right. I found only one because I was testing with the translate/test random subset.

**Comment by pedrogit** [comment]
Should we just not load the fc_id =NULL ones?

**Comment by edwardsmarc** [comment]
Actually, none of them have any values. All Null for every field. So your right, we should probably drop them.

**Comment by pedrogit** [comment]
ok I'll take care of it.
