### ISSUE TITLE
NUM_OF_LAYERS: Derived vs translated.

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#218]
Currently for NB we have a translation rule to calculate the number of layers. This is a custom casfri specific helper function that looks at the source data and assigns NUM_OF_LAYERS based on other source attributes (stand structure values for source layer 1 and 2). Using this approach we may need to write a new helper function for each standard.

This seems like an easy attribute to calculate after translation for the entire CASFRI. i.e. a CASFRI 'derived' attribute whose value is calculated based on the CASFRI table rather than the source table.

I propose we leave all NUM_OF_LAYERS values blank and assign values in the workflow file using a simple query that counts the number of rows associated with each polygon. This value would have to be calculated before we flattened any tables.

**Comment by MelinaHoule** [comment]
This makes sense. The column NUM_OF_LAYERS aims to inform the user about level of information given for a polygon in the CASFRI db. It should be CASFRI related instead of copied from raw data.

**Comment by pedrogit** [comment]
I don't like the idea of trying to compute it in the worflow. It should remain a translation rule but one derived from previously translated attributes or from rules specific to each inventory. We might be able to write a more generic function taking inventory_id and a certain number of attribute value and being able to determine the number of layer from those values.

**Comment by edwardsmarc** [comment]
Yes it is possible to write specific translation rules to calculate the number of layers. But it'll be different for different standards so it's a lot of work for something that could easily be calculated after translation with one line of code.

What if we pass the CASFRI table through the engine after everything has been translated, and use a separate translation table to generate all the 'derived' attributes? We will have a number of these. Like PRODUCTIVE_FOR. Too slow?

**Comment by pedrogit** [comment]
Is NUM_OF_LAYERS the number of LYR layers, the number of NFL layers or the number of DST layers?

**Comment by edwardsmarc** [comment]
All layers in polygon:
> Identifies the number of vegetation or non vegetation layers assigned to a particular polygon. A maximum of 9 layers can be identified.

**Comment by edwardsmarc** [comment]
Write TT_NumberOfNotNull().

Inputs: up to 5 arguments. Each argument is a list of attributes. If any member of the list is notNull, the argument counts as notNull. Function returns an integer between 0 - 5 with the number of notNull arguments. Each argument should check if a layer exists.

Get rid of TT_nbi01_num_of_layers_translation()?

**Comment by edwardsmarc** [comment]
Next step is to update translation tables to use TT_NumberOfNotNull(). Arguments should be the required columns indicating a layer is present, for all possible layers in an FRI.

**Comment by edwardsmarc** [comment]
Applied for ab06. Need to add for all other inventories.

**Comment by edwardsmarc** [comment]
In some cases when making views, we will need to map two sets of values to one column name. For example when making a view for LYR2, the usp1 column needs to be mapped to sp1. But we also need both the original usp1 and sp1 columns in order to calculate num_of_layers and layers.

Solution is to set up some specific lyr attributes for all source attributes used in numberOfNotNull(). In the dependency table for the generic row (every FRI will need a generic row for this to work), replace the attribute names in NUM_NOT_NULL with lyr_att_1, lyr_att_2 etc. Use these names in the translation table also. Each layer row will use the actual source attribute names.
