### ISSUE TITLE
Workflow should refer to generic rows in dependencies table

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#220]
ToDo when #219 is complete.

Currently no way to know which inventory attribute names a translation table is based on. This is needed when making VIEWs.

Solution: Add a 'generic' row to the dependencies table for every standard where VIEWs will be needed. All VIEWs will be mapped from this row. The row lists the attributes used in the generic translation table, it may or may not be exactly the same as one of the inventories. For example, the generic translation tables for NB and NT are just renamed versions of the NB01 and NT01 tables.

**Comment by pedrogit** [comment]
#219 was closed.
