### ISSUE TITLE
Write CAS50 validation tables

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#221]
One for each of HDR, CAS, DST, LYR, NFL, ECO and GEO.

**Comment by kdarndt** [comment]
See also comments on using Lookup tables for validation in issue #211 .

**Comment by pedrogit** [comment]
This was replaced by #300. A set of non blocking constraints are added to the database after complete translation. I don't think there is any advantages to double check everything with validation tables. Closing.
