### ISSUE TITLE
Make ab_photoyear geom valid in 02_produceCASFRI/02_cas.sql

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#236]
In 02_produceCASFRI/02_cas.sql, section where make valid geom on **ab_photoyear** is missing. The geometry validation occurs in 01_devTranslationTables/AB06.sql, but we shouldn't assumed that script is run before 02_procudeCASFRI/02_cas.sql.

**Comment by edwardsmarc** [comment]
Other validations to add:

species lookup tables
