### ISSUE TITLE
Make CASFRI specification editable

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#238]
In the CASFRI specification, section 1.2 Error and Missing Value Codes, hyperlink "Click here to view specific error codes for individual attritubes" is not working. It leads to Page not found. 

Also there is a typo.  attritubes should be attributes.

I wanted to edit the typo but I realized the documentation was generated by Rmarkdown. Is that what we want. Because right now, nobody can't edit the doc except Pierre Vernier. Is there a better way to produce doc in git? 

Finally, something that was never implemented in Cosco documentation was possible ERROR CODE per attributes, so the user would know the entire range of value possible for each field. 

What do you think?

**Comment by prvernier** [comment]
I fixed the link earlier this week but hadn't pushed the changes. Thanks for pointing out the typo. Both changes have now been pushed and the readme modified.

The cas_specifications.md document is a markdown document (not Rmarkdown) and can be edited directly in Github.
