### ISSUE TITLE
Add notEmpty() to validation rules for DIST_TYPE_ 1,2,3 in AB06 dst translation table 

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#245]
In AB06, when blank are found in MOD1, MOD2 and MOD3, the translation table returns NOT_IN_SET. Should be EMPTY_STRING

**Comment by prvernier** [comment]
@edwardsmarc Does this need to be fixed in the helper functions. It might just be a question of the order things are done. In my pseudo R code I had:
x = mutate(x, dist_type_1=case_when(
    is.na(mod1) ~ "NULL_VALUE",
    str_trim(mod1)=="" ~ "EMPTY_STRING",
    !mod1 %in% friList ~ "NOT_IN_SET",
    TRUE ~ mapvalues(mod1, friList, casList)))

This might need to be changed in SQL so that a null value or empty string is not returned as "NOT_IN_SET".

**Comment by edwardsmarc** [comment]
I think @MelinaHoule is correct. The MatchList() is failing because the empty string is not trapped earlier. MatchList fails and returns NOT_IN_SET. We should add a notEmpty(mod1) before the matchList() call.

**Comment by MelinaHoule** [comment]
The function need to be run on PostgreSQL 11 to recreate unit test with the bug fix.
