### ISSUE TITLE
Adjust translation/test files to allow unit test to run in PostgreSQL 11 and 12 

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#246]
The random function in PostgreSQL 11 do not behave the same way in PostgreSQL 12. So the testTranslations.sql do not translate the same sample leading to not being able to run a unit test on when changes are made. 

All test tables will need to take into account the version of PostgreSQL used. 

My solution is to add a variable pgversion in the config.bat and config. sh
change the load and dump _test_tables to take into account the version of PostgreSQL using that new variables. 

And then the user will need to load the proper version of the test table according to the version of PostgreSQL.

**Comment by MelinaHoule** [comment]
Add pgversion in config.bat and config.sh. 

Concatenate pgversion to data directory in load_test_tables and dump_test_tables to make sure the sample use in the unit test is consistent within version and allo TT_Compare to work. 

See commit: a8bc1dbd05a2a583781fe302d58e33773b0ecccf

**Comment by pedrogit** [comment]
This is du to a change to the random() function behavior in PostgreSQL 12: https://www.postgresql.org/docs/release/12.0/
