### ISSUE TITLE
TT_CreateMappingView generates error for BC10 inventory

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#251]
The following error message is displayed when "SELECT TT_CreateMappingView('rawfri', 'bc10', 2, 'bc', 1, 200, 'lyr');" is run from BC10.sql test file (line 127).

ERROR:  function tt_arraydistinct(text[]) is not unique
LINE 1: SELECT '  WHERE ' || array_to_string(TT_ArrayDistinct(whereE...
                                             ^
HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
QUERY:  SELECT '  WHERE ' || array_to_string(TT_ArrayDistinct(whereExpArr), ' OR ' || chr(10) || '        ')
CONTEXT:  PL/pgSQL function tt_createmappingview(text,text,integer,text,integer,integer,text,text) line 184 at assignment
SQL state: 42725

**Comment by pedrogit** [comment]
Fixed by DROPping the one parameter variant of TT_ArrayDistinct() in PierreV database.
