### ISSUE TITLE
Add generic AB row to attribute dependencies table

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#252]
Needed for LAYER translation to work properly. See comment in #218

**Comment by edwardsmarc** [comment]
Multiple generic AB tables needed because translation rules for AB06 and AB16 structure_per are different. Created 'AB_a' and 'AB_b' generic tables.

**Comment by pedrogit** [comment]
AB06_GEN and AB16_GEN? Fixing #206 would fix this as well...

**Comment by edwardsmarc** [comment]
Agreed, I was going to implement #206 but realised the STRUCTURE_PER rules are different. So I made two generic tables. I didn't label them with ab06_gen because they will eventually be used for other inventories as well.

**Comment by edwardsmarc** [comment]
Updates to tt_map functions will allow a generic function to be used for structure_per.

TT_MapInt will allow multiple input values, if multiple provided they are concatenated before doing the mapping.

This will allow a generic function to concatenate the ab06 struc and struc_val columns then do the mapping. ab16 std_struct is already concatenated so the second val will be mapped to null.

Function will look something like this:

T_MapInt({val1, val2}, {'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'H7', 'H8', 'H9', 'C3', 'C4', 'C6', 'C7', 'C8', 'C9', 'S0', 'M0', 'M', 'MO', '0', ' 0'}, {1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}).

**IMPORTANT: all complex stands should have stucture_per values of 0. In C stands the value represents average height.**
