### ISSUE TITLE
LAYER and LAYER_RANK

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#253]
BC08 has a layer_id field that represents the layer number assigned within the VRI. It also has a rank for each layer. Layer 1 is not always rank 1. Since our BC08 dataset is just the rank 1 info, polygons can have layer_id values of 1 - 4.

For the casfri LAYER attribute, should we copy the VRI layer_id value? Or calculate our own values based on the number of layers in the CASFRI (for BC08 this would always be 1 or 2 since we only have a single LYR and a single NFL table)?

**Comment by MelinaHoule** [comment]
I think we should be consistent within our own database. We do not consider layer_id from the raw and we attribute layer_id based on the number of layers in the CASFRI.

**Comment by edwardsmarc** [comment]
OK I agree. Which leads to the next question of LAYER_RANK.

How would this ever be different from LAYER in the CASFRI?

**Comment by pedrogit** [comment]
I think LAYER must be computed by us but LAYER_RANK must come from the data. Then you cross your finger that everything fits together...

I guess the true question is when would LAYER from us be different from LAYER from the data. We should be able to explain any difference and once we realize there is no difference or that we understand them, then we can use LAYER_RANK from the data and maybe sometimes, modify it.

**Comment by edwardsmarc** [comment]
@pedrogit 
An example is BC08. The data we get is Rank 1. But the BC assigned layer value (layer_id) is not always 1. So we have a single layer for each polygon, but sometimes we have layer 1, sometimes 2, 3 or 4. In CASFRI all these rows would be assigned LAYER = 1.

I guess in this situation we could copy the original layer_id value to be the LAYER_RANK in CASFRI.

**Comment by prvernier** [comment]
In BC08, the permitted values are 1, 2, 3, S, V whereas the actual values in the database are 0, 1, 2, 3, 4, S. I agree with @edwardsmarc that these should all be assigned LAYER = 1 but I think LAYER_RANK should be assigned 1 as well and not the layer_id value since LAYER_RANK in CASFRI represents "layer importance for forest management planning, operational, or silvicultural purposes".

**Comment by prvernier** [comment]
For LAYER, these should be assigned a 1 except for values 0 and 4 which are not permitted. These would take an error code.

**Comment by prvernier** [comment]
For LAYER_RANK, where layer_id are 0 or 4 (not permitted layer codes), these should still be assigned a 1, at least for BC08, since this is strictly rank 1 data.

**Comment by edwardsmarc** [comment]
We agreed on the following temporary solution:

* LAYER will be 'computed' using the method we have developed, such that the tallest forest layer will be layer 1, followed by layer 2 etc. Followed by any NFL layers. If no forest data, NFL will start at layer 1.
* LAYER_RANK will be copied from the source data attribute if one exists. If this attribute exists and has a value of null, we will report a null value error code in the CASFRI. If no attribute exists for rank in the source data will report a NOT_APPLICABLE error code.
* LAYER is therefore a CASFRI specific attribute that we compute ourselves, whereas LAYER_RANK is a copied attribute from the source data.

If we find this solution does not work with other inventories we will revisit this issue.

We also note that the only way to preserve the original source inventory layer id is to add a new column to the CASFRI tables. This could be done when we switch to the new schema.

**Comment by MelinaHoule** [comment]
According to that line : "LAYER will be 'computed' using the method we have developed, such that the tallest forest layer will be layer 1", layer is linked to heigth.

What if a province (such as Quebec) defines layer order based on basal area instead of the heigth? In QC03, when a polygon is multilayered, only the heigth of the dominant layer (highest basal area) is given. We can't recover the heigth of layer =2. 

Do we change the definition of layer or make a note somewhere?

**Comment by edwardsmarc** [comment]
I should make a correction. We don't consider height. All the inventories we have translated so far that have multiple layers, describe an overstory layer and an understory layer. We assign the overstory to layer 1 and the understory to layer 2.

We should write a definition for LAYER in the specs that captures all the cases.

**Comment by pedrogit** [comment]
LAYER is determined based on the presence/absence of significant values for key attributes describing different forest layers. Not necessarily "height".

**Comment by sgautam-nrcan** [comment]
Stand structure to be single or multiple is derived based on the number of canopy layers (it does not account non-forest layer). If only one canopy layer it would be the "Single" layer, but still it could have non-forest layers e.g., shrub and herb layer. If more than one canopy layers then it is "Multilayered". In the case of BC, the BC10 data it would be possible to evaluate single or multilayer. For example, if a polygon has Layer 1 data but no layer 2 data for that particular polygon, then it confirms that it is a single layer.  If there is data for both Layer 1 and Layer 2 data for a polygon then it confirms multilayered.
In the case of BC08, it is a bit different and not possible to draw such inferences looking at data itself (which we know is an incomplete data set). However, the corresponding data dictionary indicates that "One layer in a multi-layered stand is assigned a rank code indicating the relative importance of that layer. The layer assigned Rank 1 in multi-layer stands is the most important layer". It somehow indicates that polygons of this data package (i.e., Rank 1 - data package prepared for the specific objectives like stand growth modeling) have multilayered.  Regarding layer rank, it would be good to keep values from the original source. For example, let's say in Rank 1 data a polygon was assigned a "layer_id" is 3 then keep this in the CASFRI translated Layer_rank as 3 for that polygon (even if the data has only one layer).
In this discussion, I noticed that layer order is not universal. For example, For BC Layer 1 is the top canopy layer, but not in the case of QC03, where it is the dominant height of the highest basal area (based on the discussion above). Let's capture such differences in our documentation and make it explicit.
The number of layer than would be the total of canopy layer/s and NFL layers.

**Comment by edwardsmarc** [comment]
@sgautam-nrcan 

## Definitions
So are we agreed on the following definitions (but see bc08 section below for caveats):

* LAYER will be 'computed' using the method we have developed, such that the tallest forest layer will be layer 1, followed by layer 2 etc. Followed by any NFL layers. If no forest data, NFL will start at layer 1. Inventories that differ from this definition in their assignment of layers (e.g. QC) will be explained in the casfri specs.
* LAYER_RANK will be copied from the source data attribute if one exists. If this attribute exists and has a value of null, we will report a null value error code in the CASFRI. If no attribute exists for rank in the source data will report a NOT_APPLICABLE error code.
* NUM_OF_LAYERS is the total count of all CASFRI LYR and NFL layers.
* STAND_STRUCTURE is based on the count of LYR rows (i.e. count of canopy layers). Except for the following cases:
  * Horizontal is copied from the source
  * Complex is copied from the source
  * If we know we have missing data, we can change the rule. e.g. in BC08 we would always assign M based on your comment above.

## BC10 Examples
To confirm we are on the same page for BC10, here are some examples

### Example 1
* In the case of a source polygon from BC10, where we have the complete dataset, where species are assigned for both layer 1 and layer 2 in the source polygon and there is also one NFL layer.
* There would be two CASFRI LYR rows labelled LAYER = 1 and LAYER = 2.
* NUM_OF_LAYERS would be 3.
* STAND_STRUCUTRE would be M
* LAYER_RANK would copy the rank values (I believe these are called for_cover_rank_cd in BC10) for each canopy layer.

### Example 2
* In the case of a second polygon from BC10, where species are assigned for only the layer 1 attributes in the source polygon, and both the layer 2 and nfl attributes are null.
* There would be one CASFRI LYR row labelled LAYER = 1.
* NUM_OF_LAYERS would be 1.
* STAND_STRUCUTRE would be S
* LAYER_RANK would copy the for_cover_rank_cd value from the source data.

## BC08
I need some clarification for BC08. You comment above suggested we would copy layer_id to LAYER_RANK. In our call I had understood that layer_id would become the LAYER value. In the case of a BC08 polygon with a layer_id value of 3, I see two options:

### Option 1 - what I thought we were going to do
* LAYER = 3
* LAYER_RANK = 1
* STAND_STRUCTURE = M
* NUM_OF_LAYERS = 1
* We document that LAYER is copied from the source because we know our dataset is incomplete. We also document that stand structure is always M based on the VRI documentation.

### Option 2 - based on your comment above
* LAYER = 1
* LAYER_RANK = 3
* STAND_STRUCTURE = M
* NUM_OF_LAYERS = 1
* This would follow our current method for assigning LAYER. LAYER_RANK would be copied from the source, but my understanding was that layer_id is not the rank value in this case. I would assume rank is always 1 in BC08.

**Comment by sgautam-nrcan** [comment]
Thank you, Marc. You captured well. Regarding BC08, Option 1 is good (except in the number of layers). In my comment, I should have said CASFRI LAYER is LAYER_ID (source inventory), but now you make it correct.
We know that Rank 1 data is not complete, so providing the number of layers based on this data set alone may mislead users. The challenge still here is that how we articulate this into CASFRI data dictionary and users know that number of layers only based on the corresponding data sets. Even in this Rank 1 data, there could be 1 or 2 layers (1 forest and 1 non-forest). In each row, there is information about non-forest layer (e.g., shrub_height, shrub_crown_closure). Hence, number of layers could be 1 or 2, depending upon the shrub layer presence.

**Comment by edwardsmarc** [comment]
Great, thanks for you help on this, I'll make these changes to the translation rules and update the specs with the agreed documentation.

**Comment by edwardsmarc** [comment]
In attempting to close this issue I've encountered further questions for the BC08 case.

The decision was made above, that for BC08 we would copy the layer_id value from the source data and use that as the CASFRI LAYER value in the LYR table. That works fine but raises the following questions:

**STAND_STRUCTURE**
* In the case that layer_id > 1, we can be sure that STAND_STRUCTURE is M (multi-layered)
* What about when layer_id = 1? Based on Sishr's comment above, the manual suggests that the Rank 1 data is always multi-layered so we can always report M for BC08. Are we happy with this decision?

**NFL LAYER** 
* Without knowing what the maximum layer_id value is for a given polygon, we can't correctly assign NFL LAYER. 
* The best we can do is start the NFL LAYER assignment at layer_id + 1. We can note in the documentation that layer_id + 1 could actually be the layer value for a forest layer, but we don't know without the full dataset.
* Alternatively we could always start NFL LAYER assignment at 5, since the maximum observed layer_id in BC08 is 4.

**Comment by sgautam-nrcan** [comment]
@edwardsmarc 
I agree with you that it raises questions to assign NFL LAYER assignment at layer id. It would be hard to overcome this issue as such. However, I think the following could be options that we can try.

- If there is a chance to get additional information (shapefile) from BC providing a total number of layers in each polygon then it can resolve this issue (I'm not sure if BC has this one). I've inquired about this but haven't heard back yet.

- Or simply we could assign NFL layer_ID as 10 (i.e., the maximum number of tree layers -9 that can be created, though it's not practical in photo interpretation and not found in the Rank 1 data) and explain why we apply 10 in our documentation

**Comment by kdarndt** [comment]
I would be tempted to throw out BC08 and use the L1, L2, and D files that BC now publishes for the same year (2016 I believe?):  https://catalogue.data.gov.bc.ca/dataset/vri-historical-vegetation-resource-inventory-2002-2018-
Obviously something you're not going to do here, but maybe we will end up re-using the BC10 translation files and load the 2016 data that way.

For your questions, we could consider BC08 to be an limited dataset and thus be satisfied with:

- STAND_STRUCTURE = UNKNOWN for layer_id=1
- NFL LAYER = UNKNOWN

This reduces its usefulness in CASFRI, but we are dealing with a limited dataset...  I'll let Sishir weigh in on this before you close it though.

**Comment by sgautam-nrcan** [comment]
Yes, I agree with Kristian considering BC08 as a limited data set and apply what Kristian is suggesting. As CASFRI doesn't aim to fix the issues associated with raw data (in my understanding) I think this would be an option to deal with limited data.

**Comment by edwardsmarc** [comment]
BC08 was downloaded in 2018. I agree just using the now available L1, L2, D files that are now available would save us a lot of trouble trying to make the translations work for a limited dataset. I'll raise this with SC in our meeting tomorrow.

**Comment by edwardsmarc** [comment]
We agree that we will replace the BC08 rank 1 data with the newly available complete dataset.

We will review the current translation table, any rules that only apply to the rank 1 dataset should be archived in case other rank 1 historical datasets are added in future.

**Comment by edwardsmarc** [comment]
Closing and moving the BC08 work to #399
