### ISSUE TITLE
Should STRUCURE_PER be 0 or 100?

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#259]
In single layered, multi layered and complex stands, source inventories would report structure percent to be 0 (Only in Horizontal stands would they report a value greater than zero to indicate the % of the polygon covered).

We have previously discussed using 100 to indicate 100% of the polygon is covered.

Which should we use for these cases in cas05, 0 or 100?

**Comment by prvernier** [comment]
Currently in the specs document, for structure_per, I have value=100 when stand_structure = "S", "M", or "C". But that can change if we decide to go with 0.

For structure range, I have value=0 when stand_structure = "S", "M", or "H". Again, that can change.

**Comment by pedrogit** [comment]
I would go with 100 for STRUCTURE_PER (we all agreed that was more meaningful) and NOT_APPLICABLE for STRUCTURE_RANGE when STAND_STRUCTURE = "S", "M", or "H".

**Comment by prvernier** [comment]
Agreed, NOT_APPLICABLE, or rather -8887, seems appropriate for STRUCTURE_RANGE when STAND_STRUCTURE is not complex.
