### ISSUE TITLE
What is the purpose of DST LAYER attribute

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#272]
Can disturbances be attributed to LAYERs?

If not, what is the purpose of this attribute?

For now, I am setting this to return the NOT_APPLICABLE error code (-8887).

**Comment by pedrogit** [comment]
Yes. Sometimes only the understory will burn. Already had this discussion with Steve.

**Comment by edwardsmarc** [comment]
We don't have source data so far where this would be used (except maybe nb01):
* ab06 has understory modifier attribute but it never has a value.
* nt only records one disturbance.
* bc records multiple disturbances but not by layer.
* nb01 records disturbance by layer but the values don't make sense and don't match expected values from the manual.
* nb02 only records one disturbance.

What value do we report to indicate the disturbance has no specified LAYER?

**Comment by MelinaHoule** [comment]
In the past, we assumed  when it was applied to the entire polygon, it was layer 1. But again, that was to make sure that when people would query layer = 1 in CASFRI, they would catch all LYR layer 1 + all disturbances.

**Comment by SteveCumming** [comment]
I have been thinking about this, and pending any updates from John, it seems that few if any existing inventories mandate layer-specific disturbances, and fewer, if any, record them consistently. That being the case, I think we should leave interpretation to the user, and remove this attribute from the .dst records for CASFRI 5.0

**Comment by prvernier** [comment]
So, is the conclusion to drop attribute this from the schema/tables (for now) or keep it and code it as -8887 (NOT APPLICABLE) for all inventories?

**Comment by SteveCumming** [comment]
I would say drop it from the schema/tables for now...just for the .dst tables, that is.

**Comment by coscojohn** [comment]
For inventory purposes, I think the value of the disturbance code (which may be a disturbance or stand condition) is that some kind of disturbance, or multiple disturbances for some inventories, happened to that polygon that influenced or is influencing how that polygon is being described and why it is different than its neighbor. It seems reasonable to attach the disturbance to the layer it has been affected but I cannot think of any specific inventory rule in any jurisdiction that says this must be done.
I think what Melina said above is also a reason why it is usually attached to the top layer - it is still applicable as polygon specific and that way it would not be missed.
I think the question above that is it layer-specific and what is the purpose if not are two different things - I think attaching it to a layer is not so important but the purpose adds value to the inventory. First, disturbance data is useful (e.g. the reason for the polygon in the first place, vegetation composition or lack of it, standing dead trees, or what will happen next knowing the disturbance agent), and you do not have to go somewhere else to find it.
As an inventory guy, I am biased but keeping the attribute would add value. For CASFRI, you could do a search of all layers for a disturbance on the input inventory then assign it or them to layer 1. If the data is not included in an inventory you could have a code as stated above to indicate that it is not applicable.

**Comment by coscojohn** [comment]
Alberta is an interesting example. They provide space to add disturbance or stand condition data by layer but we only record this data in layer 1 (unwritten rule). I am sure the reason is so the data is not missed in a query.

**Comment by coscojohn** [comment]
BC, now only allows one disturbance code, previous inventories allowed two events. They can have multiple layers but disturbance has always been polygon specific. The Yukon is unique in that it identifies up to two layers and disturbance can be described in top or bottom or both. This was to accommodate the huge spruce bark beetle infestation that occurred there in the Haines Junction area. NWT allows up to two layers and three disturbance or condition events per polygon. There is no written rule as to where to code the disturbance but it is always recorded in layer 1 although they also have a non-forested burn code for recent burns which is layer specific.

**Comment by coscojohn** [comment]
Saskatchewan can record three tree layers, a shrub, herb, and a non-forest layer per polygon. Disturbance rules are similar to NWT with up to three events per polygon. Again, there is no rule as to how they are to be recorded by layer though they state that they occur as separate spatial layers although I am not quite sure what that means except that they record their data as separate Access tables. They typically are recorded as polygon specific.

**Comment by coscojohn** [comment]
Manitoba can record up to 5 layers per polygon of which two are tree layers and one can be a veteran layer (1-5% crown closure). Disturbance can be either a stand condition or a stand treatment, a maximum of two stand condition and one treatment are allowed per polygon. Stand condition or treatment is polygon specific.

**Comment by coscojohn** [comment]
That completes the western Canada recap.

**Comment by SteveCumming** [comment]
OK: based in John's recent info, I guess we should retain the layer attribute for .dst records. It would be integer numeric, 1,...,n where n is the number of vertical layers., and it would usually be either missing or "not specified in the standard"

**Comment by edwardsmarc** [comment]
I have assigned all disturbance tables to LAYER = 1 so they can be queried as discussed above.

Note that in cases where disturbances are attributed to specific layers, we will need to generate multiple disturbance tables, one for each layer. We will need to plan this carefully in Yukon where disturbances could be layer 1, 2, or both.

**Comment by coscojohn** [comment]
Hi, the Yukon and Alberta allow disturbance in the second layer. Maybe to
keep CASFRI simple you simply put any disturbance (from any layer) into
layer 1. It is not so important to know which layer is disturbed rather
than knowing that there is a disturbance occurring in a particular polygon.
Knowing what the type of disturbance usually indicates what layer it is
affecting anyways.

John

**Comment by edwardsmarc** [comment]
Closing.

All disturbances have been assigned to layer 1. Except NB01 which has disturbances assigned to layer 1 and layer 2. We cannot assign these both to layer 1 due to #305 so the understory disturbance has been assigned to layer 2.

AB06 and AB16 have attributes for understory disturbance but no values.

YT02 does not appear to have an understory or layer 2 disturbance attribute.

**Comment by edwardsmarc** [comment]
This issue came up in a recent discussion with @sgautam-nrcan and @kdarndt.

Their preference was to copy the source layer attribute if one exists, otherwise assign UNKNOWN.

However, based on @coscojohn 's comments above, it seems many inventories arbitrarily assign disturbance to layer 1, so copying the value might be misleading.

I'll let @sgautam-nrcan and @kdarndt comment here after reading the thread.

**Comment by sgautam-nrcan** [comment]
The disturbance attributes are very important. If original data explains which layer is influenced (e.g., in the case of BC it is provided in Layer 1 and Layer 2), it would be nice to keep the corresponding layer. However, if the layer is not explained in the source inventory and assigning to Layer 1 would be little confusing. Mixing of known (i.e., a source telling disturbance layer is 1) and unknown (but assumed to be layer 1) layer values may introduce biases. For example, the disturbance could have been to ground cover or shrub, but assigning layer 1 tells that the disturbance is on the top canopy layer. Hence, my thought would be if source inventory tells the disturbed layer take that layer value, and if not then we could assign UNKNOWN layer. At least then we will leave interpretation part to users for missing layer.

**Comment by kdarndt** [comment]
I agree with Sishir.  In general, we should avoid introducing information simply to make it easier to query.  LAYER should only be populated if the source dataset specifies it (otherwise it is UNKNOWN). 

As to whether the source datasets are populating that value with arbitrary values, I would say that we could still specify "UNKNOWN" only if their data dictionary clearly and explicitly specifies that the value is arbitrary  Otherwise we would have to take it at face value (I don't think we should read between the lines and assume its arbitrary unless specified & documented).

**Comment by pedrogit** [comment]
I don't if that happens, but what if the inventory describes only one layer and so that "layer" is not a concept that is part of their specification? They would have no reason to think that some people would think the disturbances they describe could apply to any other layer than 1.

**Comment by sgautam-nrcan** [comment]
Yes, if there is only one layer in a stand then definitely the disturbance should be in that layer. If forest inventory data is complete and explicitly tells us there is only one layer, it makes sense. How do we validate that the stand has only one layer and data is complete? For example, in the case of BC08, if we assign disturbance to layer 1 would be misleading because the data is not complete (in that data set only an important layer is provided).
