### ISSUE TITLE
QC03CAS - STAND STRUCTURE and NUM_OF_LAYERS need helper function

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#273]
STAND_STRUCTURE and NUM_OF_LAYERS  in QC03 is derived from cl_age. Rules are as follow:

STAND_STRUCTURE :
if cl_age IN   (10,30,50,70,90,120,JIN,VIN) STAND_STRUCTURE = S, if cl_age IN (JIR'VIR)   STAND_STRUCTURE = C, if length(cl_age)>3, STAND_STRUCTURE = M

NUM_OF_LAYERS:
if STAND_STRUCTURE =   S, NUM_OF_LAYERS = 1, if STAND_STRUCTURE = M, NUM_OF_LAYERS = 2, if   STAND_STRUCTURE = C, NUM_OF_LAYERS = unknown

See qc03_cas.csv
--

--

**Comment by pedrogit** [comment]
Would be better to create two issues.

What does CL_AGE look like when length(CL_AGE)>3 ?

**Comment by edwardsmarc** [comment]
**STAND_STRUCTURE**
Stand_structure translation needs two rules, one to deal with S and C (i.e. mapText()) and one to deal with M.

Option 1
* use mapText() for all possible values. This works well for S and C but for M we would end up with a function containing 73 separate strings to map. That's a lot. We could also copy these to a lookup table and use lookupText(). **lookupText() is probably my preferred option here**.

Option 2
* Write a custom casfri-only helper function for this translation. It would contain an if statement to separate values based on length <= 3. Then run mapText on the values with length <= 3.

Option 3
* Add a generic helper function that runs map text but only if length is less than (or greater than) a provided value. Else returns another value.
* mapTextIfLength(in_string_list, out_string_list, logic, length, else_return)
* e.g. mapTextIfLength({10,30,50,70,90,120,JIN,VIN,JIR,VIR}, {S,S,S,S,S,S,S,S,C,C}, 'lessthan', 4, M)

**NUM_OF_LAYERS**
* We prefer to calculate NUM_OF_LAYERS and LAYER using the countOfNotNull() function. But this only works if each layer is based on values from independent attributes. QC seems to concatenate multiple pieces of info into single columns. @MelinaHoule - we should open a new issue for NUM_OF_LAYERS and LAYER, once you figure out how forest layers and nfl layers are structured in QC03 you can add that info to the issue and we can discuss whether it will fit into our current model.

**Comment by pedrogit** [comment]
You could add a "else" option to mapText() so that if it's not any of the listed cases, it return the "else" string. But that would not work for the validation sister function. You could use lookup for the validation.

**Comment by edwardsmarc** [comment]
If we need a lookup table for validation, we may as well also use it for translation. Then only one thing to maintain.

**Comment by edwardsmarc** [comment]
@MelinaHoule 

The decision here is to use the existing TT_lookupText() function and create a lookup table mapping all possible cl_age values to the appropriate STAND_STRUCTURE value. You can see an example of how this works in the SPECIES translations used in all inventories.

And you can see all possible cl_age values using this query:

`SELECT cl_age FROM rawfri.qc03 GROUP BY cl_age`

**Comment by MelinaHoule** [comment]
I created a lookup table for QC03_standstructure.csv  that will allow the translation to derive stand_structure from cl_age column.  NUM_OF_LAYERS will be derived from stand_structure. In Quebec, if stand_structure = M, NUM_OF_LAYERS always = 2 and if stand_structure = C, NUM_OF_LAYERS is unknown.
