### ISSUE TITLE
Translation table for SK01

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#275]
Starting with SK01 because it has the most coverage.

**Comment by edwardsmarc** [comment]
Translation complete except SPECIES_PER. 
Needs review from @prvernier 

SPECIES_PER rules:
* If only one species in the layer - 100%
* If sa attribute is SH or HS:
  * If two species in the layer, and one is hardwood and one is softwood - we know one species is between 50-75% and the other is between 25-50%. Could use midpoints (37.5% and 62.5%).
  * If there are three species and either the hardwood or softwood component is made up of one species, we can assign percentage for that one species using the midpoint rule above.
* If multiple species of hardwood/softwood then we have no way of splitting the percentages from sa between the species.

**Comment by edwardsmarc** [comment]
Species percent of 100 added in rows with only 1 species er layer.

All translations now complete except PRODUCTIVE_FOR.

@prvernier to review before closing.

**Comment by edwardsmarc** [comment]
**UPDATE** following meeting with @prvernier:

* Species should actually be in 2 layers not 3. sp10, sp11, sp12, sp20, sp21 are species 1 - 5.

* Species percent is based on a very complex logic flow documented in the Cosco document. @prvernier has translated this to R. @edwardsmarc will write custom helper functions to translate species percent.

**Comment by edwardsmarc** [comment]
I made the change for species but it results in many rows having gaps in the species.

For example species_1 will have a value, species_2 and _3 will be null, and species_4 will have a value.

**Comment by prvernier** [comment]
@edwardsmarc - I've updated the R code to generate the SPECIES_* and SPECIES_PER_* attributes. I've added more comments to make it more clear. You can find the code in the file **sk01_spp.R** in the SK folder in the CAS project on my GitHub pages: https://github.com/prvernier/cas/tree/master/SK

**Comment by edwardsmarc** [comment]
Met with SC to discuss the species and species_percent rules.

We agree that for species, if for example values are only available for sp10 and sp20, then sp20 should be assigned to SPECIES_2, not SPECIES_4. This can be implemented with a new helper function getIndexNotNull(i, {sp10, sp11, sp12, sp20, sp21}) that returns the ith not null value. Hold off on writing this update until we have finalized the percent rules as they will also need to apply the same logic (simplest is probably for the percent function to calculate a vector of 5 percent values, then return the one matching the index returned from the species function).

For species_percent, we began going through the code and made the following decisions:

* @prvernier will re-write the R code so it returns a vector of 5 values instead of repeating rules for each of species_1 = species_5.
* @prvernier and @edwardsmarc will then review the code.
* @edwardsmarc will prepare an email to JC to check the rules, particularly the special cases involving JP and BS. cc SC.
* Once OKed by JC @edwardsmarc will write the logic into a helper function.

**Comment by prvernier** [comment]
I've revised the SPECIES_PER_1 - SPECIES_PER_5 R code. It will not run but should be a lot easier to understand, review, and translate. The file is called sk01_species_per.R and it is location in the "cas/SK" folder.

**Comment by edwardsmarc** [comment]
This is the query used to find the 14 scenarios of hardwood and softwood species that need percent translation rules developed:

`SELECT count(*), CONCAT(a._sp10, a._sp11, a._sp12, '(', a._sp20, a._sp21, ')') AS code
FROM(SELECT 
  TT_MapText(sp10, '{''WS'', ''BS'', ''JP'', ''BF'', ''TL'', ''LP'', ''GA'', ''TA'', ''BP'', ''WB'', ''WE'', ''MM'', ''BO''}', '{''S'',''S'',''S'',''S'',''S'',''S'',''H'',''H'',''H'',''H'',''H'',''H'',''H''}') AS _sp10,
  TT_MapText(sp11, '{''WS'', ''BS'', ''JP'', ''BF'', ''TL'', ''LP'', ''GA'', ''TA'', ''BP'', ''WB'', ''WE'', ''MM'', ''BO''}', '{''S'',''S'',''S'',''S'',''S'',''S'',''H'',''H'',''H'',''H'',''H'',''H'',''H''}') AS _sp11,
  TT_MapText(sp12, '{''WS'', ''BS'', ''JP'', ''BF'', ''TL'', ''LP'', ''GA'', ''TA'', ''BP'', ''WB'', ''WE'', ''MM'', ''BO''}', '{''S'',''S'',''S'',''S'',''S'',''S'',''H'',''H'',''H'',''H'',''H'',''H'',''H''}') AS _sp12,
  TT_MapText(sp20, '{''WS'', ''BS'', ''JP'', ''BF'', ''TL'', ''LP'', ''GA'', ''TA'', ''BP'', ''WB'', ''WE'', ''MM'', ''BO''}', '{''S'',''S'',''S'',''S'',''S'',''S'',''H'',''H'',''H'',''H'',''H'',''H'',''H''}') AS _sp20,
  TT_MapText(sp21, '{''WS'', ''BS'', ''JP'', ''BF'', ''TL'', ''LP'', ''GA'', ''TA'', ''BP'', ''WB'', ''WE'', ''MM'', ''BO''}', '{''S'',''S'',''S'',''S'',''S'',''S'',''H'',''H'',''H'',''H'',''H'',''H'',''H''}') AS _sp21
FROM rawfri.sk01 WHERE sa IN('SH','HS')
) AS a
GROUP BY code`

**Comment by pedrogit** [comment]
Without repetition and WITH syntax :

```
WITH mapping AS (
  SELECT '{''WS'', ''BS'', ''JP'', ''BF'', ''TL'', ''LP'', ''GA'', ''TA'', ''BP'', ''WB'', ''WE'', ''MM'', ''BO''}' from_species_code,
   '{''S'',''S'',''S'',''S'',''S'',''S'',''H'',''H'',''H'',''H'',''H'',''H'',''H''}' to_species_code
), a AS (
  SELECT TT_MapText(sp10, from_species_code, to_species_code) _sp10,
         TT_MapText(sp11, from_species_code, to_species_code) _sp11,
         TT_MapText(sp12, from_species_code, to_species_code) _sp12,
         TT_MapText(sp20, from_species_code, to_species_code) _sp20,
         TT_MapText(sp21, from_species_code, to_species_code) _sp21
  FROM rawfri.sk01, mapping
  WHERE sa IN('SH','HS')
)
SELECT count(*), CONCAT(a._sp10, a._sp11, a._sp12, '(', a._sp20, a._sp21, ')') code
FROM a
GROUP BY code;
```

**Comment by edwardsmarc** [comment]
Final rules for species percent vetted by JC. Only rules for hardwood/softwood combinations that exist in SK01 are included:

[SK UTM_species_percent_rules_v3.docx](https://github.com/edwardsmarc/CASFRI/files/4594398/SK.UTM_species_percent_rules_v3.docx)

**Comment by edwardsmarc** [comment]
Percent function complete. However blank species are not accounted for yet. So you can have SPECIES_1 and SPECIES_4 with no SPECIES_2 or 3.

Write custom function for species that gets the correct species index and runs lookupText.
Edit percent function to do the same.
