### ISSUE TITLE
ON02 LYR: SPECIES_ and SPECIES_PER_ helper function needed

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#276]
The ON02 inventory contains 2 relevant source attributes for populating the SPECIES_ and SPECIES_PER_ attributes: ospcom and uspcomp. Both attributes are composed of alphanumeric strings with up to 54 characters. Here are some examples:

Mr  20Mh  10Aw  10Iw  10Be  10Ow  10Ab  10Pt  10Bd  10
Mr  30Aw  10Bw  10Mh  10By  10Cw  10Bd  10Sw  10
Sb  40Pw  10Pj  10Pt  10Bf  10Cw  10Sw  10
Sb  60La  40
Sb 100

The helper function needs to split the string to extract the species and species percent information.

**Comment by edwardsmarc** [comment]
We'll need a species lookup table to map the strings to casfri species once the alphanumeric string has been parsed. I'm imagining a single function that would work for both ON and QC by parsing the strings and mapping species using the provided lookup table.

**Comment by prvernier** [comment]
I created look up tables for both ON and QC - they are located in the tables/lookup folder:

- on_fim02_species.csv
- qc_3rd_species.csv

Maybe @MelinaHoule can vet the latter.

**Comment by edwardsmarc** [comment]
Write validation function to catch cases where row does not have info for species x.

Can use TT_LengthMapInt with a user defined error code of NOT_APPLICABLE
