### ISSUE TITLE
Fix validation rules to deal with dist_year = 0

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#282]
Many inventories have disturbances with year being 0. Validation rules in the dst translation do not specifically deal with dist_year = 0 and those 0 are copied in final table. According to Steve, dist_year = 0 should be either treated as  missing data or invalid data.  

I proposed to set a bottom threshold to restrain the range of valid years for disturbance which would excude 0 (i.e.: isBetween(dist_year, 1950,2020)). 

Steve comments said: We should look at the various standards, but the correct call is either missing data or invalid data. If the standard says that a YEAR is required, than a 0 is an invalid entry. If the YEAR is optional, than I would consider a 0 as a missing value.

More insights is needed to assign the proper error code to dist_year = 0.

**Comment by pedrogit** [comment]
I guess we can close this one since we now have #337
