### ISSUE TITLE
Some translation rules depend on NULL values

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#283]
STAND_STRUCTURE in QC03 uses a lookup table to assign translation values.

If the source value is NULL, stand structure should be 'S'. We can pass NULL values through the validation rules using matchTable() with acceptNull = TRUE. This will catch any missing source values as NOT_IN_SET, but allows NULLs to be passed to the translation rule.

The translation rule is lookupText() which assigns a CASFRI value for each source value using a lookup table. Adding NULL to the lookup table does not work because a) it is interpreted as a string 'NULL', and b) the lookupText() translation function is hard-coded to return NULL if source value is NULL. This means any NULL source value will always return TRANSLATION_ERROR.

Option 1 - add a nullReturns argument to lookupText(). Any NULL source value will be set to nullReturns. This would default to NULL but could be set to 'S'. 

Option 2 - write a custom CASFRI helper function to deal with this case. This function would hard code NULL to be translated to 'S', then run lookupText().

**Comment by pedrogit** [comment]
What if you leave the space empty in the lookup table? Doesn't it translate to NULL in the function?

And definitely the function should accept NULL source value.

**Comment by MelinaHoule** [comment]
As Mark said in the Slack translation thread : So the problem here is that we cannot use null as a lookup source value. The reason is that the lookup table NULL is interpreted as a string and not a true null. Additionally, all translation rules are coded to return an error when the source value is a true null.

I don't know if we can change that behavior....

**Comment by pedrogit** [comment]
I repeat: What if you leave the space empty in the lookup table? Doesn't it translate to NULL when the table is read by the function? I'm pretty sure en empty cell in CSV translate into a NULL in PostgreSQL.

**Comment by MelinaHoule** [comment]
It doesn't. It returns the error code "TRANSLATION ERROR" when source_value is NULL.

**Comment by pedrogit** [comment]
It doesn't what? If the loaded value is NULL then that means it does....

Then Marc only has to change the function so it accept NULL source values.

**Comment by edwardsmarc** [comment]
An empty space in the lookup table appears to be loaded as an empty string.

i.e. 
`SELECT TT_notempty(source_val) FROM translation.qc03_standstructure WHERE ogc_fid = 74` returns FALSE, and 
`SELECT TT_notnull(source_val) FROM translation.qc03_standstructure WHERE ogc_fid = 74` returns TRUE.

**Comment by pedrogit** [comment]
So if you put empty string ('') in the translation rule, and change the lookupText() function to convert NULLs to empty spaces, does it get translated to the right value?

**Comment by MelinaHoule** [comment]
***Here is more info on Quebec (please correct me if I'm wrong with the translation)

In the 3rd and 4th, no column per se gives information about the structure of the stand. That information is implemented in the 5th inventory. 

We know a polygon is LYR if there is a cl_age associated. 
cl_age =  VIR or JIR mean a complexe structure with the height of its stems is within an amplitude of 8 m and more. 
cl_age filled with single age class means stand structure single layered with num of layers = 1.
cl_age filled with double age class means stand structure multilayered with num of layers = 2.

A polygon can be either NFL or LYR. It can't be both at the same time. 
A polygon can't have 2 NFL recorded. A NFL thus have a singular structure which lead to stand_structure = S.

This is where the NULL value comes from.

**Comment by edwardsmarc** [comment]
@pedrogit 

Yes that works. But wouldn't it be simpler to just use option 1 above and convert the NULL straight to 'S'.

I guess we have two options now.

1) Add a passNullTo option in TT_LookupText(). NULLs get converted to empty strings inside the function and translated using the lookup table. Return value is whatever is defined for empty string in the lookup table.

2) Add a nullReturns argument. Any NULLs immediately get returned as this value. We would set this to 'S'.

**Comment by MelinaHoule** [comment]
I think I prefer the passNullTo option. The lookupTable will allow to cover every case to be translated.

**Comment by pedrogit** [comment]
I don't like option 1 because you get returned values defined in two places: the rule and the lookup table. This could be confusing.

Why do we need an option at all? Can we just always convert NULL to ""?

**Comment by edwardsmarc** [comment]
Just tested that and I think always converting NULL to '' will work. 

If empty string is in the lookup table, it gets converted correctly. 

If empty string is not in the lookup table, the translation rule throws an error which results in TRANSLATION_ERROR. Same thing as the current behavior (NULL returns NULL which leads to TRANSLATION_ERROR).

@MelinaHoule I will push my update to the helper function. You will need to re-install the helper function file. And add an empty cell to your lookup table that is set to translate to S.

**Comment by edwardsmarc** [comment]
Note the only case we can't cover with some combination of TT_NotNull, TT_MatchTable, and TT_TT_LookupText, is the case where empty string and NULL source values need to be translated to two different target values.

Closed with engine commit https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/commit/424494c3acd2644b3717c6d423c815e2c58a3067
