### ISSUE TITLE
QC03 LAYER translation

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#285]
Can we use TT_CountOfNotNull with attributes sup_cl_age_et and inf_cl_age_et? LYR 1 table would always use sup_ attributes and LYR 2 would always use inf_ attributes.

![image](https://user-images.githubusercontent.com/10728298/75716255-ab24ac80-5c83-11ea-956f-2994f5ed3868.png)

I will test this out. If not we will need a custom function.

**Comment by edwardsmarc** [comment]
Can't use TT_CountOfNotNull() because may rows have cl_age but no sup_cl_age_et and inf_cl_age_et.

However, it might be the case that we can just hard code the layer values if the following logic is true:
* If polygon has NFL info it never has LYR info. And only one NFL layer is possible. So all NFL rows have to be LAYER = 1.
* Forest layers are defined in the cl_age attribute which can contain age codes for either one or two layers. Translations for LAYER 1 will always use the first age code in the string. 
* Translations for LAYER 2 will always use the second code in the string if one exists.

@MelinaHoule if these three statements are true then we can hard code the layer values in the attribute dependencies table and simply use the translation rule copyInt().

**Comment by MelinaHoule** [comment]
Yes those 3 statements are correct. Remember, age can be defined using 2 or 3 characters. Age of layers can thus not be extract by using the first 2 characters for example.

**Comment by edwardsmarc** [comment]
@MelinaHoule - One more question for this, is it possible to have layer 2, without layer 1? I think no, because if there's only one age code in cl_age it is by definition, layer 1.

**Comment by MelinaHoule** [comment]
No it is not possible. In the diagram:
Layer --> check cl_age--> if cl_age NOT NULL -->check cl_age single (NUM_OF_LAYERS = 1) or 
                                                                                double (NUM_OF_LAYERS =2)
                                          if cl_age IS NULL --> NUM_OF_LAYERS = 1
