### ISSUE TITLE
QC03 CROWN_CLOSURE translation

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#286]
Custom function required.

![image](https://user-images.githubusercontent.com/10728298/75716546-40c03c00-5c84-11ea-974a-ffce2350e094.png)

**Comment by edwardsmarc** [comment]
Height uses the same logic but with different columns. Write one function that works for both?

![image](https://user-images.githubusercontent.com/10728298/75716621-6a796300-5c84-11ea-85d7-268b35c37fd9.png)

**Comment by edwardsmarc** [comment]
Function logic:

Validation
* Use notNull(cl_age) to catch the NFL rows and report error code.
* Write custom validation function to ctch the cases below.

Translation
- num_of_layers = lookupInt(cl_age, 'translation', 'qc03_standstructure', 'num_of_layers')

- if cl_age is not null
  - if in_etage = O
    - if num_of_layers = 1
      - return sup_densitie/sup_hauteur
    - if num_of_layers = 2
      - get layer 1 age code using lookup table
      - Compare to sup and inf age columns, identify if it matches sup or inf
      - Return sup_hauteur or inf_hauteur depending on match.
      - repeat for second layer age code.
  - else in_etage = N
    - if cl_dens is null
      - no density/height - might want to catch these cases with a validation rule
    - if cl_dens is not null
      - for LYR 1 translation
        - return cl_dens/cl_haut
      - for LYR 2 translation
        - no value reported - catch with validation rule

**Comment by edwardsmarc** [comment]
@MelinaHoule - cl_dens and cl_haut have values that are codes. 
cl_dens can be A, B, C, D, H or I. 
cl_haut can be 1, 2, 3, 4, 5, 6 or 7.

Do you know what each code represents?

**Comment by edwardsmarc** [comment]
Need validation functions to catch the following cases:

* cl_age is null
* layer 1 age code and layer 2 age code assigned in lookup table do not match sup_cl_age_et and info_cl_age_et values. INVALID.
* in_etage = N and cl_dens/cl_haut is null. No data available.
* in_etage = N, cl_dens has a value but layer 2 requested. No data available.

**Comment by MelinaHoule** [comment]
-----CL_HAUT meaning
1:>22m
2:17-22m
3:12-17m
4:7-12m
5:4-7m
6:2-4m
7:<2m
***Note that sup_hauteur and inf_hauteur are the heigth in meters. They are not height class

**Comment by MelinaHoule** [comment]
-----CL_DENS meaning (at the polygon level)
A : => 80% covered
B : >= 60%  and < 80%
C : >= 40% and < 60%
D : >= 25% and < 40%
H : >= 60% 
I : < 60%

inf_densite and sup_densite represent crown_closure in % at the layer level

**Comment by edwardsmarc** [comment]
In some cases there are 2 layers, but the codes are the same. e.g. 1010. In these cases we don't know which age code relates to sup and inf so we don't whether to return the density value from the sup or inf table.

We could assume layer 1 is sup and layer 2 is inf in these cases.
Or we can return an error code.

**Comment by MelinaHoule** [comment]
If there are 2 layers (derived by cl_age) but they are not present in étage (in_etage = 'N') than cl_haut applied to LAYER = 1 (the most dominant) and LAYER=2 has heigth unknown.   For CROWN_CLOSURE, when NUM_OF_LAYERS = 2, it is not possible to assign any specific CROWN_CLOSURE to any layers because the % (or class code) represent the crown closure for the canopy (polygon level)

**Comment by edwardsmarc** [comment]
OK.
And what if in_etage = 'O' and there are two layers with the same code (e.g. 1010). Usually we would take the first code (10) and compare it to the sup and inf age codes to decide which table to return the density/height from. But if they are both the same, how do we know which table to return from?

Put another way, what do we we do if we have the following attribute values, do we return the 50 or the 70?
cl_age: 1010
sup_cl_age_et: 10
inf_cl_age_et: 10
sup_densite: 50
in_densite: 70

**Comment by MelinaHoule** [comment]
I ran some stats. The column et_domi gives use the information on which column is dominant. The codes are:
EQU: Both layers have the same coverage (45%-55%)
SUP: sup is layer one and it covers more than 50%
INF: inf is the dominant layer (layer 1) and it covers more than 50%

There are about 60 000 entries that are in_etage with 2 age class. Layer order can be classified using et_domi in 53 000 cases. 

et_domi IS NULL for 4300 having 2 age class. As discussed, we can defined layer number based on the order of the age class. 

However, 110 polygons use the same code within cl_age (1010,3030,7070,...). In every cases, double age class is always place in sup_cl_age_et with no species and all inf columns are empty. That means species will need to be derived from gr_ess with there percent according to the rule of the third inventories.

**Comment by edwardsmarc** [comment]
Updated logic...

Validation
* Use notNull(cl_age) to catch the NFL rows and report error code.
* Write custom validation function to ctch the cases below.

Translation
- num_of_layers = lookupInt(cl_age, 'translation', 'qc03_standstructure', 'num_of_layers')

- if cl_age is not null
  - if in_etage = O
    - if num_of_layers = 1
      - return sup_densitie/sup_hauteur
    - if num_of_layers = 2
      - if et_domi is not null, use it to find if layer 1 is in sup or inf table. Return the appropriate value based on which is dominant and which layer is being processed by the function.  
      - if et_domi is null
        - if cl_age in ('1010','3030','5050','7070','9090','12012','JINJI'), only sup info available. **USE SUP INFO FOR LAYER 1, LAYER 2 HAS NO INFO TO RETURN   ///   OR   ///   USE SUP INFO FOR BOTH LAYERS.**
        - for all other cl_age values, get age code for the layer being processes using lookup table. Compare to sup and inf age columns, identify if it matches sup or inf. Return value from whichever table matches.
      
  - else in_etage = N
    - if cl_dens is null
      - no density/height - might want to catch these cases with a validation rule
    - if cl_dens is not null
      - for LYR 1 translation
        - return cl_dens/cl_haut. These are codes that need to be translated to actual values. Upper_lower argument to get top or bottom of range. cl_dens is a polygon level measure so can only be returned if num_of_layers = 1. Height is specific to the top layer so can returned when num_of_layers = 1 or 2.
      - for LYR 2 translation
        - no value reported - catch with validation rule

**Comment by edwardsmarc** [comment]
Remaining questions for @MelinaHoule :

* 110 polygons have matching layer age codes but et_domi is null. These only have sup info. Is that sup info only relevant for layer 1, or do we use the sup info for layers 1 and 2. I'm guessing it's just layer 1 and we return null for layer 2.

* If we have 2 layers and et_domi = EQU, do we use the first age class code in in cl_age as layer 1? If so the logic for rows where et_domi = EQU will be the same as rows where et_domi IS NULL.

**Comment by MelinaHoule** [comment]
Answers: 

- YES info is related only to layer 1. In the middle of Qc 4th inventory, et_domi was implemented. Many polygons with no_prg = 4 thus follow rules from 3rd inventory. If in_etage = 'O' but sup_eta_ess_pc IS NULL, we need to derive species info from gr_ess. cl_age, cl_dens and cl_haut is assigned to layer 1. We can derive species for layer 2 from gr_ess but crown_closure, age and heigth will be unknown. 

- In the doc, it is written that layer is defined according to heigth. I would say, if layer = EQU, we based layer 1 according to height, not age.  Need to be discussed.

**Comment by edwardsmarc** [comment]
Added code for the case where in_etage is N, et_domi is null, and sup and inf have the same ages.

Remaining is to assign density when et_domi is EQU. As discussed in the comment above.

**Comment by edwardsmarc** [comment]
I'm having trouble remembering all the cases and logic here, and what the differences between density and height translations should be. I propose for these complex QC translations we map out all the possible values and expected return values in a table. This table can then be used to write the tests. I'll make a first attempt here for @MelinaHoule to review:

## Density
Attributes used to define logic:
- cl_age - full age code
- in_etage - is the row from 4th inventory
- et_domi - is sup or inf dominant (EQU, SUP, INF)
- sup_cl_age_et - 4th inventory sup layer age - used to decide whether layer 1/2 is sup/inf
- inf_cl_age_et - 4th inventory inf layer age - used to decide whether layer 1/2 is sup/inf
- sup_densite - 4th inventory sup layer density
- inf_densite - 4th inventory inf layer density
- cl_dens - 3rd inventory density value (polygon level attribute)
- layer - layer being processed
- num_of_layers - calculated from lookup table

| cl_age | in_etage | et_domi | cl_dens | layer | num_of_layers | RETURN |
| ------------------------ | --- | ------ | --- | ---------- | --- | ------------- |
|                                     | O   |          |       | 1              | 1    | sup_densite |
|                                     | O   |          |       | 2              | 1    | NULL           |
| Ages match e.g. 1010 | O   | NULL |       |  1             | 2    | sup_densite |
| Ages match e.g. 1010 | O   | NULL |       |  2             | 2    | NULL           |
| Ages don't match       | O   | NULL |       |  sup layer | 2    | sup_densite |
| Ages don't match       | O   | NULL |       |  inf layer  | 2    | inf_densite    |
|                                    | O   | SUP   |        |  1             | 2    | sup_densite  |
|                                    | O   | SUP   |        |  2             | 2    | inf_densite   |
|                                    | O   | INF    |        |  1             | 2    | inf_densite   |
|                                    | O   | INF    |        |  2             | 2    | sup_densite |
|                                    | O   | EQU  |        |  1             | 2    | ???               |
|                                    | O   | EQU  |        |  2             | 2    | ???               |
|                                    | N   |          |        | 1              | 1    | mapInt(cl_dens ...) |
|                                    | N   |          |        | 2              | 1    | NULL           |
|                                    | N   |          |        | 2              | 2    | NULL           |

## Height
Attributes used to define logic:
- cl_age - full age code
- in_etage - is the row from 4th inventory
- et_domi - is sup or inf dominant (EQU, SUP, INF)
- sup_cl_age_et - 4th inventory sup layer age - used to decide whether layer 1/2 is sup/inf
- inf_cl_age_et - 4th inventory inf layer age - used to decide whether layer 1/2 is sup/inf
- sup_hauteur - 4th inventory sup layer height
- inf_hauteur - 4th inventory inf layer height
- cl_haut - 3rd inventory height value (polygon level attribute)
- layer - layer being processed
- num_of_layers - calculated from lookup table

| cl_age | in_etage | et_domi | cl_dens | layer | num_of_layers | RETURN |
| ------------------------ | --- | ------ | --- | ---------- | --- | -------------- |
|                                     | O   |          |       | 1              | 1    | sup_hauteur |
|                                     | O   |          |       | 2              | 1    | NULL            |
| Ages match e.g. 1010 | O   | NULL |       |  1             | 2    | sup_hauteur |
| Ages match e.g. 1010 | O   | NULL |       |  2             | 2    | NULL            |
| Ages don't match       | O   | NULL |       |  sup layer | 2    | sup_hauteur |
| Ages don't match       | O   | NULL |       |  inf layer  | 2    | inf_hauteur    |
|                                    | O   | SUP   |        |  1             | 2    | sup_hauteur  |
|                                    | O   | SUP   |        |  2             | 2    | inf_hauteur   |
|                                    | O   | INF    |        |  1             | 2    | inf_hauteur   |
|                                    | O   | INF    |        |  2             | 2    | sup_hauteur |
|                                    | O   | EQU  |        |  1             | 2    | ???               |
|                                    | O   | EQU  |        |  2             | 2    | ???               |
|                                    | N   |          |        | 1              | 1    | mapInt(cl_dens ...) |
|                                    | N   |          |        | 2              | 1    | mapInt(cl_dens ...) |
|                                    | N   |          |        | 2              | 2    | NULL           |

**Comment by edwardsmarc** [comment]
We have now updated the QC approach and split the source data into three inventories that will each have their own set of translation rules. Roughly these can be considered as the 3rd, 4th and 5th standards which will be named QC03, QC04 and QC05.

This greatly simplifies the translation rules.

## QC03 and QC04
- In these datasets in_etage is always N, so we can use the following translations pulled from the logic above.

### CROWN_CLOSURE_UPPER
- We use the cl_dens attribute which is at the polygon level. 
- For this reason we must use a validation function to only run the translation if there is exactly 1 layer. If there are two layers we don't know which layer the cl_dens attribute applies to. This will require a new helper function named tt_lookupIntMatchList(). It will lookup the number of layers in the lookup table using the cl_age attribute. If num_of_layer = 1 the validation passes. Otherwise an error code (UNKNOWN_VALUE) is returned. 
- The translation function will then run mapInt using the cl_dens attribute and the correct translation depending on whether its the _UPPER or _LOWER.
- There is no need to validate that the layer being processed is layer 1 because the ROW_TRANSLATION_RULE will only allow layer 2 translations to happen if num_of_layers = 2. And in that case the existing validation function will fail because num_of_layers != 1.

#### Validation
`notNull(cl_dens);notEmpty(cl_dens);lookupIntMatchList(cl_age, 'translation', 'qc_ipf05_standstructure', 'num_of_layers', 1|UNKNOWN_VALUE)`
#### Translation
mapInt(cl_dens, {'A','B','C','D','H','I'}, {100,80,60,40,100,60})

### CROWN_CLOSURE_LOWER
#### Validation
`notNull(cl_dens);notEmpty(cl_dens);lookupIntMatchList(cl_age, 'translation', 'qc_ipf05_standstructure', 'num_of_layers', 1|UNKNOWN_VALUE)`
#### Translation
mapInt(cl_dens, {'A','B','C','D','H','I'}, {80,60,40,25,60,0})

### HEIGHT_UPPER
- Height is specific to the top layer, i.e. layer 1. So validation needs to catch case where layer != 1 and return UNKNOWN_VALUE.
#### Validation
`notNull(cl_haut);notEmpty(cl_haut);matchList(cl_haut, 1|UNKNOWN_VALUE)`
#### Translation
`mapInt(cl_haut, {'1','2','3','4','5','6','7'}, {100, 22, 17, 12, 7, 4, 2})`

### HEIGHT_LOWER
#### Validation
`notNull(cl_haut);notEmpty(cl_haut);matchList(cl_haut, 1|UNKNOWN_VALUE)`
#### Translation
`mapInt(cl_haut, {'1','2','3','4','5','6','7'}, {22, 17, 12, 7, 4, 2, 0})`

## QC05 ... in progress

**Comment by edwardsmarc** [comment]
Delete TT_qc_ipf_height_translation() and TT_qc_ipf_crownclosure_translation() from helper functions once we are happy with the revised translations.
