### ISSUE TITLE
QC03 SPECIES and SPECIES_PER translations

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#287]
Need custom function to parse species codes. Should take arguments of source_val, species number required (e.g. 1), do you want species name or percent?

Will also need a validation function to check if the requested species number exists. i.e. if you request species 2 but there is only 1 species, validation rule should catch this and return error code.

@MelinaHoule is working on the logic for the species codes. What patterns exist. what happens if there is no percentage etc.

**Comment by MelinaHoule** [comment]
In QC03, some polygons used an old standard (no_prg=3) that use species composition instead of independent species and species_per. Species_per need to be derived according to definition of the species composition. The species composition uses range to describe the coverage of a specie. Some general rules are needed. How to fix species_per with those definitions?

1. In stand with 2 species group: species_per_1 is >50% but <75%? How to establish species_per_1 and specie_pers_2

2. Non commercial deciduous cover >50%
species_1: non commercial deciduous
species_per_1:
species_2: unknown
species_per_2:

3. A specie X covers >75%?
species_1: X
species_per_1:
species_2:
species_per_2:

4. A specie X covers >50% but <75%?
species_1: X
species_per_1:
species_2:
species_per_2:

5. 2 species together (X and Y) cover >50% but less than 75% with species X having higher % than Y ?
species_1: X
species_per_1:
species_2: Y
species_per_2:
species_3:
species_per_3:

6. specie X covers >66%
species_1: X
species_per_1:
species_2:
species_per_2:

7. specie X covers >33% but <66%
 
8. specie X covers >33% but <50%

9. 3 species (X,Y,Z), specie X covers >50%, specie Y covers >25%

**Comment by MelinaHoule** [comment]
Here is an example of a complex definition: gr_ess = BBPER: White birch with softwood (deciduous dominance where birch occupies 50% to 75% and Poplar occupies 25% to 50% **of the hardwood strata**). 

We know there are 3 species : Birch sp, poplar sp and softwood unknown. 
But the % given express what's within the hardwood strata and not the % within the stand. How do we fix softwood % and what is the real % of birch and poplar?

**Comment by MelinaHoule** [comment]
Example 2: gr_ess = EBB: White birch with black spruce or red spruce (conifer dominance where birch occupies 51% to 100% of the hardwood s.t.)

Do we translate as:
species_1: **Spruce sp**
species_per_1: **60**
species_2: **Birch**
species_per_2: **30**
species_3: **Hardwood unknown**
species_per_3: **10**

How do we justify percent in our standard?

**Comment by edwardsmarc** [comment]
This is similar to the info we had for the SK UTM standard. In that case JC had some rules for the possible percent values under different combinations of hardwood and softwood species. There was a table in the appendix that we were able to use to figure out the rules for CAS05.

@prvernier I wonder if there is a similar table for QC in JC's documentation?

**Comment by prvernier** [comment]
Yes, there is, Appendix 7 (p 49-51) in the Cosco 2011 specifications.

**Comment by MelinaHoule** [comment]
Here is the logic.  Species and species percent depend of  in gr_ess, in_etage and no_prg.

_gr_ess_ is used to define species and species_per in the 3rd and first half of the 4th inventory. 3rd and 4th don't use the same species list. Some code are used to describe different species.... Percent are not the same either. They need to have a different lookup table. A query on _no_prg_ ensure the use of the proper lookup table. 

For the second half of the 4th and 5th, species and species_per are found  under _sup_eta_ess_pc_ for layer_1 and _inf_eta_ess_pc_ for layer_2.   They use the same species list. We know we need to check in those columns to extract species and species_per when _in_etage = 'O'_. 

I wrote a SQL query to extract species and percent according to position. If it can be useful in the helper function... 


![QC03_species_mindmup](https://user-images.githubusercontent.com/10730242/89787505-90d0e380-daeb-11ea-8909-97274d468c41.jpg)

**Comment by edwardsmarc** [comment]
@MelinaHoule - Where can I find the QC03_ipf05_species lookup table?

Also, I don't understand the query for splitting gress according to position. When I try and get the 1st species it returns the whole gr_ess string. Maybe I have something wrong? Here's the code I was trying:
`SELECT trim(SPLIT_PART(species, ' ', 1)) as species_split, gr_ess
FROM (SELECT trim(regexp_replace(gr_ess, '(.{2})', E'\\1', 'g')) as species, gr_ess
     FROM rawfri.qc03 WHERE no_prg='4' AND in_etage = 'N' AND gr_ess IS NOT NULL) r
GROUP BY r.species, r.gr_ess`

**Comment by edwardsmarc** [comment]
@MelinaHoule if in_etage is N, can there only be one layer? Layer 2 only has a value when in_etage = O?

**Comment by MelinaHoule** [comment]
Yes. The concept of layer appear late in the 4th with in_etage. Num_of_layer = 1 when in_etage = 'N'

**Comment by MelinaHoule** [comment]
Following @edwardsmarc comment ( I noticed that sup_eta_ess_pc can have a value when gr_ess is NULL), we should change the logic for the function to avoid dropping information. 
![QC03_species_mindmup_v2](https://user-images.githubusercontent.com/10730242/93343843-f9a02f80-f7fe-11ea-9d8a-302ee18073ee.jpg)

**Comment by MelinaHoule** [comment]
That would make the species_per function to follow the same logic 
![QC03_species_per_mindmup_v2](https://user-images.githubusercontent.com/10730242/93347928-9fee3400-f803-11ea-8761-fc968273d34c.jpg)

**Comment by edwardsmarc** [comment]
Validation function is needed for no_prg 4 to catch the case where species 2 or 3 is requested, but species code is doubled (e.g. PePe). These cases should return NOT_APPLICABLE.

**Comment by edwardsmarc** [comment]
For prg 5 species are not coded in the order we need. Species order follow these rules: 
1) crown closure from conifer vs deciduous (if a stand is mixed conifer dominant, all conifers will be named first), 
2) if crown closure is the same, it follow a specific richness order given in the manual, 
3) if crown closure is the same and both species were planted, it follow alphabetic order, 
4) in reforested polygons, planted species go first and invasive species go last.

We want species to be ordered by percent cover. Function needs to be edited to return species in order of percent, i.e. species 1 will always have highest percent. If two species have the same percent, return them in the order they occur in the source code.

**Comment by edwardsmarc** [comment]
I've added the following functions to helperfunctionsCASFRI.sql:

- TT_qc_prg4_not_double_species_validation(gr_ess)
- TT_qc_prg4_species_translation(gr_ess, species_number)
- TT_qc_prg4_species_per_translation(gr_ess, species_number)
- TT_qc_prg5_species_translation(eta_ess_pc, species_number)
- TT_qc_prg5_species_per_translation(eta_ess_pc, species_number)

Since we are now translating each prg separately we don't the complex if else logic that used in_etage, no_prg etc. Each of the functions simply runs the sql you included in the diagrams above.

_A note on place holders...If you look at the translation tables for other inventories you'll see we have standardized the attribute names in the tables. This is to make the tables more readable. For example the species attributes are always species_1, species_2 etc. These are then mapped to the correct source attribute name using the attribute_dependencies table. In our case all species are coded in a single attribute so we will map species_1, species_2 etc. all to gr_ess (for prg 3 and 4), to sup_eta_ess_pc when translating layer 1 in prg 5, or to inf_eta_ess_pc when translating layer 2 in prg 5._

Here is my initial attempt at the translation table rules for using these new functions.

## prg 3
No custom functions needed. We can simply use the lookup functions to get the required values from the lookup table. All species_1 etc. and species_per_1 ect. placeholders should be mapped to gr_ess in the attribute dependencies table.
### Validation - check code is not null or empty. Check code is in lookup table.
`notNull(species_1);notEmpty(species_1);matchTable(species_1, 'translation', 'qc_ipf05_species_prg3', 'gr_ess')`
`notNull(species_1_per);notEmpty(species_1_per);matchTable(species_1_per, 'translation', 'qc_ipf05_species_prg3', 'gr_ess')`
`notNull(species_2);notEmpty(species_2);matchTable(species_2, 'translation', 'qc_ipf05_species_prg3', 'gr_ess')`
`notNull(species_2_per);notEmpty(species_2_per);matchTable(species_2_per, 'translation', 'qc_ipf05_species_prg3', 'gr_ess')`
`notNull(species_3);notEmpty(species_3);matchTable(species_3, 'translation', 'qc_ipf05_species_prg3', 'gr_ess')`
`notNull(species_3_per);notEmpty(species_3_per);matchTable(species_3_per, 'translation', 'qc_ipf05_species_prg3', 'gr_ess')`

Species 4 and up would use `false()` because they do no appear in the source data.

### Translation - return the correct column from the lookup table.
`lookupText(species_1, 'translation', 'qc_ipf05_species_prg3', 'gr_ess', 'species_1')`
`lookupText(species_per_1, 'translation', 'qc_ipf05_species_prg3', 'gr_ess', 'species_per_1')`
`lookupText(species_2, 'translation', 'qc_ipf05_species_prg3', 'gr_ess', 'species_2')`
`lookupText(species_per_2, 'translation', 'qc_ipf05_species_prg3', 'gr_ess', 'species_per_2')`
`lookupText(species_3, 'translation', 'qc_ipf05_species_prg3', 'gr_ess', 'species_3')`
`lookupText(species_per_3, 'translation', 'qc_ipf05_species_prg3', 'gr_ess', 'species_per_3')`

Species 4 and up would use `nothingText()` for SPECIES because they do no appear in the source data; and `nothingInt()` for SPECIES_PER.

## prg 4
Here we need to use the custom functions to extract the correct species value and pass it to the lookup table. We also need to catch the double species when translating species 2. Again, all species and percent placeholders are mapped to gr_ess.

### Validation - check the code is not null or empty. For species 2 check its not a double. If it is return NOT_APPLICABLE. 
`notNull(species_1);notEmpty(species_1)`
`notNull(species_per_1);notEmpty(species_per_1)`
`notNull(species_2);notEmpty(species_2);qc_prg4_not_double_species_validation(species_2|NOT_APPLICABLE)`
`notNull(species_per_2);notEmpty(species_per_2);qc_prg4_not_double_species_validation(species_per_2|-8887)`
`notNull(species_3);notEmpty(species_3)`
`notNull(species_per_3);notEmpty(species_per_3)`
This pattern would continue up SPECIES_X where X is the maximum possible number of species in the source inventory. Everything beyond X would use `false()`.

### Translation - run the custom function with the correct species_number.
`qc_prg4_species_translation(species_1, '1')`
`qc_prg4_species_translation(species_per_1, '1')`
`qc_prg4_species_translation(species_2, '2')`
`qc_prg4_species_translation(species_per_2, '2')`
`qc_prg4_species_translation(species_3, '3')`
`qc_prg4_species_translation(species_per_3, '3')`
etc.

## prg 5
I'll update this when the more complex function has been created....

**Comment by edwardsmarc** [comment]
prg 4 species function needs more work.

BPBPSB should return "Betu papy"	70	"Abie bals"	30     "NOT_APPLICABLE"	-8887

i.e. doubles are really a single species.

Also need a validation function to check how many species there are before attempting translation.

**Comment by MelinaHoule** [comment]
In prg4, lenght(gr_ess) = 6 represents mix stand. The 2 first species indicate if the stand is conifer or deciduous dominant. Species 1 and species 2 can thus be duplicate if a stand is mix with only 2 species (e.g., ESESSB). When 3 species and the 2nd is the same as the 1st, we follow John Cosco rule and transfert only spp 1 and spp 3 to CAS as species_1 and species_2 with 65% and 35%. In a mix stand (3 species) where no species are doubled, Cosco rule translate percent as follow: 1st=51%, 2nd=25%, 3rd=24%. However according to the QC04 manual, the definition of a mix stand is that the dominant group should be between 50-75% and the other group should be between 25-49%. We should thus change the rules to make percent be 1st=37%, 2nd=33%, 3rd=30%.
![prg4](https://user-images.githubusercontent.com/10730242/96920961-df9be180-147b-11eb-8b0c-818b7a17ba6a.jpg)

**Comment by edwardsmarc** [comment]
So in the case of a 6 character code where species 1 and 2 are the same, we can just drop the first species code and treat the remaining 4 character code as we normally would.

In the example above, for 'BBBBRX' we would drop 'BB', leaving us with 'BBRX' which would return 'BB' at 65% and 'RX' at 35%.

@MelinaHoule is this correct?

**Comment by edwardsmarc** [comment]
Validation function should first drop the first species in the case of a 6 char code where species 1 and 2 are the same. Then pass the string to tt_lengthmatchList() to check that for e.g. SPECIES_3 and SPECIES_PER_3 have a third species to translate.

**Comment by edwardsmarc** [comment]
I have updated the functions and added a new function.

For the species and species_per translations you can still use:
- qc_prg4_species_translation
- qc_prg4_species_per_translation

I have updated these so that if they receive any gr_ess code of any length (i.e. length 4 or 6) that starts with a double species code (e.g. FXFX, PUPU), the first two characters will simply be removed and the function will continue as normal. So 'FXFXPU' will be processed as 'FXPU', and 'FXFX' will be processed as 'FX'.

For the validation you no longer need *qc_prg4_not_double_species_validation()*, it still exists because I use it internally, but for the translation table you can now replace it with *qc_prg4_lengthMatchList(gr_ess, list)* which we can use to validate the number of species for all species and species_per translations.

*qc_prg4_lengthMatchList(gr_ess, list)* takes the gr_ess code, removes the first two characters if the code starts with a double species entry (e.g. FXFX, PUPU), then passes the resulting string to tt_lengthMatchList() which counts the number of characters and returns TRUE if the length matches an integer in the list. i.e. it corrects the code and counts how many species we have.

Here's how we can use it to check if there are at least 1, 2 or 3 species.
For species_1 and species_per_1 use: *qc_prg4_lengthMatchList(species_1, {2, 4, 6})*
For species_2 and species_per_2 use: *qc_prg4_lengthMatchList(species_1, {4, 6})*
For species_3 and species_per_3 use: *qc_prg4_lengthMatchList(species_1, {6})*

**Comment by MelinaHoule** [comment]
I have this error: ERROR IN TRANSLATION TABLE AT RULE_ID # 13 (SPECIES_1): No error code defined for validation rule 'qc_prg4_lengthMatchList(species_1, {2, 4, 6})'. Should error code be 'NOT_IN_SET'?

**Comment by edwardsmarc** [comment]
Add "|NOT_APPLICABLE" as a custom error code. NOT_APPLICABLE is used in most other cases where there is no SPECIES_X to translate. I need to add default error code for many custom functions #445 which is why you got the error.

**Comment by MelinaHoule** [comment]
Closed with e536b24cb706f6ff4f0b3857637ee750bd5d722c
