### ISSUE TITLE
Create 2 lookupTable for QC03 species translation

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#288]
To translate species in QC03, we will need to use 2 lookuptables: one for species and one for gr_ess.  QC03 is a mix of QC 3rd, 4th and 5th inventories. Most of the time, the 4th and 5th inventories has information on species with percent associated.  When species is absent (all the time in 3rd and sometimes in 4th), the provinces uses gr_ess to describe species within a polygon. It doesn't have percent per se.  However, gr_ess in 3rd doesn't use the same value to code species in the 4th. For example, gr_ess = ES in 3rd means spruce and in 4th means mapple. The lookupTable will need to consider inventory program to translate species when using gr_ess lookupTable.

**Comment by kdarndt** [comment]
The NFI has a tree species lookup table that includes English and French common names.  The French common names are not completely unique, but it would be a start. It would be great if this could be used.  Could also be used for validation (ie: issue #191 )

      Column      |         Type          |                                     
Modifiers                                     
------------------+-----------------------+-------------------------------------
----------------------------------------------
 eng_common_name  | character varying(50) | 
 fre_common_name  | character varying(50) | 
 latin_name       | character varying(50) | 
 genus            | character varying(4)  | 
 species          | character varying(3)  | 
 variety          | character varying(3)  | 
 veg_type         | character varying(2)  | 
 is_exotics       | character varying(1)  | 
 eng_display_name | character varying(50) | 
 fre_display_name | character varying(50) | 
 id               | integer               | not null default nextval('nfi_dms.nf
i_tree_species_list_lookup_id_seq'::regclass)

**Comment by MelinaHoule** [comment]
There are some inconsistencies between the existing translation rules (cosco manual) and description of some group species  given by the province.  More details have been sent to Cosco to solve that issue. Fro example, BB1S (White birch (BB)  with spruce or fir (S)). According to the manual, when first spp is followed by +, 1st should be 70%.  The province define the polygon as follow: Mixed stand where deciduous trees represent 50% to 75% of the total basal area of the stand and where birch constitutes 50% to 75% of that of the deciduous part. In these stands, over 50% of the surface area of the coniferous part is made up of fir and white spruce.  My question: If all deciduous is 50-75% where birch is 50-75% within deciduous, birch can't be 70%. Should we add a 3rd spp hard unkn? Seven similars questions remain. I sent an email to John Cosco and I am waiting to hear from him prior to finish the lookup table for 3rd inventory.

**Comment by MelinaHoule** [comment]
In QC03 when no_prg=4 a stand is considered mix when
1)   Conifer covers 50-75%  (mix confier)  OR
2)  Conifer cover 25-50% (mix deciduous)

A mix stand always have 3 species or species group. The 2 first indicate the dominance. The species translation rules for Qc says when there are 3 species, 1st = 51%, 2nd = 25% and 3rd = 24%. 

If we apply those percent, dominance would be over 75% (51% + 25%), which is not the definition from the province. I would suggest that when 3 species in Quebec , 1st = 35%, 2nd = 35% and 3rd = 30%. 

Or something like that. Do we agree?

**Comment by edwardsmarc** [comment]
I would guess `1st = 51%, 2nd = 25% and 3rd = 24%` was used to make sure 1st 2nd and 3rd were in order.

So maybe something like `1st = 37%, 2nd = 33% and 3rd = 30%`.

**Comment by MelinaHoule** [comment]
Percent were implemented in custom function qc_prg4_species_per_translation() with commit e7d97354f8253eee94751d4299d174eaba9899c9
