### ISSUE TITLE
Load remaining AB inventories

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#290]
Crown inventories are the priority.

**Comment by edwardsmarc** [comment]
@pedrogit - for the recently acquired AB29 dataset, there is a AVIPostInventoryCutblocks.shp file that we can treat as an 'update'. It contains cutblock polygons with attributes of harvest type and harvest year. 

How do we deal with this during loading? Should I give it it's own name (AB30), and then use the inventory_list to link it to the fri data it came with (AB29)?

Then for translation, since it only includes disturbance attributes should we just generate the DST and GEO tables for this dataset? Would the temporalization procedure take care of the polygons? The polygons do not line up with the existing FRI polygons.

**Comment by edwardsmarc** [comment]
Update:

Steps for translating depletion update will be as follows:
- Treat update as new dataset named AB30. Mention in inventory_list that it was received with AB29
- Don't both running a LYR or NFL translation because there won't be any rows to return
- Run the CAS table using the depletion update publication year as the PHOTO_YEAR (see #473 for reasoning) 
- Run the DST table
- Run the GEO table

**Comment by edwardsmarc** [comment]
All sh loading scripts complete

**Comment by edwardsmarc** [comment]
bash scripts needed

**Comment by pedrogit** [comment]
> bash scripts needed

If what was meant was "batch" instead of "bash", then this issue is replaced by #576 and should be closed.
