### ISSUE TITLE
Constraints - Assigning PRODUCTIVE_FOR when no source attribute exists

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#295]
Some inventories have a source attribute we can use to assign PRODUCTIVE_FOR (NB02, ON, NT, BC).

In cases where no source attribute exists (AB, NB01, NT, YT), how can we assign PRODUCTIVE_FOR?

**Comment by pedrogit** [comment]
NOT_APPLICABLE

**Comment by edwardsmarc** [comment]
I'll use NOT_APPLICABLE for now, but @MelinaHoule has mentioned that we need this attribute to be assigned for all inventories to facilitate queries on the final db. We can discuss when she is back.

**Comment by pedrogit** [comment]
1) Do we need want this attribute?

2) Do we want to derive this attribute from existing CASFRI attribute when it is not present?

3) What would be the rules to derive them?

**Comment by edwardsmarc** [comment]
Answer to 1. is Yes from the sponsor.

We need to set up a meeting to discuss 2 and 3 with SC when MH is back.

**Comment by edwardsmarc** [comment]
@edwardsmarc to do the following:
* Review existing FRIs for PRODUCTIVE_FOR and SITE_CLASS attributes.
  * Which have them?
  * How do they define/calculate them?
* For the non-forest values currently included in the PRODUCTIVE_FOR specs, what FRIs do these come from? Are they included in the NFL table?

**Comment by MelinaHoule** [comment]
I went over productive_for issue.  I cross checked documentation with the way we used it in CASFRI v4. Of course, there were some inconsistencies. I created frequency tables to highlight where and why productive_for was used. 

Not all inventories use productive_for. Many use default value "Productive_forest". 

Type "Potentially_productive" comes from us. It is never translated from the source. This type is inconsistent across inventories. 

The others are translated from the source. They are most of the time derived from the same column as NFL, but with information about height and crown_closure. That is why, I guess, they were put in LYR. Do we want to keep an entry in LYR to retain information about height and crown closure?

Please review the document before the meeting. 
[productive_for_exploration.pdf](https://github.com/edwardsmarc/CASFRI/files/4926458/productive_for_exploration.pdf)

**Comment by edwardsmarc** [comment]
Thanks @MelinaHoule this is great.

The following indicates whether the PRODUCTIVE_FOR attributes are also captured in out current NFL translations:
* BC - Alpine forest is currently translated into an NFL type in BC. We have an open issue (#347) discussing this because the specs do not include an alpine forest value for NFL. 
* SK-UTM - Source value CLEAR MUSKEG is translated to OPEN_MUSKEG, but source value TREED MUSKEG is not translated.
* MB - we haven't done this translation yet
* ON02 - Source values TREED MUSKEG and OPEN MUSKEG are both translated to OPEN_MUSKEG in the NFL table.
* NB - Source value BOG is translated to OPEN_MUSKEG. No source values representing shrubs are translated.
* NL - we haven't done this translation yet
* YT - source values 'Tall shrub', 'Tall shrub, open', 'Tall shrub, closed' are translated to TALL_SHRUB. Source value 'Low shrub' is translated to LOW_SHRUB.

**Comment by edwardsmarc** [comment]
The following is a list of inventories where we have SITE_CLASS information:

* AB
  * We copy the attribute TPR (Timber Productivity Rating) which can be 'Good', 'Medium', 'Fair' or 'Unproductive'. The manual states that values of 'Good', 'Medium' or 'Fair' are considered productive.
* NT
  * We copy the attribute 'Site class' which can be 'Very good', 'Good', 'Medium', 'Poor', 'Unproductive'.
* ON
  * We copy the attribute 'Overstory site class' which can be 'Best', 'Better', 'Good', 'Poor', 'Protection Forest'.
* YT
  * We copy the attribute 'site_class' which has values 'Low', 'Poor', 'Medium' and 'Good'.

The following is a list of source attribute versions of PRODUCTIVE_FOR:
* AB
  * Timber Productivity Rating - we use this for SITE_INDEX - *A timber productivity rating (TPR) is assigned when any of the tree species listed in Table 3-8 are or have been present on a site. TPR reflects tree growth response to environmental factors including soil, topography, climate, elevation and moisture. It indicates the potential timber productivity of a stand based on the height and bhage of the dominant and codominant trees of the leading species (first tree species listed in the polygon label). Timber productivity is determined using the TPR for one of the five major tree species.*
* ON
  * FORMOD - Can take values:
    * PF - Protection Forest - *Areas that may have adequate timber growth, but which contain features that pose a significant operational challenge or risk in terms of forest management and site protection. These areas have been designated as a reserve for the purpose of protecting a specific site or ecosystem and are excluded from forest operations.*
    * RP - Production Forest (Regular) - *Productive forest areas at various stages of growth and development, including areas that have been recently depleted (by harvest or natural causes) or renewed (by artificial or natural means), that are capable of producing adequate growth of timber to support harvesting on a sustained yield basis. These areas have no significant physical or biological limitations on the ability to practice forest management, but may include areas which pose an operational challenge in terms of harvest, access, protection, silviculture, or renewal (areas formerly called production forest reserves).*
* NB01
  * We have a rule from CAS04 that assigns PP in cases where there is no crown closure info or no height info. It also assigns PP when the polygon is non-forested and has a treatment code that is not CUT. CUT and forested polygons with crown closure and height are assigned PF.
* NB02
  * This uses a different rule based on the fst (Forest Stand Type) column which can have values of 1 (>70% merchantable), 2 (merchantable and unmerchantable) or 3 (<35m2/ha merchantable).
* SK UTM
  * Has attribut NP (Non-productive) listing non-productive codes.
* SK SFVI
  * Has a TYPE attribute with value FOR - *Land that is currently growing, or capable of supporting, a treed upland forest community. Moisture regimes are dry through very moist.*

**Comment by prvernier** [comment]
PRODUCTIVE_FOR

  - BC
    -  There's an attribute called **for_mgmt_land_base_ind** that could be used as a proxy for productive and non-productive forest. We used it for BC08 and it's described [here](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/data-management/standards/forest_management_land_base_definition.pdf).

**Comment by edwardsmarc** [comment]
Post meeting notes:

We agreed that the following information should be recorded somewhere when it is available:
* Any value describing an unproductive forested polygon. This is important for rows that could have height and crown closure information in a LYR row, but no species values (e.g. the photo interpreter declined to record the species because they decided it was unproductive and not worth their time). Examples are ALPINE_FOREST, TREED_MUSKEG, SCRUB_CONIFEROUS, SCRUB_DECIDUOUS. **Action Item - review inventories for other unproductive values (who will do this? Please make an issue)**.
* Any value that labels the polygon as productive for the purposes of forestry. Where available, we should copy these values as a record that the source jurisdiction considered this polygon to be part of their merchantable forest. **Action Item - review inventories for merchantable forest values.**

It is important to recognize that many source inventories group information into productive forest, unproductive forest, and non-forested. CASFRI however only groups information into forested or non-forested. It is important that we somehow represent the distinction between productive and unproductive forest.

We agreed that computing a derived CASFRI productivity class will be complex and potentially open to criticism. For now we will just focus on translating source values where they exist.

We will add the following attributes to the CASFRI schema in the LYR table:
* **UNPRODUCTIVE_CLASS** - Describes the assigned class for a LYR layer that is forested but not productive. Often included in source inventories as an 'unproductive' type. Possible values are (additional classes may be added after review) ALPINE FOREST, TREED_MUSKEG, SCRUB_CONIFEROUS, SCRUB_DECIDUOUS, UNKNOWN_VALUE.
  * UNKNOWN_VALUE would be assigned to all LYR polygons where we have no evidence that the layer is an unproductive class (i.e. UNKNOWN_VALUE is the default class).
  * Users wishing to query for all productive forested lands could extract all layers where `UNPRODUCTIVE_CLASS = UNKNOWN_VALUE`. With the caveat that some of these may actually be unproductive: we can only assign the values where they are available. 
* **PRODUCTIVE** (or LAND_BASE? I don't know the best name for this attribute) - Indicates the forestry land base value assigned by the source jurisdiction. For example BC assigns Y or N. ON assigns 'Production forest'. We recognize that not all inventories have this information, but even if it's only available for BC and ON, that's a lot of Canada. This attribute could be boolean.
  * Users wishing to query for all polygons designated as part of the jurisdictions forestry land base could do so using this attribute.
  * The specific definitions from the source inventories should be added to the CASFRI specs.

Other related attributes that we will keep are:
* **SITE_CLASS** - copies a site class value from the source where available. Possible values are UNPRODUCTIVE, POOR, MEDIUM, GOOD.
* **SITE_INDEX** (rename to SITE_PRODUCTIVITY_LEVEL?) - copies a site index from the source where available. Values range from 0-99.

Not all attributes will be available for all inventories. For example some inventories could have SITE_INDEX but no information on UNPRODUCTIVE_FOR or PRODUCTIVE. We can therefore imagine a query that combines CASFRI attributes to identify productive polygons:
`WHERE (PRODUCTIVE = TRUE) OR UNPRODUCTIVE_CLASS = UNKNOWN_VALUE AND SITE_CLASS != UNPRODUCTIVE`

**Comment by pedrogit** [comment]
- I would probably rename UNPRODUCTIVE_CLASS to UNPRODUCTIVE_TYPE. A class would be something that would have sub classes. It's the case in the new schema classification but not here.

- Seems to me there is no need for the PRODUCTIVE attribute. Productive stands should simply be coded as such in the UNPRODUCTIVE_CLASS attribute (this is very different from attributing a default value since in this case we have evidences to classify them as productive). Unless there are many types of PRODUCTIVE. But you mentioned that it should be boolean.

- I guess SITE_CLASS should be renamed SITE_PRODUCTIVITY_LEVEL and SITE_INDEX, SITE_PRODUCTIVITY_INDEX.

**Comment by prvernier** [comment]
Is there a need to rename SITE_CLASS and SITE_INDEX? Both are very common in forestry circles. Also, SITE_CLASS is not an ordinal attribute, so SITE_PRODUCTIVITY_LEVEL would be misleading.

**Comment by edwardsmarc** [comment]
In response to @pedrogit comment...
I agree with combining these two attributes into one, since if something is labelled as being in the merchantable land base it should never also be labelled as an unproductive type. However this leads us back full circle, we are almost just using PRODUCTIVE_FOR as it is in the specs :)

It also reintroduces the issue of coding productive values in an attribute named UNPRODUCTIVE. What if we name the attribute **PRODUCTIVITY_TYPE** and had values that are prefixed with either PRODUCTIVE or UNPRODUCTIVE, e.g.:
* UNPRODUCTIVE_ALPINE_FOREST
* UNPRODUCTIVE_TREED_MUSKEG
* UNPRODUCTIVE_SCRUB_CONIFEROUS
* UNPRODUCTIVE_SCRUB_DECIDUOUS
* PRODUCTIVE_FORESTED - i.e. Y in BC for_mgmt_land_base_ind and RP in ON FORMOD
* PRODUCTIVE_PROTECTED - i.e. PF in ON FORMOD
* UNKNOWN_VALUE

We'd need to do a review to see if there any other values to add.

**Comment by pedrogit** [comment]
I agree with both previous comments.

**Comment by pedrogit** [comment]
Thinking about it twice I really don't like the fact that we are trying to code two values (PRODUCTIVITY and PRODUCTIVE_TYPE) in one attribute. This is breaking one of our very basic principle that we generally blame other inventories for. 

So I would suggest:

- PRODUCTIVITY (PRODUCTIVE, UNPRODUCTIVE, POTENTIALLY_PRODUCTIVE, UNKNOWN_VALUE)

and 

- PRODUCTIVITY_RELATED_TYPE (ALPINE_FOREST, TREED_MUSKEG, SCRUB_CONIFEROUS, SCRUB_DECIDUOUS, FORESTED, PROTECTED, UNKNOWN_VALUE)

ALPINE_FOREST, TREED_MUSKEG, SCRUB_CONIFEROUS, SCRUB_DECIDUOUS would necessarily have PRODUCTIVITY=UNPRODUCTIVE and FORESTED and PROTECTED would necessarily have PRODUCTIVITY=PRODUCTIVE

PRODUCTIVITY_RELATED_TYPE could be simply be named PRODUCTIVITY_TYPE but I find that RELATED adds the fact that the two attributes are linked.

**Comment by edwardsmarc** [comment]
So PRODUCTIVITY_RELATED_TYPE would always be translated directly from available source data, otherwise it gets assigned UNKNOWN_VALUE. 

And PRODUCTIVITY would be derived directly from PRODUCTIVITY_RELATED_TYPE with the rules you describe. Rows with no source info would be UNKNOWN_VALUE for both attributes.

How would we assign POTENTIALLY_PRODUCTIVE? I would vote we drop this value. It is a subset of the UNKNOWN_VALUE rows but without developing a derived rule we can't assign anything as POTENTIALLY_PRODUCTIVE. For me it is a candidate for a plugin table.

**Comment by edwardsmarc** [comment]
Starting a list of unproductive types that do not fir into a current PRODUCTIVITY_TYPE class:

* ON POLYTYPE BSH - Brush and Alder - Areas covered with ‘non-commercial’ tree species or shrubs. These areas are normally associated with wetlands or water features, and must not be confused with productive forest areas of similar brush or bush cover which have developed as a result of forest management operations (e.g., areas that have been recently depleted or areas that are below silvicultural standards).

**Comment by edwardsmarc** [comment]
Done, constraints need to be checked. Leave open for MB and NL translations.

**Comment by edwardsmarc** [comment]
@pedrogit to check constraints pass

**Comment by pedrogit** [comment]
This is not checked by constraint 4.47 and 4.48 and they both pass. Closing.
