### ISSUE TITLE
Add OTHER (OT) value to all NFL types

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#301]
Currently only non_veg_anth has OT.

We should edit the specs so non_for_veg and nat_non_veg also have OT. This will allow all possible source nfl attributes to be assigned a value in casfri.

We might also want to consider revising the specs for each nfl attribute so OT does not have to be used very frequently. For example, SK UTM has Treed Muskeg which doesn't match our current Open Muskeg class so gets set to OT. We could add a Closed Muskeg class.

**Comment by pedrogit** [comment]
What's the difference between OTHER and NOT_IN_SET?

**Comment by edwardsmarc** [comment]
It's a good point. NOT_IN_SET might be sufficient. 

One example is SK01 where they use 0 for rows that don't have values (instead of null). They also have NFL values that don't fit into the CASFRI schema. They use a code system so code 3100 for example does not fit in the casfri schema. The zero values will be caught as NOT_IN_SET. 

Question is do we want to distinguish between 3100 and 0? Using OT for 3100 would indicate a valid source value that we don't have a category for.

**Comment by edwardsmarc** [comment]
Actually the solution for SK would be to catch the zero using tt_notMatchList() and report NULL_VALUE as the error code. Then the 3100 would be caught with NOT_IN_SET. 

I'll leave this issue open because we had discussed revising the NFL codes since their categories are arbitrary and based on a small number of inventories.

I'd be interested in making a list of all possible source NFL codes to see how many do not fit in the current schema.

**Comment by edwardsmarc** [comment]
Update for SK01: tt_notMatchList() is not strictly necessary because createMappingView() filters out zero rows anyway. I've left it in to indicate that zero's are actually NULLs in this inventory.

**Comment by pedrogit** [comment]
Can we close this?

**Comment by edwardsmarc** [comment]
I think we can close. Any discussions of revising the NFL code specs will be deferred to CASFRI 6.
