### ISSUE TITLE
Random rows selection changed in the NB01 LYR test table

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#306]
Problem with randomization?

See LYR table in commit: 1ff89522b8922dcecaa6e323a769c8ba548c45c2

**Comment by pedrogit** [comment]
The problem occurs in DST as well. 

Might be related to the way we load the table. If the final loaded table is not in the same order from one loading to the next, then the randomization would happen differently. Solution would be to sort the final table. Let's see...

**Comment by pedrogit** [comment]
Found that NB01 data were edited/changed when fixing #284.

This does not explain the change for NB02 however. Still searching.

**Comment by pedrogit** [comment]
Changes in NB02 random sampling were caused by the source data being edited at every load depending on a configuration variable. This will be changed to a flag file: see #308
