### ISSUE TITLE
Some enhancements to conversion files

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#31]
1) More explicit and more consistent variable names e.g "targetTable" instead of "trgtT", "schemaName" instead of "schema"
2) Define a local path for GDAL
3) Define prjFile not locally and from current folder
4) Remove some useless variable e.g. ogrTab
5) Make the target schema settable locally
6) Hardcode inventory name
7) Make local configuration file common for both FRI loading and translation files loading
8) Generalize overwrite parameter being setable from the configuration file
9) Make long comment on many lines for better reading
11) Replace unloading of variables by SETLOCAL and ENDLOCAL

**Comment by pedrogit** [comment]
Remains to apply the same recipe on the bash files.

**Comment by edwardsmarc** [comment]
@pedrogit I simplified the code for ab16. Everything is now done in one loop. If you like this approach, apply it to the batch file and close the issue.

**Comment by pedrogit** [comment]
Can we close this one?

**Comment by edwardsmarc** [comment]
The .bat for ab16 is out of sync with the .sh. I updated the .sh to do everything in a single loop. I just tried to apply the same approach to the .bat but it relies on setting a variable inside the loop which doesn't seem to be possible in a batch file. So we might have to have different loading approached for .bat and .sh in this case.
