### ISSUE TITLE
Include or drop ECO tables?

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#318]
#171 (new schema) proposed moving the ECO tables to a plugin table since only a small number of FRIs have wetland information. This would remove the currently empty ECO tables for most inventories.

We should also consider doing this for the current schema. Is wetland info required in casfri05? If yes, do we prefer the current approach or moving to a plugin table?

Steps to remove ECO tables from current schema:
* Delete ECO translation tables and associated custom helper functions
* Edit workflow sql code to remove ECO translations
* Remove ECO columns from attribute dependencies table
* Edit specs

Steps to add ECO translations as plugin tables:
* Include ECO tables only for FRIs that have wetland info. Add back the custom helper functions
* Add workflow code to run the translations and add the plugin table
* Write specs for plugin

**Comment by prvernier** [comment]
The wetlands attributes are of great interest to research groups like BAM but maybe not so much for NRCAN (we need to check). In appendix 15 of the original specifications document, John Cosco wrote detailed procedures for deriving wetland attributes from standard forest attributes for provinces/standards that did not have specific wetland information. So, it might be possible to implement them for all inventories but this would require a fair bit of time - and maybe best parked for the time being. If we leave the ECO tables empty or partially filled we are recognizing that these attributes belong to the core set of CAS attributes and that they will eventually be populated. Alternatively, setting them up as plugin tables would distinguish them as supplementary attributes, which could also be used for other specialized attributes in the future. Currently, I'm ambivalent about which route to take.

**Comment by edwardsmarc** [comment]
I'm leaning towards leaving them in and doing the translations for the inventories that we already have rules for. Then maybe if there's time we can work on populating other inventories.

**Comment by SteveCumming** [comment]
I am ambivalent about having ECO as a plug in table or a plugin table. I think it is important to retain the wetland classification as part of the CASFRI standard, especially as we have the rules, and they should be not that hard to implement...for those standards that do not include it.   Perhaps the .cas table could be enhanced, to indicate if there exists an .eco entry as I think we have discussed for other tables.

**Comment by edwardsmarc** [comment]
We agree to stick with the current tables and not pursue the plugin table as part of this project.

@prvernier - can you link to the rules you mention for deriving wetland codes in cases where they do not already exist? Are there any inventories we have already done that include wetland codes and need wetland translations added? So far we only have an ECO table for NB.

**Comment by prvernier** [comment]
I've extracted the relevant appendices and placed them in the "docs/specification/appendices/" folder on the CASFRI GitHub project website:

- Appendix14.xls (three worksheets related to wetlands)
- Appendix15.docx (Procedures for CAS wetland derivation i.e., when no dedicated attributes are available)
- Appendix15.md (started converting the Word version to markdown but the wobbly formatting of the original document makes this difficult)
- Appendix16.xls (worksheet related to ecosite attribute)

Appendix 15 seems to be the key information for deriving the wetland attributes, esp where no dedicated attributes exist e.g., BC, AB, SK.

**Comment by edwardsmarc** [comment]
@edwardsmarc to review which inventories have ECO info. Some inventories have rules but we haven't added them.

**Comment by pedrogit** [comment]
Issues #377 and #376 are related to this issue.

**Comment by edwardsmarc** [comment]
We previously agreed with our sponsor that we would only include wetland info if it exists in source datasets. Any kind of derived ECO table will be put on hold, and could possibly be implemented later as a an example of a plugin table.

Next step on this is for @edwardsmarc to review the inventories and record which ones we have wetland info for.

@MelinaHoule is already working on the ECO table for QC.

**Comment by edwardsmarc** [comment]
Most of this information is already gathered in appendix 14 from CASFRI 04. It also includes the translations to use when source attributes are available.

**Comment by edwardsmarc** [comment]
This issue is being transferred to @prvernier who will review appendix 14 and write the ECO translation tables.
