### ISSUE TITLE
What should STAND_STRUCTURE be for non-forest rows?

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#320]
Specs suggest S, M and C are used for forest layers.

What about polygons with only NFL info? Should they be S or an error code?

Currently we have cases where we are assigning stand structure by counting layers. If there is one layer we assign S, but this layer could be LYR or NFL info. We could easily change this so only LYR rows get stand structure values.

**Comment by edwardsmarc** [comment]
NOT_APPLICABLE

Update existing tables to only use forest layers for assigning stnad structure.

**Comment by edwardsmarc** [comment]
This is tricky for AVI. It assigns H and C stands using a stand structure attribute. We want to carry these through to CASFRI. However it also includes shrubs in layer counts so a two layered stand where one layer is shrub gets labelled M. In casfri we would label this S since the shrub is NFL.

Only solution I see here is a custom validation function to catch the following case and assign them NOT_APPLICABLE:
* Where overstory is NFL, and stand structure is not assigned to H.

And a custom translation function to assign the following cases:
* If H or C, copy source attribute to CASFRI.
* Then assign M to all cases where countOfNotNull({overstory species}, {understory species}) = 2
* Then assign S to all cases where countOfNotNull({overstory species}, {understory species}) = 1

**Comment by pedrogit** [comment]
What is assigned to the stand structure in AVI when there is only NFL info (e.g. lake)?

**Comment by pedrogit** [comment]
BTW the specs says that NOT_APPLICABLE is when "Target attribute not in source table". This does not cover this case. It should say "Target attribute not in source table or does not apply to this record".

**Comment by edwardsmarc** [comment]
AVI leaves the stand structure cell blank for any NFL or single layered stand. They only report C, H or M values and state in the manual that anything else is assumed to be S. So there is no way to differentiate single layered forested stands from NFL without looking at other attributes.
