### ISSUE TITLE
Many YT translated rows have the same NFL and LYR layer number for the same CAS_ID

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#329]
You can find them with this query:

```
SELECT lyr.cas_id, lyr.layer lyr_layer, nfl.layer nfl_layer
FROM casfri50.lyr_all lyr, casfri50.nfl_all nfl
WHERE lyr.cas_id = nfl.cas_id AND lyr.layer = nfl.layer;
```
There are 92130 of them...

(This query might take forever if you aven't created indexes on both tables. They are created at the end of workflow # 2)

**Comment by edwardsmarc** [comment]
Layer is hardcoded to 1 in LYR and NFL tables because there can only be one layer in YT. Every polygon is either forested or nfl. I think the issue here is that the view is not being filtered so empty rows are copied into the results table leading to duplication. Same issue as #325.

**Comment by edwardsmarc** [comment]
This should be fixed with the new ROW_TRANSLATION_RULE. Should only ever get one CASFRI row (LYR or NFL) per source row.

**Comment by edwardsmarc** [comment]
Fixed, query returns no lines for me.
