### ISSUE TITLE
Can vertical_complexity be used to infer complex stands in BC VRI?

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#333]
>  The subjective classification that describes the form of each tree layer as indicated by the relative uniformity of the height of the forest canopy as it appears on mid-scale aerial photographs. Vertical complexity is influenced by stand age, species (succession as it relates to shade tolerance) and degree and age of past disturbances. The tree height range is calculated as the total difference in height between the tallest and shortest visible dominant, co-dominant, and high intermediate trees. To most adequately represent the tree layer of interest, occasional occurrences of either very tall or very short trees should be ignored so that the vertical complexity indicated is for the majority of stems in the dominant, co-dominant, and highintermediate portion of each tree layer. Vertical complexity is a subjective classification that describes the form of each tree layer as indicated by the relative uniformity of the forest canopy as it appears on midscale aerial photographs.

> Codes Description
1 Very uniform
A very uniform canopy with less than 11% difference between the height of the leading species and the average tree layer height. Holes (or canopy gaps) are generally not visible in the canopy and there is usually no evidence on the photograph of recent disturbances affecting the form of the stand. Examples include plantations and young, immature stands of shade intolerant species.
2 Uniform
A uniform canopy with 11% - 20% difference between the height of the leading species and the average tree layer height. A few holes (or canopy gaps) may be visible in the canopy and there is usually little or no evidence on the photograph of recent disturbance affecting the form of the stand.
3 Moderately uniform
A moderately uniform canopy with 21% - 30% difference between the height of the leading species and the average tree layer height. Some holes (or canopy gaps) may be visible in the canopy and there may be evidence of past disturbance affecting the form of the stand. Stocking may be somewhat patchy or irregular. Examples include older spruce-balsam stands.
4 Non-uniform
A relatively non-uniform canopy with 31% - 40% difference between the height of the leading species and the average tree layer height. Holes (or canopy gaps) are often visible in the canopy (due to past
disturbance) and stocking is typically patchy or irregular.
5 Very non-uniform
A very non-uniform canopy with more than a 40% difference between the height of the leading species and the average tree layer height. Stocking is typically very patchy or irregular. Examples include disturbed dry belt Douglas-fir stands and decadent, coastal over-mature stands.

**Comment by sgautam-nrcan** [comment]
Hello,
Yes, the described methods in defining vertical complexity sounds very promising and can be implemented across other forest inventories. However, still there is tricky how to get average tree height for a stand within a polygon. Looking at VRI data from BC, I see this can be derived using either weighted tree height of height measurements in Layers (e.g., Layer 1 and Layer 2) or simple average.

**Comment by edwardsmarc** [comment]
@sgautam-nrcan - where is average height recorded? CASFRI has attributes for height in the LYR table, so every layer within the polygon would have a height value. However, there is no polygon-level height attribute in the CASFRI schema.

**Comment by sgautam-nrcan** [comment]
@edwardsmarc Yes, you are right there is not polygon level height but it seems that can be derived from the information available. For example, let's say a polygon has two layers (Layer 1 and Layer 2). So, we have two height values for each layer in that polygon. Then we can derive average height from these two layers (i.e., Average of Layer 1 and Layer 2). Later, the derived average height can be compared with Layer 1 and Layer 2 to understand vertical complexity.  However, this can be implemented to BC10.

**Comment by edwardsmarc** [comment]
@sgautam-nrcan - OK I understand your calculation.

I was wondering whether we could directly translate the vertical_complexity values from BC10 into the CASFRI stand_structure attribute. For example, could vertical_complexity codes of 4 ( Non-uniform) and 5 (Very non-uniform) be assumed to be Complex stand structure based on the CASFRI definition:

> Complex layered stands exhibit a high variation in tree heights. There is no single definitive forested layer as nearly all height classes (and frequently ages) are represented in the stand.

I am realising now though that our working stand_structure definition (specs will be updated to reflect this soon) only assigns Complex (or Horizontal) stand structure if it was labelled as such in the source data. Following that definition BC would only be assigned Single or Multi-layered stand structure in CASFRI since BC does not assign Horizontal or Complex stand structure in the source data.

My preference is therefore to close this issue and continue with the current translation rule that assigns S or M based on a count of the canopy layers.

**Comment by sgautam-nrcan** [comment]
@edwardsmarc 
You are right on "vertical_complexity codes of 4 ( Non-uniform) and 5 (Very non-uniform) be assumed to be Complex stand structure based on the CASFRI definition". I thought you were elaborating CASFRI definition but now I realized that you were mentioning the BC data dictionary. As this information is associated with BC forest inventory, we do not have to estimate. Sorry for creating this confusion.
Hence, I also assume vertical_complexity codes 4 and 5 to be Complex stand structure on the CASFRI definition.

**Comment by edwardsmarc** [comment]
Closing. We agreed that stand structure C and H will only be copied to the CASFRI if specified in the source data. BC stands will therefore only be S or M.
