### ISSUE TITLE
Check all height translations

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#336]
The CASFRI specs state this should be the average of dominant and co-dominant heights. So BC for example should be (proj_height_1 + proj_height_2) / 2.

Currently we are just copying the proj_height_1 value.

* Check with SC and JC if this is what was intended.
* Check if this applies to any other inventories.

**Comment by sgautam-nrcan** [comment]
In my opinion, if height_upper and height_lower can be translated accounting both proj_height_1 and proj_height_2 with their corresponding species abundance (i.e., species_pct_1 and species_pct_2) would be better than a simple average. The formula for this estimation would be: 
(proj_height_1 * species_pct_1/100) + (proj_height_2 * species_pct_2/100) + (proj_height_1 + proj_height_2)/2*(100 - species_pct_1 - species_pct_2)

**Comment by edwardsmarc** [comment]
I'm adding the height definitions from other inventories we have done here:

##### AB AVI and NT FVI

> Stand height is the average height of the dominant and codominant trees of the leading species.

##### BC VRI

> The average height, weighed by basal area, of the dominant, co-dominant, and high intermediate trees for the leading and second species of each tree layer identified.

##### NB NBI

> Dominant/Secondary layer average height in metres. (where dominant and secondary refer to layers 1 and 2)

##### ON FIM

> The overstorey height attribute contains the average height in meters of the dominant
> and co-dominant trees of the leading species in the stand (or in just the uppermost
> canopy layer if the stand canopy contains two or more distinct layers).

##### SK SFVI

> The average height of the dominant and co-dominant trees of the leading species in a layer.

##### YT YVI

> Average height, in metres, of the dominant and co-dominant trees of the leading species.

**Comment by edwardsmarc** [comment]
Based on this BC is the only case where we would need a calculation. It's not clear to me what proj_height_1 and proj_height_2 are representing. The data dictionary states they are for different 'layers' but they are repeated in both VEG_COMP_LYR_L1_POLY and VEG_COMP_LYR_L2_POLY.

We consider VEG_COMP_LYR_L1_POLY and VEG_COMP_LYR_L2_POLY to be the two LAYERS.

So are there 'layers' within the LAYERS?

**Comment by sgautam-nrcan** [comment]
I have not looked into other jurisdictions' data yet. However, from the definition you provided in this thread, it seems that they have estimated height based on dominant and codominant tree species. However, in the case of BC it was provided at the dominant and co-dominant species level (if more than one species in a polygon) for layers (VEG_COMP_LYR_L1_POLY and VEG_COMP_LYR_L2_POLY to be the two LAYERS). 
Yes, somehow it's confusing. Once we estimate using the method we are discussing we will have one tree height for each layer.

**Comment by edwardsmarc** [comment]
We agree that @sgautam-nrcan 's formula for weighted average height should be used in BC. This should be documented in the specs. The height definitions for all other inventories should be checked and any that deviate from the CASFRI definition should be documented.

**Comment by edwardsmarc** [comment]
We will need a weighted average helper function that works when both one or two species heights are available.

@sgautam-nrcan 's formula above should do the trick, or @prvernier provided the formula below.

((proj_height_1 * (species_pct_1/100)) / ((species_pct_1 + species_pct_2)/100)) +
((proj_height_2 * (species_pct_2/100)) / ((species_pct_1 + species_pct_2)/100))

This formula appears to work when the species percentages don't sum to 100, which should never be the case. If we use @sgautam-nrcan 's formula we should also validate that species percentages sum to 100.

**Comment by sgautam-nrcan** [comment]
In many cases, species_pct_1 and species_pct_2 do not add up to 100 because there are more than 2 species in forests but not recorded about their abundance.
The revised formula also does the same as I proposed above.

**Comment by edwardsmarc** [comment]
I'm updating this helper function to account foe cases where all 4 attributes are not available. Currently all null height or percent cover values are set to zero, but that does not produce the desired behaviour.

If either of the percent cover values are null, set them to zero. This will essentially ignore that species height value. This should only occur for species 2 where species 1 is 100%.

The more common error is where there are two percent values but only one height value. In this case we should not set the height value to zero, but we should set the percent value to zero, essentially dropping any null height values from the calculation.
