### ISSUE TITLE
Some DIST_YEAR_1 are invalid

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#337]
"NB01-xxxxxxxxxFOREST-xxxxxxxxxx-0000683016-0841861" have 6 and "NT02-xxxxxxNT_FORCOV-xxxxxxxxx9-0009013617-0073244" have 1

Also: many disturbance years are in the 1800s in NB01, NT02 and ON02 (5751 of them). Is is a translation error or are these the true values?

Specifications say DIST_YEAR_X should be greater than 1900.

You can find them all with:

```
SELECT cas_id, dist_year_1
FROM casfri50.dst_all
WHERE dist_year_1 > 0 AND dist_year_1 < 1900
ORDER BY dist_year_1;
```

**Comment by edwardsmarc** [comment]
Also many cases with year = 0.

**Comment by pedrogit** [comment]
Make sure constraint 2.22 passes in 01_addConstraint.sql on the final database before closing this issue.

**Comment by edwardsmarc** [comment]
These are all valid values based on the source manuals and valid translations. 

So the question is whether we think we should report an error code for disturbances in the 1800s. I would say no given that they are valid based on the source inventory specs. It's risky for us to try and guess what is and is not an error. I don't think we can assume anything in the 1800s is an error. Seems unlikely ON would have 5000 errors of this type?

So, we need to change the CASFRI specs to make these values valid. ON requires their years to be 4-digit integers. NT requires an int between 1-9999. I say we use 1000-2020 to match ORIGIN_UPPER and ORIGIN_LOWER.
