### ISSUE TITLE
Many rows have NUM_OF_LAYERS = 0

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#339]
You can see the numbers with this query:

SELECT left(cas_id, 4) inv, count(*) nb
FROM casfri50.cas_all
WHERE num_of_layers = 0
GROUP BY left(cas_id, 4);

And analyse the reasons with the new flat table if you have it:

SELECT cas_id, num_of_layers, *
FROM casfri50_flat.cas_flat_all_layers_same_row
WHERE num_of_layers = 0

Seems to me that all row should at least represent a LYR, a NFL or a DST layer. What are they otherwise?

More analysis to come...

**Comment by pedrogit** [comment]
Many BC rows are explained by #325. Many non true DST row are translated for nothing.

**Comment by edwardsmarc** [comment]
We now have a constraint that checks this. Closing.
