### ISSUE TITLE
Conversion files are not working with GDAL version 2.1.2

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#34]

**Comment by edwardsmarc** [comment]
Tested conversion with GDAL v1.11.4, v2.1.3 and newest version v2.4.0.
* Coverage files don't load in 2.1.3. But they do load in 1.11.4 and 2.4.0. I think this might a bug in 2.1.3 (https://gis.stackexchange.com/questions/253103/trying-to-get-gdal-2-x-to-work-but-ogrinfo-reports-error-3-and-error-4-and-f?rq=1).
* SQL queries work in 2.1.3 after removing single quotes around ogr table names. Haven't found a way to use ogr table names with spaces as required in NB01. Documentation suggests double quotes for identifiers but this hasn't worked for me yet (https://gdal.org/ogr_sql.html).
* SQL queries return new errors in 2.4.0, more investigation needed to figure out whats wrong.

**Comment by kdarndt** [comment]
Using bc09 script, simply removing quotes around ogr table names (like for 2.1.3 specified above) appears to work for GDAL 2.4.1.

Perhaps simply standardize on a GDAL version (hopefully a newer version) and write the scripts to that?

**Comment by edwardsmarc** [comment]
I've been using v1.11.4 to match with what Brian said he was using at the start of the project. Is it a priority to move to v2?

If not we can probably close this issue.

**Comment by kdarndt** [comment]
I wouldn't say a priority.  But I also don't think we'll be sticking with 1.11.4 since that's pretty old.  If you don't have time to deliver with it working on v2 or v3, we'll probably just end up modifying the conversion files ourselves.  Can you leave it open but reduce priority?

**Comment by pedrogit** [comment]
Reopening as there is still a problem with ON02. Only now 3600369 rows are imported when there should be 3629072.

**Comment by pedrogit** [comment]
GDAL 3.1.4 is able to load one extra row (polyid=40061)
