### ISSUE TITLE
If NUM_OF_LAYERS = 0, catch and return UNKNOWN

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#340]
Many rows have disturbance info but no LYR or NFL info. These cases have NUM_OF_LAYERS = 0.

Proposal is to catch these cases with a validation rule and return UNKNOWN.

**Comment by pedrogit** [comment]
Make sure constraint 1.15 and 1.17 pass in 01_addConstraint.sql on the final database before closing this issue.

**Comment by edwardsmarc** [comment]
Done, constraints need to be checked.

**Comment by edwardsmarc** [comment]
Passes. Closing
