### ISSUE TITLE
Adjust workflow SQL to allow loading an individual inventory

### ISSUE THREAD

**Issue by kdarndt** [edwardsmarc/CASFRI#342]
When running the SQL scripts in the workflow/02_produceCASFRI folder, it is currently an all-or-nothing approach.

It would be great if it were possible to run individual inventories (ie: only BC10) without having to comment-out or run others.
The workflow may end up being scripted or run programmatically in the NFIS environment.

Not a high-priority issue as once CASFRI is delivered, it will be easy to reorganize for our own purposes.  But it would make it slightly easier to test individual inventories before then.

**Comment by pedrogit** [comment]
The only way I see we could achieve this is by creating a new set of scripts similar to the ones in de devel folder. One of them would have to create the table though and would have to be launched first. We would rather need an "init" script that would create the tables to be populated by following scripts.

We could also have them create separate final tables (6 per inventory). That would help debugging as we would not have to process the whole database to get something final.

Any other idea?

**Comment by kdarndt** [comment]
I think it makes sense to create the tables first (your "init" script).  The schema is defined in the data dictionary, so it should be created based on the Data Dictionary definitions -- rather than the columns specified in the first translation table.  If the translation table references columns not in the data dictionary, it should be an error then (instead of blindly creating the table with extra columns).  
 -- Hopefully I understood the current process correctly.

For orchestration, you could have a simple shell script that takes a parameter to decide which SQL to run (ie: BC09, BC08, BC, ALL, etc).  It could drop all constraints prior to the load (to improve speed) and re-create them after (ie: your setConstraints script).

**Comment by pedrogit** [comment]
There are now two different ways to generate the final CASFRI database:

- The first is by CASFRI table (02_perCASTable). Useful if you have all inventories supported by the project and you are generating the database from scratch. All scripts in 02_perCASTable can be executed concurrently as multiple processes.
- The other is by inventory (02_perInventory). Useful if you do not have all inventories supported by the project or if you want to regenerate only a selected inventory after fixing a bug. For some reasons these scripts lock the tables and even if you execute them concurently, they will wait that the preceding script finishes before executing.

Additional constraints, indexes and upcoming additional checks in 03_ConstraintsChecksAndIndexes must be run last.

**Comment by pedrogit** [comment]
I created a new issue (#351) for a proposed function that would take an inventory ID as parameter to replace the numerous scripts in 02_perInventory.
