### ISSUE TITLE
Many inventories replace GDAL generated ogc_fid with a PostgreSQL generated ogc_fid

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#344]
ogc_fid is used a the only common primary key for all inventories. It is used by TT_CreateMappingView() to generate repeatable random selections of rows. ogc_fid has to be associated with the same source record from one load into the database to the other. It's the case when it is generated by GDAL but generally not the case when it is generated by PostgreSQL (probably because PostgreSQL does not garantee same order on two SELECT statement not explicitly defining and ORDER BY).

BC10, NT02, QC03 conversion scripts delegate the assignment of ogc_fid to PostgreSQL breaking the translation tests.

One thing that puzzle me though is that NT02 is part of the test and we never had problem with it. Investigating...

**Comment by pedrogit** [comment]
One test to determine if two loading end up with the same ordering is:

```
SELECT ogc_fid, polygon_id
FROM rawfri.bc10
WHERE ogc_fid = 10000;
```

polygon_id should be equal to 63 in all tested database.

Works for me in my two databases.

**Comment by edwardsmarc** [comment]
I get 63 too.
