### ISSUE TITLE
Some SPECIES_X translations produce TRANSLATION_ERROR

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#346]
Two examples are "ON02-xxxxxxxxxQPP_2D-xxxxxxxxxx-0059535115-2752989" and "ON02-xxxxxxHF_601_2D-xxxxxxxxxx-172905450--1559309"

**Comment by pedrogit** [comment]
Same for SPECIES_PER_X

**Comment by pedrogit** [comment]
Make sure constraints 4.42, 4.44, 4.47, 4.52, 4.53, 4.54, 4.55 and 4.56 pass in 01_addConstraint.sql on the final database before closing this issue.

**Comment by pedrogit** [comment]
Constraints 4.52, 4.53, 4,54, 4,55 and 4.56 are now 4.56, 4.57, 4.58, 4.59 and 4.60 and they all pass.

Remains 4.42, 4.44 and 4.47 which are now 4.46, 4.48 and 4.51, were fixed and should pass next time.

**Comment by pedrogit** [comment]
4.46 passed.

Remains 4.48 and 4.51.

"ON02-xxxxxxHF_601_2D-xxxxxxxxxx-172905450--1559309" still produce an error.

**Comment by pedrogit** [comment]
This still produce a translation error:

SELECT species, TT_fim_species_translation(species, '6', 'translation', 'species_code_mapping', 'on_species_codes', 'casfri_species_codes')
FROM rawfri.on02_l1_to_on_l1_map_lyr
WHERE ogc_fid = 1674486

TT_fim_species_code() should not rely on fixed width of species/percent groups of characters. Some species and some percent are 3 characters long. It should use the space separator and get the left and right parts and determine which one is which.

**Comment by pedrogit** [comment]
Fix pushed. Still have to check constraint 4.51.

**Comment by edwardsmarc** [comment]
4.51 passes. Closing.
