### ISSUE TITLE
Many NON_FOR_VEG translated codes not in the specs

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#347]

**Comment by pedrogit** [comment]
AF, CL, OT, SC and SO can be found in the final database but not in the specs.

**Comment by pedrogit** [comment]
- AF produced by BC08 and BC10
- CL produced by NB02
- OT produced by SK01
- SC and SO produced by AB06

**Comment by pedrogit** [comment]
Make sure constraints 5.22 pass in 01_addConstraint.sql on the final database before closing this issue.

**Comment by pedrogit** [comment]
OT was fixed by addind OTHER to the specification.

SC and SO are OPEN_SHRUB and CLOSED_SHRUB. How do they distinguish from TALL_SHRUB and LOW_SHRUB? Please provide a clear definition.

AF is ALPINE FOREST. Any definition?

Remain CL... No meaning. No definition. Should it part of the spec or translated to something else?

**Comment by edwardsmarc** [comment]
Tall/Low indicates height, closed/open indicates density.

From the AVI manual:
CLOSED_SHRUB - Closed shrub (crowns of most shrubs interlocking) 
OPEN_SHRUB - Open shrub (crowns of most shrubs not touching each other)

The VRI data dictionary doesn't define AF. @prvernier is this definition in any of the other documentation?

**Comment by prvernier** [comment]
AF is Alpine Forest (with species etc.) and is one of the permitted values for the source attribute non_forest_descriptor_code that we use to populate NON_FOR_VEG.

**Comment by edwardsmarc** [comment]
Is there any info on what an Alpine Forest actually is? Elevation, density etc?

**Comment by prvernier** [comment]
The correct attribute that we used was "non_productive_descriptor_cd" not "non_forest_descriptor_code" that I mentioned above. This attribute refers to land that is "incapable of supporting commercial forests". It's part of the older FIP standard which has been replaced by VRI. So, it's only in there to support the transition. The guide doesn't give additional information on AF or any of the other classes - at least that I can find so far.

**Comment by pedrogit** [comment]
NON_FOR_VEG is still translated to CL somehow.

What do we do with ALPINE FOREST? If we keep it we need a proper definition for the specs.

Check constraint 5.24 before closing this issue.

**Comment by edwardsmarc** [comment]
CL is translated from NB source values AQ and 415.
AQ and 415 are - "Aquaculture -saltwater or freshwater areas used for commercial fish-farming".

@prvernier what do you think these should be translated to? NON_FOR_ANTH class OTHER?

For AF, all but one row in both bc08 and bc10 that are labelled AF, also have crown closure and species info. So I would say the the alpine forest info is captured in the LYR table and adding it to NFL would duplicate this info. I would propose we drop AF from the NFL translation. What do others think?

**Comment by edwardsmarc** [comment]
I also just found this for SK01 NON_FOR_ANTH: mapText(np, {3700,9000,4000}, {'OT','OT','CL'})

3700- CLEARING
9000- NOT TYPED
4000- PASTURE LAND

**Comment by edwardsmarc** [comment]
Summary of outstanding issues:

* @pedrogit has suggested we change LOW_SHRUB and TALL_SHRUB to either LOW_SHRUB and HIGH_SHRUB, or SHORT_SHRUB and TALL_SHRUB.
* ALPINE_FOREST - should this be translated as a PRODUCTIVE_FOR value, or an NFL value, or not translated at all since it is captured in the LYR table? If we add this as an NFL, we will need to add it to the specs.
* Should we add CLOSED_SHRUB and OPEN_SHRUB to the specs? If no, what should we translate CLOSED_SHRUB and OPEN_SHRUB to in AB?

**Comment by prvernier** [comment]
PV comments:

- shrub issue: some inventories use Shrub Low and Shrub Tall (e.g., BC, SK), so may be a forestry term
- alpine forest issue: we could add this to the productive_for discussion on Wednesday
- closed and open shrub issue: according to the specs, both should be translated to either LOW_SHRUB or TALL_SHRUB using the height attribute (SL <= 2m; ST >= 2m).

**Comment by edwardsmarc** [comment]
AB does have an nfl height attribute so I'll make an issue for translating open and closed shrub.

Alpine forest and Shrub Low/Tall will be discussed on Wednesday.

**Comment by edwardsmarc** [comment]
* AB shrub issue is moved to #415 
* We agreed at the meeting that ALPINE_FOREST should not be translated as an NFL because it describes a non-productive forest type.

* Remaining question is if we want to change the names of LOW_SHRUB and TALL_SHRUB? If these are standard forestry terms I'm happy to leave them as they are.

**Comment by edwardsmarc** [comment]
Closing and leaving LOW_SHRUB and TALL_SHRUB as they are.
