### ISSUE TITLE
load_bc10.sh specifies different attribute names than what is posted on DataBC for 2018 inventory

### ISSUE THREAD

**Issue by kdarndt** [edwardsmarc/CASFRI#349]
The conversion script "load_bc10.sh" specifies attribute names that were in a version of BC10 downloaded from an FTP site.

It appears that the attribute names may have changed slightly since then.  For example, the version of BC10 (2018 inventory) that can be downloaded from DataBC uses GEOMETRY_LEN instead of GEOMETRY_LENGTH for the dead layer (and possibly the other layers too -- I have not tested those).

I have also not tested the other attributes.  There may have been other adjustments.

See: https://catalogue.data.gov.bc.ca/dataset/vri-historical-vegetation-resource-inventory-2002-2018-/resource/a1928936-3dd4-4189-8c62-ca558574dbba

I think the script should be adjusted to align with the version posted on DataBC.

**Comment by pedrogit** [comment]
So I guess we should download the online one and replace BC10 with it. @prvernier @edwardsmarc any comment on this?

**Comment by edwardsmarc** [comment]
I agree on using the version available online. 

We should update the inventory_list_cas05.csv before closing this issue.

**Comment by pedrogit** [comment]
Forgot to update  inventory_list_cas05.csv...
