### ISSUE TITLE
SK SFVI disturbance codes - source values that are not in documentation

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#356]
Values - SN, S, W, C, B appear in SK02 but not in sfvi specs.

Can we assume SN is snow, W is windfall, C is cutblock and B is burn?

Or should we only translate whats in the source documentation?

**Comment by prvernier** [comment]
I don't think SN is snow since it's a disturbance code. W, C, and B are probably WI (windthrow), CO (cutover) and BO (burnover) but I don't think we should make that assumption. I would suggest we flag them with the proper error code.

**Comment by edwardsmarc** [comment]
Missed some codes
