### ISSUE TITLE
ON FIM species code functions do not catch all cases

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#361]
Some codes have only 1 space between the species and percent values. Most have 2.

This violates the assumption that each species - percent code has a length of 6.

Proposed fix - remove spaces from strings and assume length of 4 for each species - percent code.

**Comment by edwardsmarc** [comment]
Proposed fix wouldn't work as cases with 100 would have a length of 5 whereas others would have length 4.

The code causing the error only appears to occur once so we should just catch it during validation. Question is why it isn't already caught. Still investigating...

**Comment by pedrogit** [comment]
Regular expression?

**Comment by edwardsmarc** [comment]
Update: the invalid code is caught during validation when using the most recent version of the engine.

We could switch the function to use regular expressions, this would take some time as there are three function that would need to be changed. 

There are only 6 values in ON02 with invalid codes. I don't think it's worth the time to update the function to catch these 6 cases. I'd rather just return error codes since the codes are in fact invalid.
