### ISSUE TITLE
NS03 Attributes requiring custom functions

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#367]
Two attributes require a custom function.

### Site class

SITE_CLASS requires two source attributes (site_sw and site_hw); concatenating them does not guarantee unique combinations:

SITE_CLASS: mapText({site_sw}, {0,1,2,3,4,5,6,7,8,9,10,11,12,13}, {'P','P','P','P','P','M','M','M','M','M','G','G','G','G'})
SITE_CLASS: mapText({site_hw}, {0,1,2,3,4,5}, {'P','P','M','M','G','G'})

### Species (layer 2)

SPECIES_1, SPECIES_PER_1, SPECIES_2, and SPECIES_PER_2 are created from one source attribute (ss_species):

SPECIES_1: mapText({sp1}, {'S','SH','HS','H'}, {'Soft unkn','Soft unkn','Hard unkn','Hard unkn'})
SPECIES_PER_1: mapText({ss_species}, {'S','SH','HS','H'}, {'85','60','40','15'})
SPECIES_2: mapText({ss_species}, {'S','SH','HS','H'}, {'Hard unkn','Hard unkn','Soft unkn','Soft unkn'})
SPECIES_PER_2: mapText({ss_species}, {'S','SH','HS','H'}, {'15','40','60','85'})

**Comment by edwardsmarc** [comment]
For SITE_CLASS we can use tt_matchList and tt_mapText. The presence of zero's for site_hw and site_sw means that concatenation does result in unique values:

`SELECT site_sw, site_hw, CONCAT(site_sw, site_hw) FROM rawfri.ns03 GROUP BY site_sw, site_hw`

**Comment by edwardsmarc** [comment]
No custom function needed for species or species_per.

Proposed solution for species is to add lookup table mapping for species 1 and species 2. This allows different values to be returned depending on the species being translated for layer 2.

For species_per, we can use mapInt and just have different return values for the layer 2 values for species 1 and species 2.

I changed the layer 2 translations using ss_species to the following, @prvernier  can you verify these:

For SPECIES_1
S becomes 'Soft unkn' with percent 85.
SH becomes 'Soft unkn' with percent 60.
HS becomes 'Hard unkn' with percent 60.
H becomes 'Hard unkn' with percent 85.

For SPECIES_2
S becomes 'Hard unkn' with percent 15.
SH becomes 'Hard unkn' with percent 40.
HS becomes 'Soft unkn' with percent 40.
H becomes 'Soft unkn' with percent 15.

**Comment by edwardsmarc** [comment]
I also added some mappings for crown closure and height in the NFL table.

@prvernier can you verify my mappings based on the FORNON table in the manual.
