### ISSUE TITLE
WET_LOCAL_MOD is sometimes translated to 'B' which is not a valid CASFRI value

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#377]
TT_nbi01_wetland_code() put 'B' in fourth position of the produced string under some conditions:

           WHEN wc='BO' AND vt='EV' AND im='BP' THEN 'BO-B'
           WHEN wc='FE' AND vt='EV' AND im='BP' THEN 'FO-B'
           WHEN wc='BO' AND vt='AW' AND im='BP' THEN 'BT-B'
           WHEN wc='BO' AND vt='OV' AND im='BP' THEN 'OO-B'
           WHEN wc='FW' AND im='BP' THEN 'OF-B'

The fourth position is then used by nbi01_wetland_translation(wc, vt, im, 4) in the translation table to produce WET_LOCAL_MOD.

Either 'B' is a valid value for WET_LOCAL_MOD and it should be added to the specification or it is not a valid value and TT_nbi01_wetland_code() should be modified.

**Comment by edwardsmarc** [comment]
This concerns the source value BP for attribute im which is Beaver Pond.

We don't currently have a WET_LOCAL_MOD value for this.

I don't have a problem with adding this to the CASFRI specs. Do we know where the other WET_LOCAL_MOD values came from? Are they from a specific inventory? Maybe @MelinaHoule knows?

**Comment by edwardsmarc** [comment]
Related to #359

**Comment by pedrogit** [comment]
Make sure 01_addConstraints.csl test 3.13 pass before closing this issue.

**Comment by pedrogit** [comment]
B is now translated to TRANSLATION_ERROR.  Still to be fixed.
