### ISSUE TITLE
Create a test for the translation files with a sampling of the inventories

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#38]

**Comment by prvernier** [comment]
The goal is to generate a subset of the BC inventory for testing prior to testing the whole inventory.

Option 1 - Generate a random subset of the BC inventory as needed i.e., in the workflow file.

SELECT * INTO rawfri.bc08_rnd200k FROM rawfri.bc08 ORDER BY random() LIMIT 200000;
One problem is it has to regenerate the dandiom value for each row every time you want a new sample.
a way to avoid this is to make the random number part of the table and index it.
Then you can generate any sample table very quickly with a WHERE randomColumn<200 for example
or with ORDER BY randomColum LIMIT 200, but still the ordering will not be that fast.
  - The advantage is that over time, multiple random samples would be tested.
  - The disadvantage is the time to generate the sample and replication would not be possible without a random number seed (replication is useful to test if an error has be resolved, for example)

Option 2. Generate a random subset of BC inventory once and reuse it

SELECT * INTO rawfri.bc08_rnd200k FROM rawfri.bc08 ORDER BY random() LIMIT 200000;
The advantage is that this is done once and the same data is available allowing replication.
The disadvantage is that this approach may miss exceptions that are not in the random subset.

**Comment by pedrogit** [comment]
https://stackoverflow.com/questions/8674718/best-way-to-select-random-rows-postgresql

**Comment by edwardsmarc** [comment]
Here's a method for option 2. It makes a random number table that can be re-used for different tests. It took 4:38 mins for 1000 rows, and 7:55 mins for 200,000. The value 4677411 is the total number of rows in the BC FRI.

-- DROP TABLE IF EXISTS random_bc;
CREATE TABLE random_bc AS
SELECT random_num FROM generate_series(1,4677411) AS random_num ORDER BY random();
ALTER TABLE random_bc ADD COLUMN ogc_fid SERIAL PRIMARY KEY;

-- DROP TABLE IF EXISTS rawfri.bc08_test;
CREATE TABLE rawfri.bc08_test AS
SELECT * FROM random_bc JOIN rawfri.bc08 USING (ogc_fid) WHERE random_num < 200001;

**Comment by pedrogit** [comment]
What if you index random_num and ogc_fid in both tables?

CREATE INDEX idx_random_bc_random_num ON random_bc(random_num);
CREATE INDEX idx_random_bc_ogc_fid ON random_bc(ogc_fid);
CREATE INDEX idx_rawfri_bc08_ON rawfri.bc08(ogc_fid);

**Comment by edwardsmarc** [comment]
Indexing made it slower?

I don't know how to add the values directly. I tried joining the random numbers table to bc08, its been running for 2 hours!

**Comment by edwardsmarc** [comment]
Adding directly to BC08 should be possible with:

ALTER TABLE rawfri.bc08 ADD COLUMN random_id int;
UPDATE rawfri.bc08
SET random_id = random_num
FROM (SELECT random_num FROM generate_series(1,4677411) AS random_num ORDER BY random()) AS g;

However it takes too long. Currently at 1.5 hrs for me.
My preference is to use the solution I posted above. It also has the advantage that we could all be testing the same tables since we can just copy the random number table to each of our databases.

**Comment by edwardsmarc** [comment]
This issue replaced by #70
