### ISSUE TITLE
Many species code are missing a mapping in species_code_mapping.csv

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#381]
In BC:

- DG, SA, SXB, SXE

To be completed...

**Comment by MelinaHoule** [comment]
Species list coe for BC is found here:

https://www.for.gov.bc.ca/hfp/publications/00026/fs708-14-appendix_d.htm#ad_02

DG: green/sitka alder
SA: norway spruce
SXB: sprice hybrid white x black
SXE: spruce hybrid engelmann x sitka

engelmann x sitka
--




engelmann x sitka
--

**Comment by MelinaHoule** [comment]
Species code were added. Close with commit d8d7daae339502528d04a59626a0d3646fcd27f6
