### ISSUE TITLE
Add OT to all three NFL attributes

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#383]
* NON_FOR_ANTH already has 'OT'
* Update specs for NON_FOR_VEG and NAT_NON_VEG
* Translate 'WA' (Water -unspecified body of water) from the NB waterbody source attribute to NAT_NON_VEG 'OT'.
* Translate SK_UTM's NP attribute value 3900 (NON PRODUCTIVE BURN-OVER) to NAT_NON_VEG 'OT'.

**Comment by pedrogit** [comment]
This is a duplicate of #359 and is all done already. Closing...
