### ISSUE TITLE
PE01 Inventory - custom function needed for countOfNotNull()

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#384]
The source attribute LANDTYPE is used to create the following CASFRI attributes (note that not all LANDTYPE values are used):

nat_non_veg
fri = {'SO','SD','WW','FL'}
cas = {'SL','SA','LA','FL'}

non_for_anth
fri = {'CL','WF','PL','RN','RD','RR','AG','EP','UR'}
cas = {'OT','OT','FA','FA','FA','FA','CL','BP','SE'}

non_for_veg
fri = {'AL','BO'}
cas = {'ST','OM'}

The source attribute ORG_HIST is used to create the DIST_TYPE_1 attribute (note that not all ORG_HIST values are used):

dist_type_1
fri = {'BR','CC','WF','FL','DI','EP','OF','HR','RN','SD','SY','UR','SW','E', 'PN','TH','RC','PC','ST'}
cas = {'BU','CO','WF','FL','DI','OT','OT','OT','OT','OT','OT','OT','OT','PN','SI','SI','PC','PC','PC'}

**Comment by edwardsmarc** [comment]
Full translation complete with no errors.
