### ISSUE TITLE
Two disturbances should be translated from PE01

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#385]
Very often two two characters disturbance codes are concatenated together. e.g. "SWPC". I guess the first one (SW) should be translated to DIST_TYPE_1 using mapSubstringText(dist_code_1, 1, 2, {...}, {...}, 'TRUE') and the second one (PC) should be translated to DIST_TYPE_2 using mapSubstringText(dist_code_1, 3, 2, {...}, {...}, 'TRUE')

**Comment by edwardsmarc** [comment]
* Mappings need to reflect the substring, not the full string.
* Validation needs to check the substring, not the full string.
* See the engine github readMe for an explanation of how the substring functions work.

Changes needed:
1. Change matchList() validation rule to:
`matchListSubstring(dist_type_1, 1, 2, {'BR','CC','DI','EP','FL','HR','OF','PC','PN','RN','SD','ST','SY','TH','SW','UR','WF'})`
and
`matchListSubstring(dist_type_2, 3, 2, {'BR','CC','DI','EP','FL','HR','OF','PC','PN','RN','SD','ST','SY','TH','SW','UR','WF'})`

2. Change mapTextSubstring() translation rule to:
`mapSubstringText(dist_type_1, 1, 2,  {'BR','CC','DI','EP','FL','HR','OF','PC','PN','RN','SD','ST','SY','TH','SW','UR','WF'}, {'BURN','CUT','DISEASE','OTHER','FLOOD','OTHER','OTHER','PARTIAL_CUT','SILVICULTURE_TREATMENT','OTHER','OTHER','PARTIAL_CUT','OTHER','SILVICULTURE_TREATMENT','OTHER','OTHER','WINDFALL'})` 
and
`mapSubstringText(dist_type_2, 3, 2,  {'BR','CC','DI','EP','FL','HR','OF','PC','PN','RN','SD','ST','SY','TH','SW','UR','WF'}, {'BURN','CUT','DISEASE','OTHER','FLOOD','OTHER','OTHER','PARTIAL_CUT','SILVICULTURE_TREATMENT','OTHER','OTHER','PARTIAL_CUT','OTHER','SILVICULTURE_TREATMENT','OTHER','OTHER','WINDFALL'})` 

3. Add meaningful description:
`Takes substring of characters 1 and 2. Validates substring and maps to CASFRI disturbance type.`
and 
`Takes substring of characters 3 and 4. Validates substring and maps to CASFRI disturbance type.`
