### ISSUE TITLE
One DIST_TYPE_1 value is translated to TRANSLATION_ERROR in AB

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#386]
AB16-xxxxxxxxxCANFOR-xT063R01M6-0000080567-0030689

**Comment by edwardsmarc** [comment]
The row in question has a source value of 'UK' which is included in the mapText call. Not clear why this row would return TRANSLATION_ERROR.

Do you have the error message from the log?

**Comment by pedrogit** [comment]
Make sure constraint 2.19 pass before closing this issue.

**Comment by pedrogit** [comment]
Constraint 2.19 passed. Closing.
