### ISSUE TITLE
Many rows in AB06, AB16, NT01 and NT02 produce DIST_EXT_LOWER_1 = 1

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#387]
Check for DIST_EXT_LOWER_2 and DIST_EXT_LOWER_3 also...

**Comment by edwardsmarc** [comment]
1 is an expected value based on the translation rule:

`mapInt(dist_ext_lower_1, {1,2,3,4,5}, {1,26,51,76,96})`

Assigning to @prvernier so he can validate this is the correct translation.

**Comment by prvernier** [comment]
I believe that 1 is a valid value for DIST_EXT_LOWER and this needs to be updated in the specs (I can do that):

- Disturbance extent upper – upper bound of extent class 10 – 100
- Disturbance extent lower – lower extent of extent class 1 - 95

**Comment by pedrogit** [comment]
Constraints have also to be updated to accept 1.

**Comment by pedrogit** [comment]
Stilll have to check constraint 2.28, 2.29 and 2.30 on next complete translation.

**Comment by edwardsmarc** [comment]
Constraints still failing due to translation error in NS03 disturbance table.

**Comment by edwardsmarc** [comment]
NS03 translation fixed, code 62 now returns unknown error code for extent. Re-running translation and re-testing constraints.

**Comment by edwardsmarc** [comment]
Constraint changed to accept value up to 100 instead of 95.
Passes.
