### ISSUE TITLE
ECO QC03: Need helper function to simultaneously translated 4 attributes

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#398]
According to Cosco, field WETLAND_TYPE, WET_VEG_COVER, WET_LANDFORM_MOD and WET_LOCAL_MOD are assigned simultaneously using a set of value:

![QC03_ECO_mindmup](https://user-images.githubusercontent.com/10730242/86925584-0f0e2480-c0ff-11ea-9d23-1fc82aa44770.jpg)

How to deal with translation and validation rules when that happen?

**Comment by edwardsmarc** [comment]
We can make a custom function that runs all your logic and returns a 4-letter code. Then we can just use tt_substring in the translation table to extract the relavent character from the 4-letter code.

We might need to review the logic together. Why are there two lists of gr_ess values in the bottom image for example? Why not combine into one long list?

**Comment by MelinaHoule** [comment]
The logic is right. Following Cosco review, MJ28 was added in STNN. In bottom diagram, the 1st and 3rd can be combined (1st is conifer, 3rd is deciduous. They should have been merged). See new version below with those 2 fix
![QC03_ECO_mindmup](https://user-images.githubusercontent.com/10730242/97191253-13794e80-177d-11eb-9fd2-9526aa5e0cdc.jpg)

Now that we deal with 3 standards in QC, should we keep 1 function and add a parameter on the standard and adapt the species list in the function according the the standard?

Or we create 3 functions and pass different species code list?

**Comment by edwardsmarc** [comment]
I should probably split it into 3 functions to match what we did elsewhere. I'm guessing the logic using TYPE_ECO is for prg5, and the gr_ess logic is prg3 and prg4?

**Comment by MelinaHoule** [comment]
No, the logic is the same for all 3 standards. Only the species code change. Type_eco gives the vegetation type, physical attributes (type and thickness of deposit + index on water drainage) and topography, all into one value. Cosco's rules use either a combinaison of species_code, soil_moisture_reg and density/height to derive ECO attributes or some direct TYPE_ECO. The 3 standards will thus use the same logic, but species code will change between the 3rd and the 4th/5th. Species code are the same in the 4th and 5th.

**Comment by edwardsmarc** [comment]
So are the lists of species codes in the diagram above a mix of 3rd and 4th/5th codes?

If so the function should work as it is for all inventories. I'll just need to update it with your recent comments.

**Comment by MelinaHoule** [comment]
The species listed in the diagram come from Cosco rules, which means from the 3rd. I know some species code are use in both 3rd and 4th, but don't have the same meaning. I'll check if species listed in the diagram could be problematic, thus we will need to provide 2 list of species depending of the standard or if they aren't, we could merge the 2 list together and keep the function as it is. I'll provide more information soon.

**Comment by MelinaHoule** [comment]
One gr_ess code is problematic. In QC03, ES means balsam fir/white spruce while in QC04-QC05, it means maple sugar. All others are either unique to the inventories or the same. Here are the translation for each case QC03 (QC04):

RME (RXML), RE (RXEP), BB1 (BPFX),BBBB (BPBP), PUC (PUTO), BJ (BJ, BJBJ), PE1 (PEFX), BB1E (BPEP), BBBBE (BPBPEP), EBB (EPBP),RC (RXTO), SE (SBEP), SC (SBTO), CC (TOTO), CE (TOEP), CME (TOML), CPU (TOPU), BB (BPFX), MEC (MLTO), EE (EPEP), EME (EPML),FT (FTFT), CS (TOSE), EPU (EPPU), EC (EPTO),FH (FHFH), PE (PEPE), FI (FIFI), FNC (FNFN), MEME (MLML, ML), MEE (MLEP), ES (EPSE)

**Comment by edwardsmarc** [comment]
So we will need two versions of the function, one for qc03 and one for qc04-qc05. I'll need a version of the logic diagram above for qc03 and another version for qc04-qc05. I just need to know what gr_ess codes to use in each case.

**Comment by pedrogit** [comment]
If the logic for QC03, QC04 and QC05 is very similar you can pass the standard as a string constant ("QC03", "QC04" or "QC05") to the function so it can resolve the few existing exceptions. If the logic is very different then it's better to write different version of the function.

**Comment by MelinaHoule** [comment]
The logic is the same. Only species code change. Below is the new schema (Note: Font colour doesn't mean anything)
![QC03_ECO_v2_mindmup](https://user-images.githubusercontent.com/10730242/98289102-b730de80-1f75-11eb-8419-83efa3ee2650.jpg)

**Comment by edwardsmarc** [comment]
@pedrogit : there are multiple internal functions that run to translate wetland. 
- TT_qc_ipf_wetland_code() runs the logic above to get a 4-character wetland code. I'll add an inventory argument to this function as you suggest above. 
- TT_wetland_code_translation() translates the 4-character code into the CASFRI value. This is used in all inventories with wetland translations.
- I will make functions TT_qc03_wetland_translation() and TT_qc04_qc05_wetland_translation() that will call the above functions. I prefer to have two translation functions here to match what we have done elsewhere. We don't have any helper functions that take inventory id as an argument.

**Comment by edwardsmarc** [comment]
@MelinaHoule : at some point your logic diagram lost the SONS translation listed in the first version at the top of this issue. Is that still a valid translation?

**Comment by edwardsmarc** [comment]
Following functions have been created:

tt_qc_prg3_wetland_validation(CO_TER, CL_DRAIN, gr_ess, cl_dens, cl_haut, TYPE_ECO)
tt_qc_prg45_wetland_validation(CO_TER, CL_DRAIN, gr_ess, cl_dens, cl_haut, TYPE_ECO)
tt_qc_prg3_wetland_translation(CO_TER, CL_DRAIN, gr_ess, cl_dens, cl_haut, TYPE_ECO)
tt_qc_prg45_wetland_translation(CO_TER, CL_DRAIN, gr_ess, cl_dens, cl_haut, TYPE_ECO)

**Comment by edwardsmarc** [comment]
Ran into a problem during testing. The logic diagram relies on density and height values, but into prg3 and prg4 these attributes are coded into classes.  Whereas in prg5 they are numerics.

Will therefore need an ECO function for each inventory:

QC03 - uses density and height class values in logic. Uses prg3 species.
QC04 - uses density and height class values in logic. Uses prg4/prg5 species.
QC05 - uses density and height numeric values in logic. Uses prg4/prg5 species.

**Comment by edwardsmarc** [comment]
Update, prg 5 does in fact have coded density and height, as well as numeric. Stored in different columns. So we can use the coded values to match the behavior of prg3 and prg4. Function logic has been updated to convert the density (A, B, C, D) and height (1, 2, 3, 4, 5, 6, 7) codes to numeric values to work with the logical tests.
