### ISSUE TITLE
Make sure 2018 BC dataset is the same as BC08 and replace BC08 with it if so

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#399]
What is the link to this 2018 dataset?

**Comment by prvernier** [comment]
https://pub.data.gov.bc.ca/datasets/02dba161-fdb7-48ae-a4bb-bd6ef017c36d/

**Comment by pedrogit** [comment]
This does not look like a permanent link. I would like to put a permanent link in the inventory_list_cas05.csv file. Isn't there a web page where to download the complete dataset? For example the link we have in the list for BC08 is now dead. So same question applies for BC08.

Also: BC10 is supposed to be 2019 right? Why does the year found in the name of the file we have is 2018 (VEG_COMP_LYR_D_POLY_2018.gdb.zip etc. in the BC10/data/inventory/actual folder)? This does not looks like it is corresponding to the "current" BC dataset which is tagged as "2019". 

Also: The PHOTO_YEAR_END for BC10 in inventory_list_cas05.csv is 2018. Should it not be 2019? And the PHOTO_YEAR_END for BC08 is 2017.

Why do they tag the "current" one "2019"? Should not the current be "2020"?

All that is very confusing and that's why those datasets should have a version number. I hope CASFRI will maintain a clear version number policy in the future...

**Comment by prvernier** [comment]
**VRI - HISTORICAL Vegetation Resource Inventory (2002 - 2018)**

- https://catalogue.data.gov.bc.ca/dataset/vri-historical-vegetation-resource-inventory-2002-2018-

**VRI - 2019 - Forest Vegetation Composite Layers**

- https://catalogue.data.gov.bc.ca/dataset/vri-2019-forest-vegetation-composite-layer-1-l1-
- https://catalogue.data.gov.bc.ca/dataset/vri-2019-forest-vegetation-composite-layer-2-l2-
-  https://catalogue.data.gov.bc.ca/dataset/vri-2019-forest-vegetation-composite-dead-layer-d-

I'm tabulating number of records in rawfri and comparing to BC inventories by year...

**Comment by prvernier** [comment]
It seems there's been some confusion due in part to the renaming and re-organizing of files on the BC server and maybe our own server. In any case, we have not translated the latest BC inventory (2019) which was released Feb 19, 2020.

I've downloaded L1 for the past four years. Here are the number of records: 

- 2019: 5,419,596 records
- 2018: 5,151,772 records
- 2017: 4,861,240 records
- 2016: 4,677,411 records

And here's what we've translated so far:
  - rawfri.bc08 has 4,677,411 records [this corresponds to the 2016 inventory] - R1 only
  - rawfri.bc09 has 5,151,772 records [this corresponds to the 2018 inventory] - we dropped this one because it only used R1
  - rawfri.bc10 has 5,151,772 records [this corresponds to the 2018 inventory] - we used this one because it has L1, L2, D

Looks like we're also missing 2017. Since our priority is the 2019 inventory, we could name and translate the missing inventories in this sequence:

BC11 - 2019 BC inventory (L1, L2, D)
BC12 - 2017 BC inventory (L1, L2, D)
BC13 - 2016 BC inventory (L1, L2, D); this would be the expanded version of BC08

We would thus have inventories for the last four years.

Any thoughts?

**Comment by prvernier** [comment]
Note: I've downloaded the 2019 files (L1, L2, D) and placed them on D:\FRIs\BC\tmp\2019 until we agree on their names.

**Comment by pedrogit** [comment]
Does the BC inventories available on this site get final (or definitive) at some point? Or are they always updated (even the last ones)? 

If they ever get into a definitive version, we could wait for these versions to integrate them. This way we would not have to worry about future updates and get confused about what is what and the desire to replace the old ones with the updated ones.

Are your proposed BC11, BC12 and BC13 dataset definitive versions?

**Comment by prvernier** [comment]
I think the major reorganization took place earlier this year and now they are just adding L1, L2 etc. to the historical inventories. The number of records and attributes values shouldn't be changing, however some attribute names (esp. older inventories) will likely have changed to standardize them. So, I think we can consider them definitive now. And, yes, I am proposing that we name them BC11, BC12, and BC13 to reflect our priorities in translating these and consider them final products. I'm assuming the 2020 inventory won't be posted until early 2021, maybe before we finish :)

**Comment by edwardsmarc** [comment]
I support this order of loading. Lets make sure we get the inventory list up to date now @prvernier has figured out all the years!

**Comment by prvernier** [comment]
I can update the list.

**Comment by pedrogit** [comment]
We must:

- archive the inventories
- update the list
- make the workflow scripts for those inventories
- test that everything translate properly

I'll do it. Focus on MB.

**Comment by prvernier** [comment]
I've already updated the list and pushed it. I've also put the downloaded files in the appropriate folders on the server (BC11, etc.)

**Comment by pedrogit** [comment]
Does "2019" in the name of the inventory refers to the date of publication or to the PHOTO_YEAR?

**Comment by prvernier** [comment]
I think it's the year for which the inventory is current, not the photo year. The published date is sometimes early in the next year e.g., Feb 2020 for the 2019 data.

**Comment by pedrogit** [comment]
So that would be the "production year"?

**Comment by prvernier** [comment]
Yes

**Comment by edwardsmarc** [comment]
Tables, code, attribute dependencies, test file and workflow scripts updated. Need to test that results are as expected. One thing I noticed was that in the test file, the number of rows produced for bc08 is always the same as bc10, suggesting the translations are identical. How much difference do we expect between these datasets?

**Comment by prvernier** [comment]
There should be 474,361 more polygons in the full bc10 table than the full bc08 table.

**Comment by edwardsmarc** [comment]
We can check the number of rows in the final translations. It's likely that our test samples are the same because most of the polygons are the same in these two datasets.
