### ISSUE TITLE
Reorganize FRIs folder structure according to new CASFRI conventions.

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#40]
- Rename FRI folders according the the new file name scheme.
- Bring together everything related to a FRI in a single, structured, folder hierarchy.
- Put everything not necessary for CASFRI 5.0 in an 'archive' folder

We should agree on a structure before moving/renaming everything.

**Comment by edwardsmarc** [comment]
Inventory level folder structure. Docs should be with their data.

**Comment by prvernier** [comment]
One possible way to organize the data and docs:

casfri
	- docs
		- specs
		- contacts
	- ab	
		- docs
		- ab06 (date)
			- docs
			- data

Thoughts?

**Comment by edwardsmarc** [comment]
Currently we have:
--FRIs
----BC
------SourceDataset
--------v.00.04
----------BCGOV

We can remove v.00.04 and SourceDataset, they are redundant if we label using the FRI codes (e.g. BC08). So we could have:
--FRIs
----BC
------BC08
--------VEG_COMP_LYR_R1_POLY.gdb
--------docs
------docs
----AB
------AB06
--------GB_S21_TWP.gdb
--------docs
------photoyear
--------PhotoYear_Update.shp
--------docs
------docs

The FRI specific docs folder would be for docs that came with that inventory. The higher level docs folder could be used for standard specific docs (or removed if not necessary?).

**Comment by pedrogit** [comment]
I like that!

**Comment by prvernier** [comment]
Yes, looks good!

**Comment by pedrogit** [comment]
Should not photoyear be inside each juridiction folder for which it applies?

**Comment by edwardsmarc** [comment]
Photoyear is one file for the entire province so we only need to load it once.

**Comment by pedrogit** [comment]
It would be important to group source inventories documentation into separate folders according to the source inventory they document. e.g. Put BC08 and BC09 documentation into their specific folders.

BC/doc/BC08
BC/doc/BC09

If a set of documents documents many inventores, make it explicit: 

BC/doc/BC08-09

And rename each document with meaningfull names.

Right now doc folders are a bit of a mess... And its hard to say which inventory each document documents.

**Comment by pedrogit** [comment]
Melina and I met and agreed on this new structure:

FRI/
├─AB/
│    ├─AB06/
│    │   ├─data/
│    │   │   ├─archive/
│    │   │   ├─coverage/
│    │   │   ├─inventory/
│    │   │   └─photoyear/
│    │   ├─doc/
│    │   │   ├─archive/
│    │   │   ├─emailexchange/
│    │   │   ├─manual/
│    │   │   │   ├─others/
│    │   │   └─map/
│    │   ├─license/
│    │   └─toclassify/
│    └─AB16/
│    │   ├─data/
│    │   ├─doc/
│    │   ├─.../
├─BC/
│    ├─.../
...

- "archive" is old stuff that we want to keep
- "data/coverage" is for shapefiles representing the spatial coverage of this inventory
- "toclassify" is for documents to be classified when having time
- "manual" should contain only the documents useful to CASFRI. Others manual should be put in manual/others.

- We agreed about not keeping personnal work files (e.g. .mdx, .xlsx, .doc) in this hierarchy. If you create some, keep them in your working folder.
- >

**Comment by prvernier** [comment]
This looks good. How would you create the coverage shapefile? By dissolving all polygons? Can we also create a master shapefile showing all inventories and their status?

**Comment by pedrogit** [comment]
We used to create the coverage by dissolving all polygons with PostGIS. We need a detailed version for spatial analysis and a simplified version for quick representation. We will document a method at some point. This folder now is mostly for existing coverages.

We use the simplified version to create a master shapefile. Which status are you refering to?

**Comment by prvernier** [comment]
Conversion and translation status.

**Comment by MelinaHoule** [comment]
Correction: We used to create coverage by dissolving raw inventories in ArcGIS. By doing this, we overestimated the coverage of some inventories, mostly in AB. Some FMA cover a small portion of a mapsheet, the rest is filled with an empty polygon, which creates overlap with other FMA operating in the same mapsheet. I still don't know what would be the best stage to produced the coverage.

We used to have inventory status shapefile in the past that was never updated as we were working because it goes to fast and to much back and forth.  I think following the project tab in github with the issues would be enough.

**Comment by prvernier** [comment]
Thanks for the clarification on creating the coverages. I think a map for each would be useful and, eventually, combined for Canada. But, I agree that github is sufficient for status checks on a regular basis.

**Comment by pedrogit** [comment]
There is an issue to keep track of conversion and translation status:

https://github.com/edwardsmarc/CASFRI/issues/175

**Comment by pedrogit** [comment]
- AB\archive\phase3_fri_coverage.pdf should go in on of AB\AB06\doc\archive or AB\AB16\doc\archive since it is a map and maps are part of the doc folder.

- All readMe.txt should have a lowercase 'M'...

- AB16 coverage coverage should be converted to a shapefile

- Seems to me that VRI_Photo_Interpretation_Procedures.pdf should go directly in the doc folder since it's a major reference document.

- VRI Data Dictionary-rpt_vri_datadict0907_draft1.pdf should be named VRI Data Dictionary (rpt_vri_datadict0907_draft1).pdf

-We must get rid of one of BC09 VEG_COMP_LYR_R1_POLY.gdb or VEG_COMP_POLY_AND_LAYER.gdb or both.

**Comment by MelinaHoule** [comment]
Closing that issue. I will update BC after we agreed on inventory versioning
