### ISSUE TITLE
97 AB16 STAND_STRUCTURE are translated to INVALID_VALUE which is not an acceptable value for an attribute containing codes

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#407]
4,STAND_STRUCTURE,text,"avi01_stand_structure_validation(stand_structure, nfl, anth_veg, anth_non, nat_non);hasCountOfNotNull(stand_structure, species_1_layer1, species_2_layer1, species_3_layer1, species_1_layer2, species_2_layer2, species_3_layer2, 1, 'FALSE'|INVALID_VALUE)","avi01_stand_structure_translation(stand_structure, species_1_layer1, species_2_layer1, species_3_layer1, species_1_layer2, species_2_layer2, species_3_layer2)","Validation returns NOT_APPLICABLE if row is NFL and not Horizontal. Or INVALID_VALUE if there is no stand structure or species info. Translation returns HORIZONTAL or COMPLEX, SINGLE_LAYERED if one forest layer, MULTI_LAYERED if two forest layers. Source stand structure counted NFL layers as forest layers, CASFRI does not.",TRUE

Acceptable error codes for attribute containing codes are defined by the CASFRI TT_IsMissingOrNotInSetCode() helper function. They are: 'NULL_VALUE', 'EMPTY_STRING',  'NOT_APPLICABLE',  'UNKNOWN_VALUE',  'NOT_IN_SET'

**Comment by pedrogit** [comment]
Check constraint 1.16 before closing this issue.

**Comment by edwardsmarc** [comment]
What are these 97 rows? Must be DST if NFL is accounted for in avi01_stand_structure_validation? Check.
Should probably be returning NOT_APPLICABLE instead of INVALID.

**Comment by pedrogit** [comment]
NON_FOR_ANTH is also sometimes set to INVALID_VALUE in AB06 and AB16.

There seems to be missing some notNull() or notEmpty() check for those attributes.

The default error code for hasCountOfNotNull() is INVALID_VALUE. Maybe in those cases it could be overwritten with NULL_VALUE?

**Comment by pedrogit** [comment]
Check constraints 1.16 and 5.23 before closing this issue.

**Comment by edwardsmarc** [comment]
Issue should be fixed, check constraints.

**Comment by pedrogit** [comment]
Constraints 1.16 and 5.23 passed.
