### ISSUE TITLE
Convert SRC_INV_AREA to hectare when necessary

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#414]
Some inventories provide SRC_INV_AREA  in square meters. According to the specs it should be converted to hectares.

At least BC100 has to be converted. Check the others...

copyDouble(src_inv_area) could be replaced with a new divide(src_inv_area, 10000) helper function.

**Comment by edwardsmarc** [comment]
The following inventories need SRC_INV_AREA to be converted from metres to ha:
* AB06
* AB16
* BC08
* BC10
* NB01
* NB02
* ON02
* SK01
