### ISSUE TITLE
Bug in helper function TT_MinIndexLookupText & TT_MaxIndexLookupText 

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#417]
When both year (first parameter) are NULL, the function return the translation of the first value instead of the translation of the  first Non NULL value. 

NULL is not a value in the dist_type translation table. So in this example, the function return an error (NULL missing from translation table) instead of returning the translation of 'CT'

SELECT TT_minIndexLookupText('{NULL,NULL}', '{NULL,''CT''}', 'translation', 'qc_ipf05_dist_type', 'source_val', 'dist_type', NULL::text)

I couldn't find any example in helperFunctionsTest.sql with 2 NULL representing the first parameter. Something to add there too. 

Same thing for TT_MaxIndexLookupText, in SELECT TT_minIndexLookupText('{NULL,NULL}', '{NULL,''CT''}', 'translation', 'qc_ipf05_dist_type', 'source_val', 'dist_type', NULL::text), the function return the translation of CT. It should return NULL.

**Comment by edwardsmarc** [comment]
Moving this issue to the engine repo
