### ISSUE TITLE
Get rid of unused error codes

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#418]
WRONG_TYPE, UNUSED_VALUE and and NOT_UNIQUE are not really used in the final translated table. For the sake of simplicity we should probably get rid of them in the specs. And change the default error codes for the associated functions.

**Comment by edwardsmarc** [comment]
WRONG_TYPE can occur if isInt() fails. I fixed a couple of bugs by searching for WRONG_TYPE in the translated tables.

We could replace it with INVALID_VALUE but it would make bugs harder to find.

**Comment by edwardsmarc** [comment]
UNUSED_VALUE and NOT_UNIQUW removed. Kept WRONG_TYPE
