### ISSUE TITLE
NT02 NFL produces duplicates cas_id/layer couples

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#420]
ERROR:  could not create unique index "nfl_all_pkey"
DETAIL:  Key (cas_id, layer)=(NT02-xxxxxxNT_FORCOV-xxxxxxxx11-0011000140-0083393, 2) is duplicated.

**Comment by edwardsmarc** [comment]
No more duplicates, checked with:
`SELECT cas_id, layer FROM casfri50.lyr_all GROUP BY cas_id, layer HAVING count(*) >1`
