### ISSUE TITLE
MB05 and MB06 Translations

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#423]
Below is a list of most of the remaining tasks needed to complete the MB05 and MB06 translations.

MB05 (VRI01) inventory - remaining tasks
  
  - stand_structure, num_of_layers, lyr_nfl_layer, layer_rank need to be done
  - DST attributes need to be done
  - NFL attributes need to be done
  - SQL scripts written but need to be tested when tables are finished
	
MB06 (VLI01) inventory - remaining tasks

  - stand_structure, num_of_layers, lyr_nfl_layer, layer_rank need to be done
  - crown_closure - done except for the special case of veterans which **may need a helper function**:
    - if canlay=='V' and crowncl==0 then crown_closure_lower = 1 and crown_closure_upper = 5
    - else crown_closure_lower = 6 and crown_closure_upper = 10
    - the above is not fully clear and needs to be explored further
  - non_for_veg **may need a helper function**:
    - closed shrub (along with height to nearest metre and 0 to 9 crown closure)
  - See Cosco note re shrub crown closure
  - DST attributes: what about treatmod, treatext, trorig?
  - SQL scripts written but need to be tested when tables are finished

**Comment by edwardsmarc** [comment]
I'll hold off on the layer and stand structure attributes until the nfl tables are complete.

**Comment by prvernier** [comment]
MB05 (VRI01) inventory:

  * Attributes STAND_STRUCTURE, NUM_OF_LAYERS, LAYER, LAYER_RANK need to be created
  * Testing of translation tables with SQL workflow script currently only works with CAS attributes until above attributes exist
  * Source attribute "productivity" translation of codes 701-734:
    - 701-704=TM (treed muskeg) - added to PRODUCTIVITY_TYPE
    - 711-713=TR (treed rock) - added to PRODUCTIVITY_TYPE
    - 721-734 classified as NFL attributes (Cosco specs); revised specs suggest PRODUCTIVITY_TYPE; should this be updated in the specs document?
  * According to Cosco specs, there are no source fields for DST attributes

MB06 (VLI01) inventory:

  * Attributes STAND_STRUCTURE, NUM_OF_LAYERS, LAYER, LAYER_RANK need to be created
  * Should STAND_STRUCTURE be created from "canlay" instead of sp1, sp2, etc.?
  * STRUCTURE_RANGE needs to be created from canlay=C and comht x 2: new function required?
  * Testing of translation tables with SQL workflow script currently only works with CAS attributes until above attributes exist
  * CROWN_CLOSURE_UPPER/LOWER - done except for the special case of veterans which needs helper function:
    - if canlay=='V' and crowncl==0 then crown_closure_lower = 1 and crown_closure_upper = 5
    - else crown_closure_lower = 6 and crown_closure_upper = 10

**Comment by prvernier** [comment]
MB05 (VRI01) inventory:

The following "productivity" classes, which were previously classified as NFL attributes, have now been placed in the PRODUCTIVITY_TYPE attribute which is consistent with the revised specifications:
- classes 721-725 are now classified as "ALDER"
- classes 731-734 are now classified as "PROTECTION_FOREST"

**Comment by edwardsmarc** [comment]
Crown closure translation was used in NFL table for SO and SC. The translation contradicts the manual which states: 
"Open shrub - crown closure less than 50 percent."
"Closed shrub - crown closure more than 50 percent."

**Comment by edwardsmarc** [comment]
Translations complete, check the above discrepancy with @prvernier.
Run full translation and check constraints before closing.
