### ISSUE TITLE
Add QC04 and QC05 to inventory_list_cas05.csv

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#429]
@MelinaHoule and @edwardsmarc decided to split QC03 into three separate datasets.

One for the three standards: INI03, IPF04 and IPF05.

This will simplify the logic for translation tables. These three datasets will be treated as independent inventories for the purpose of translation. Each will have it's own complete set of translation tables. The translation tables for the 5th inventory will eventually be the only set used moving forward.

Related to #430

**Comment by MelinaHoule** [comment]
The 3rd is by its own. In the case of the 4th, the species composition happen in the middle of the cycle. The no_prg stayed the same (no_prg = 4), but the ver_prg (version or standard) changed from INITIALE  to MIXTE to NAIPF. INITIALE is related to the 3rd but use new names and MIXTE is a mix of INITIALE and NAIPF (which follow the 5th). Sometimes it uses in_etage and sometimes not. I can't find any field to help us split the MIXTE. In the 5th, ver_prg changed for AIPF. The rules would be as follow: 

1. QC03 : ver_prg IS NULL  (same as no_prg= 3)
2. QC04: ver_prg ='INITIALE'  OR (ver_prg ='MIXTE' AND in_etage = 'N')
3. QC05: ver_prg LIKE 'AIPF%' OR ver_prg LIKE 'NAIPF%' OR (ver_prg ='MIXTE' AND in_etage = 'O')

How does that sound?

**Comment by edwardsmarc** [comment]
This makes sense and captures all the cases.

**Comment by edwardsmarc** [comment]
closed with 948a4cf1b3dc88dc8be904126a44bc0726afc7c1
