### ISSUE TITLE
BC CAS ID parameters

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#43]
* Cas04 used an objectid attribute as the fourth cas id parameter
* We think this is created in ArcMap
* When the VRI dataset on the server is loaded there is no objectid attribute
* What should be the 4th parameter?

**Comment by prvernier** [comment]
For the fourth element of the CAS_ID, we are now using "feature_id" instead of the Arcmap generated "objectid". The "feature_id" is defined as "Provincially unique identifier for an instance of a spatial feature" and is more appropriate.

**Comment by pedrogit** [comment]
Is is unique? Did you verify?

**Comment by prvernier** [comment]
Yes, it is.
