### ISSUE TITLE
Make conversion scripts for QC04 and QC05

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#430]
As per #429 we are splitting the current QC03 dataset into three datasets that will be named QC03, QC04 and QC05.

Write three conversion scripts, one for each.

The rules for filtering the single source table are as follows:

QC03 - no_prg = 3

QC04 - no_prg = 4 and in_etage = N

QC05 - in_etage = O

**Comment by edwardsmarc** [comment]
Copied from #430:

The 3rd is by its own. In the case of the 4th, the species composition happen in the middle of the cycle. The no_prg stayed the same (no_prg = 4), but the ver_prg (version or standard) changed from INITIALE to MIXTE to NAIPF. INITIALE is related to the 3rd but use new names and MIXTE is a mix of INITIALE and NAIPF (which follow the 5th). Sometimes it uses in_etage and sometimes not. I can't find any field to help us split the MIXTE. In the 5th, ver_prg changed for AIPF. The rules would be as follow:

QC03 : ver_prg IS NULL (same as no_prg= 3)
QC04: ver_prg ='INITIALE' OR (ver_prg ='MIXTE' AND in_etage = 'N')
QC05: ver_prg LIKE 'AIPF%' OR ver_prg LIKE 'NAIPF%' OR (ver_prg ='MIXTE' AND in_etage = 'O')

**Comment by edwardsmarc** [comment]
Need to drop the '_full' tables at the end of the sql statement.

**Comment by MelinaHoule** [comment]
Loading script have been updated and tested
