### ISSUE TITLE
QC03, QC04 - Need helperFunction do derive ORIGIN_LOWER and ORIGIN_UPPER

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#432]
In QC03 and QC04, ORIGIN needs to be derived using photoyear (an_pro_ori) - age (cl_age). However, cl_age has a complex structure which allow to derive stand_structure. For example, cl_age can be 1030, 90100 or 70JIN. In QC03 and QC04, only layer 1 is translated. In order to translate ORIGIN__LOWER and ORIGIN_UPPER, we need to use the translation table QC_ini03_standstructure and use l1_age_origin to extract age prior to substract it from an_pro_ori.

**Comment by edwardsmarc** [comment]
Added function tt_qc_ini03_origin_translation(cl_age, an_pro_ori).
Looks up the l1_age_origin value for the cl_age code from the lookup table, then substracts that value from an_pro_ori.

ORIGIN_UPPER and ORIGIN_LOEWR should use the following validations:
- isInt(an_pro_ori|-8886)
- notNull(cl_age)
- notEmpty(cl_age)
- matchTable(cl_age, 'translation', 'qc_ini03_standstructure') to check that the cl_age value is in the lookup table.

**Comment by MelinaHoule** [comment]
Close with 5c79c3239e77aabf83adf85470e7d914ebdc8322
