### ISSUE TITLE
Constraints - 4.2, 5.2, 4.45, 4.70 are failing

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#436]
Running the constraints on the tranlsated MB05 and MB06 data gives the following failures. I need help troubleshooting these:

* Foreign key fails for LYR and NFL - constraints 4.2 and 5.2. Why would foreign key fail?

* Lookup test for PRODUCTIVITY and PRODUCTIVITY_TYPE fails - constraints 4.45, 4.70. However the values in casfri match the permitted values listed in the constraint. Is there meant to be a lookup table created for these attributes? Similar to species_codes_lookup?

**Comment by pedrogit** [comment]
Foreign keys generally fail when there is no equivalent key in the foreign table. Checking...

**Comment by pedrogit** [comment]
All constraints worked after fixing list of acceptable codes and translating both MS05 and MB06. Will close after a complete translation.

**Comment by pedrogit** [comment]
All those constraints now pass. Closing.
