### ISSUE TITLE
NL01 Inventory - Functions needed for LYR attributes

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#438]
# Functions needed for LYR attributes

Several CAS attributes are defined differently depending on whether they are considered to be commercial or non-commercial forests. These will need new helper functions. The source attribute "stand_id" can be used to distinguish between the two classes:

**Commercial forest**: stand_id = 1-899, 1000-7000
**Non-commercial forest**: stand_id = 900, 910 or working_group = 'CS', 'DS'

NOTE: Do these make sense?

## SOIL_MOIST_REG

**Commercial forest**:
SOIL_MOIST_REG: undefined

**Non-commercial forest**: [This is entered in the LYR table but needs to be restricted to non-commercial]
SOIL_MOIST_REG: mapText(soil_moisture_regime, {'d','D','w','W'}, {'DRY','DRY','WET','WET'})

*ME: add validation function to check stand_id is 900 or 910 or working_group is CS or DS:*

**tt_nl_nli01_isNonCommercial(stand_id, working_group)**

## CROWN_UPPER, CROWN_LOWER

**Commercial forest**: [This is missing from the LYR table]
CROWN_UPPER: mapInt(density_code, {1,2,3}, {50,75,100})
CROWN_LOWER: mapInt(density_code, {1,2,3}, {26,51,76})

In addition, according to Cosco:
  - 0 Cannot be defined from interpretation
  - DI or NSRV 1-25

**Non-commercial forest**: [This is entered in the LYR table]
CROWN_UPPER: mapInt(density_code, {1,2,3,4}, {25,50,75,100})
CROWN_LOWER: mapInt(density_code, {1,2,3,4}, {10,26,51,76})

**ME: requires custom function**

**ME note: DI (disturbed) and NS (not stocked) are not LYR or NFL rows and will therefore not have any crown_closure values to define.**

## HEIGHT_UPPER, HEIGHT_LOWER

**Commercial forest**: [This is entered in the LYR table]
HEIGHT_UPPER: mapInt(height_class, {1,2,3,4,5,6,7,8}, {3.5,6.5,9.5,12.5,15.5,18.5,21.5,100})
HEIGHT_LOWER: mapInt(height_class, {1,2,3,4,5,6,7,8}, {0,3.6,6.6,9.6,12.6,15.6,18.6,21.6})

**Non-commercial forest**: [This is missing from the LYR table]
HEIGHT_UPPER: mapInt(height_class, {1,2,3,4,5}, {3.5,6.5,9.5,12.5,15.5})
HEIGHT_LOWER: mapInt(height_class, {1,2,3,4,5}, {0,3.6,6.6,9.6,12.6})

**ME: requires custom function**

## PRODUCTIVITY

The source attribute "stand_id" can be used to identify productive and non-productive forests:
NON_PRODUCTIVE_FOREST: stand_id = 900, 910 or working_group = 'CS', 'DS'
PRODUCTIVE_FOREST: stand_id = 1-899, 1000-7000

NOTE: double check to see if additional stand_id classes should be added to PRODUCTIVE_FOREST

**ME: requires custom function**

## PRODUCTIVITY_TYPE

TREED_MUSKEG: stand_id = 930
SCRUB_SHRUB: stand_id = 900, 910 or working_group = 'CS', 'DS'
HARVESTABLE: stand_id = 1-899, 1000-7000

NOTE: double check to see if additional stand_id classes should be added

**ME: requires custom function**

## SPECIES_1-3, SPECIES_PER_1-3

The source attribute species_comp contains up to 3 species/species_percent, for example:

if 1 species (e.g., species_comp = bF):
    species_1 = "ABIE_BALS"; species_per_1 = 100

if 2 species (e.g., species_comp = bfwB):
    species_1 = "ABIE_BALS"; species_per_1 = 60
    species_2 = "BETU_PAPY", species_per_2 = 40

if 3 species (e.g., species_comp = bFbSwB):
    species_1 = "ABIE_BALS"; species_per_1 = 40
    species_2 = "PICE_MARI", species_per_2 = 30
    species_3 = "BETU_PAPY", species_per_3 = 30

**ME: Use lengthMatchList() to check species is present. Then write TT_MatchTableSubstring() and TT_LookupTextSubstring() to get the correct code and lookup the species**

## ORIGIN_UPPER, ORIGIN_LOWER

Rules are slightly different between Newfoundland and Labrador rather than between commercial and non-commercial:

**Newfoundland**: [This is missing from the LYR table]
ORIGIN_UPPER: mapInt(age_class, {1,2,3,4,5,6,7}, {20,40,60,80,100,120,2000})
ORIGIN_LOWER: mapInt(age_class, {1,2,3,4,5,6,7}, {0,21,41,61,81,101,121})

**Labrador**: [This is entered in the LYR table]
ORIGIN_UPPER: mapInt(age_class, {1,2,3,4,5,6,7,8,9}, {20,40,60,80,100,120,140,160,2000})
ORIGIN_LOWER: mapInt(age_class, {1,2,3,4,5,6,7,8,9}, {0,21,41,61,81,101,121,141,161})

**ME: requires custom function**

## SITE_CLASS

The Cosco specs translate this attribute using only what's described under "Commercial forest" below. This means all polygons are translated the same way. However, the Newfoundland manual splits this attribute based on forest type; the problem is that the classes under "Non-commercial forest" are not SITE CLASS types. So, do we leave as is (i.e., as per Cosco) or do we enquire further?

**Commercial forest**: [This is entered in the LYR table]
SITE_CLASS: mapText({site}, {'p','P','m','M','g','G','h','H'}, {'POOR','POOR','MEDIUM','MEDIUM','GOOD','GOOD','GOOD','GOOD'})

**Non-commercial forest**: [This is missing from the LYR table]
SITE_CLASS: mapText({site}, {'w','W','d','D','r','R'}, {'WET','WET','DRY','DRY','BEDROCK','BEDROCK'})
**ME: I would say these don't fit into the CASFRI specs so they are either UNKNOWN_VALUE or NOT_APPLICABLE. Or actually we have a value UNUSED_VALUE that would fit this.**

**Comment by edwardsmarc** [comment]
Helper functions required:

Helper function to decide if row is commercial forest:
**tt_nl_nli01_isCommercial(stand_id, working_group)**
- Returns TRUE if stand_id 1-899 or 1000-7000, and working_group is NOT CS or DS.

Helper function to decide if row is non-commercial forest:
**tt_nl_nli01_isNonCommercial(stand_id, working_group)**
- Returns TRUE if stand_id 900, 910 or working_group is CS or DS.

**Comment by edwardsmarc** [comment]
@prvernier - I'm working on the ORIGIN functions and noticed that in your mappings above we are returning age values, not origin values.

I think we need to get the age value, then subtract it from the photo year to get origin. Do you agree?

I guess since origin upper should be the higher of the year values, I should switch the mappings for upper and lower. So for a Newfoundland age code of 1 and a photo year of 2000, origin upper would be 2000 and lower would be 1980.

I can add the photo year translation, it is currently missing from the CAS table. We'll need to run an intersect similar to in AB because photo year is stored in a shapefile.

**Comment by edwardsmarc** [comment]
@prvernier What does the 2000 value represent for old growth classes denoted as 161+ ?

I guess in those cases ORIGIN_UPPER would be photo_year - 161.
And ORIGIN_LOWER is unknown. We could either assign 1000 which is the lowest values allowed according to the specs, or we would assign UNKNOWN_VALUE.

**Comment by prvernier** [comment]
Yes, that sounds about right. I meant to discuss how to convert age class to origin without a year attribute yesterday - so, using photo year seems to be the logical choice.

**Comment by prvernier** [comment]
The value 2000 is arbitrary - in the specs, Cosco uses "INFINITY" i.e., 121-INFINITY for Newfoundland and 161-INFINITY for Labrador.

**Comment by prvernier** [comment]
I think assigning a value of 1000 would be wrong - in the example you provided, this would give a lower value of 1000 (2000 - 1000). We could use 200, which would likely be closer i.e., 1800 (2000 - 200), but still only a guess. On the other hand, UNKNOW_VALUE is probably correct but seems like a misleading value. I'm not sure...

**Comment by edwardsmarc** [comment]
We decided to use UNKNOWN_VALUE for ORIGIN_LOWER in polygons with age 161+

**Comment by edwardsmarc** [comment]
Note to @edwardsmarc : origin is producing translation errors. Figure out why and catch with validation.
