### ISSUE TITLE
Add value WATERBODIES to NFL NAT_NON_VEG attributes

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#439]
In QC03, QC04 and QC05, rivers and lakes are represented by the same value in the raw data: waterbody. There is no other field that allow us to split them appart. NAT_NON_VEG attributes need to be able to represent those water features that are not explicitly named.

**Comment by edwardsmarc** [comment]
I have added WATERBODY to the specs for NAT_NON_VEG. 

@pedrogit - can you add this as an acceptable value in the constraints file? And any associated lookup table?
