### ISSUE TITLE
TT_Between raises error with text

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#44]
* TT_Between is set to raise error if it recieves a text value.
* BC08 translation is failing due to this raised error.
* Not sure if the problem is due to the TT_Between exception (should this be switched to false?), or if the problem is that the engine is casting a numeric (crown_closure) to a text.
* Lots of validation functions raise exceptions if input type is invalid. Should this functionality be removed?

**Comment by pedrogit** [comment]
Closed by https://github.com/edwardsmarc/postTranslationEngine/commit/c1aed83300f09cd7afe941f34b7f2cc52b09dfc8
