### ISSUE TITLE
Does CASFRI schema allow CAS orphan?

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#440]
Does CASFRI schema allow to have a geometry associated with a CAS entry without having any DST, LYR, NFL and ECO associated. In Quebec (QC03, QC04, QC05), some polygons are defined as "not interpreted" or "nature unknown" by the field CO_TER. We don't have any attributes to help us classify those polygons into the proper table. That means, those polygons will have a GEO and a CAS  entry but will be orphan of any other attributes. Is that ok? Or does the CAS schema always expect to be link at list with one of the attribute tables?

**Comment by edwardsmarc** [comment]
There is no requirement that a geo and cas row also need to have other tables.  There is a constraint that num_of_layers must not be 0, but it is possible to assign UNKNOWN_VALUE to num_of_layers.

The real question is, why would we include these polygons if they don't contain any information? In other inventories we have just dropped these empty polygons, usually during the loading procedure. If it's too complex to drop them during loading we can also add a ROW_TRANSLATION_RULE to both CAS and GEO tables to filter them out.

Maybe @pedrogit has some thoughts on this?

**Comment by pedrogit** [comment]
Seems to me that in this particular case and only in this particular case we could solve it by assigning 0 to num_of_layers. I would be surprised if this does not happen in other inventories even if we filter most of the no data polygons at load time. i.e that the combination of all ROW_TRANSLATION_RULES would exactly match the loading filter.

**Comment by edwardsmarc** [comment]
@pedrogit So we would just leave them in as empty polygons with num_of_layers = 0?

**Comment by pedrogit** [comment]
Yep. No need for an extra column and all polygon would be provided.

Now I don't remember if it happens that a polygon can have only DST info (aren't these depletion rows? I think I found that yes that happens). In that case there would be no pecific way to tell if there is or there is no DST info.

**Comment by edwardsmarc** [comment]
Yes this is true, and is the reason for #340. 

Many rows will have only CAS, GEO and DST. The depletion updates in AB are one example but it occurs elsewhere.

@pedrogit is correct. The only way to tell if a cas_id with num_of_layers = 0 (actually due to #340 it would num_of_layers = UNKNOWN_VALUE) has a DST record would be to join the tables.

**Comment by pedrogit** [comment]
We could add a num_of_dst column... But again this problem would not occur with the new schema because all polygon would have at least one entry in the horizontal_cmp and one entry in the vertical_cmp table envent if it says UNKNOWN. I would rather work on buying the new car then trying to fix the old buggy.

**Comment by pedrogit** [comment]
So the end answer for now is YES, we allow orphans. And NUM_OF_LAYERS should be UNKNOWN_VALUE in these cases. All we know in these cases is that there is no LYR or NFL info. There could be a DST.

So CAS rows with NUM_OF_LAYERS = UNKNOWN_VALUE could be for 2 reasons:

All we have is a polygon with a DST record.
All we have is a polygon with no information about DST, LYR or NFL.

0 is not an acceptable value for NUM_OF_LAYERS.

See the last issues related to this: #609
