### ISSUE TITLE
QC03 Potentially replace photo_year info missing by photo_interpretation_year

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#444]
In QC, 3 fields are linked to photo_year: photo_year, photo_interpretation_year, modification_year (often related to a depletion update). For QC04 and QC05 we take photo_year_date. In QC03, photo_year_date is always unknown. It was not a field that existed in the old structure of the third inventory. The field used was photo_interpretation_year. photo_interpretation_year is known for every polygons in QC03. I spoke with the chief of photo-interpretation in the QC gov. Knowing from him that photo_interpretation_year is always within 3 years max from photo_year (usually it's one year after), are we confident using photo_interpretation_year instead of photo_year? That will be apply for both 
STAND_PHOTO_YEAR and ORIGIN_UPPER/ORIGIN_LOWER that is derived from photo_year - age. QC03 has 400 000 polygons

**Comment by edwardsmarc** [comment]
If it's usually 1 year after the true photo year date, could we just use photo_interpretation_date +1

It seems like whatever we use it will be wrong in some cases, but it's always going to pretty close to the true photo year. I think either option would work as long as we document this in the description column of the translation table.

**Comment by MelinaHoule** [comment]
I'll use photo_interpretation_year as photo_year for now and will document the translation table. I think if we derive photo_year by doing photo_interpretation_year - 1, we will need to adjust custom function qc_origin_translation to make it be  photo_interpretation_year - 1 - extracted_age and I'm not sure about that...

**Comment by edwardsmarc** [comment]
OK I agree, best to just use photo_interpretation_year for now and document its definition.

**Comment by MelinaHoule** [comment]
Closed with 5c79c3239e77aabf83adf85470e7d914ebdc8322
