### ISSUE TITLE
DST table in NL01

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#446]
NL01 has two attributes that store disturbance info: disturbance type, and silviculture type. Both also have years indicating the year of disturbance or silviculture.

Rows can have neither, one, or both attributes. Many rows have a type but not an associated year, or a year with no type.

This is very similar to disturbance info in QC03 so we already have functions to deal with this data structure. The translation functions return the disturbances in order by indexing on the year attributes. In the case of two disturbances the one with the oldest year value is assigned to DIST_TYPE_1. If one disturbance doesn't have a year it defaults to DIST_TYPE_2. In the case of a year with a missing type value, we assign UNKNOWN_VALUE.

Question for @prvernier : There is a disturbance type labelled "vegetation". Any idea what this means? It occurs in many many polygons.

**Comment by edwardsmarc** [comment]
ROW_TRANSLATION_RULE should only include row if it has a notEmpty disturbance or silviculture type, or a year value that is not zero.

**Comment by prvernier** [comment]
In answer to the question about the disturbance type labelled "vegetation", I really don't know and the manual does not provide a description. Looking at the data, most other attributes are "" or 0 for this value - except for "site", which takes commercial forest type values.

**Comment by edwardsmarc** [comment]
OK maybe it's something like 'potentially productive'. I think we can drop it from the disturbance table but I'll make a not in the description column that it has been dropped.

**Comment by prvernier** [comment]
Just looking at the perl code, it translates "V" to "OTHER" disturbance type. Maybe that's the way to given the number of polygons with that value.
