### ISSUE TITLE
MB05 and MB06 source data have wrong number of rows

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#447]
Source data has somehow been changed from the original data stored in CAS04 project.

The original MB v.00.04 GOV inventory had 1818749 rows. 
The MB05 has 675426 rows
MB06 has 576156 rows 

Could be caused by poly_id assignment, this is the only way I see a source table could be edited.

Solution: Copy data again, run loading script, see if rows are lost.

Additionally, check if OBJECT_ID could be used as a uniqye id instead of making poly_id. Is object_id loaded or internal to arcgis?

**Comment by edwardsmarc** [comment]
OBJECT_ID is added when the data is opened in ArcGIS, it is not loaded by GDAL and does not appear in the postgresql loaded tables.

**Comment by edwardsmarc** [comment]
Initial load works and doesn't remove any rows from the source table. Now testing a second load where poly_id is skipped.

**Comment by edwardsmarc** [comment]
Waiting for MB05 data to be unlocked. Once it is, delete the MB05 folder and rename MB05_test and MB06_test to Mb05 and MB06. Then reload both datasets and check the number of rows is correct. Expected rows are:

1,818,749 rows in both source geodatabases
1,644,808 rows in the loaded MB05 table
163,064 rows in the loaded MB06 table

**Comment by edwardsmarc** [comment]
This issue is complete but others should reload the tables and check they get the same number of rows as listed above.

**Comment by MelinaHoule** [comment]
I reloaded mb05 and mb06 in pg12 and numbers are the same as listed above.

**Comment by pedrogit** [comment]
> I reloaded mb05 and mb06 in pg12 and numbers are the same as listed above.

Same for me.
