### ISSUE TITLE
NFL table for NL

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#448]
@prvernier Can you confirm these translations in the NFL table. They don't seem correct to me:

stand_id 906 'Small Cut Area' is translated to 'FORBS'
stand_id 920 'Bog' is translated to 'BTYOID'
stand_id 925 'Wet bog' is translated to 'OPEN_MUSKEG'

**Comment by prvernier** [comment]
These are correct according to the Cosco specs and the perl code with one exception for stand_id 906, which according to the perl code: 

  - if (stand_id==906 & type_disturb=="X"): NON_FOR_VEG = "FORBS"

This may require a helper function?

**Comment by edwardsmarc** [comment]
type_disturb is always blank when stand_id is 906. So FORBS would never get reported. 

I think we should be drop this translation because we are assuming forbs will be present when we don't actually know. Plus there are no other non forest veg translations included in the source inventory.

**Comment by prvernier** [comment]
Sounds reasonable to me.
