### ISSUE TITLE
All SK05 STAND_PHOTO_YEAR are INVALID_VALUE

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#449]
Because source values are text strings padded with spaces on the left. e.g. '      2000'

**Comment by pedrogit** [comment]
Related to #248

**Comment by edwardsmarc** [comment]
Add remve_spaces argument to substringInt() and isIntSubstring(). Also apply to matchTableSubstring() and lookupTextSubstring() for consistency.

Change substring() call to tt_substring and pass remove_spaces through.
