### ISSUE TITLE
Fix CROWN CLOSURE translation rules for nb01

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#45]
* Crown closure upper and lower rules don't make sense
* I think lower and upper are mixed up.
* e.g. source value of 3 results in range of 70-51

**Comment by prvernier** [comment]
CROWN_CLOSURE_UPPER and CROWN_CLOSURE_LOWER were inversed. This has been corrected.

**Comment by prvernier** [comment]
The LOWER and UPPER values were inversed. This is fixe. However, we still need to look into values 61-64 i.e., sparsely treed polygons. Should they be included?

**Comment by prvernier** [comment]
Yes, it is the case for ab06 as well. I've mixed up upper and lower. I'll fix and push.

**Comment by prvernier** [comment]
Dropped values 61-64 from translation tables since they do not occur in l1cc attribute in NB01.

**Comment by pedrogit** [comment]
While fixing ab16 you made the translation rule dependent on the "density" field which does not exist.

**Comment by prvernier** [comment]
Fixed.
