### ISSUE TITLE
CASFRI species specs: _SUBS

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#451]
Current CASFRI species codes that represent generic codes for a genus use _SUBS.

e.g. a source code acer spp. would be translated to ACER_SUBS

_SUBS could be misinterpreted as meaning 'subspecies' which I don't think is the intended label here.

I would usually use _SPP but that is only 3 characters long.

**Comment by pedrogit** [comment]
I choose SUBS to keep everything 9 char long.

**Comment by MelinaHoule** [comment]
In the past, to keep it 9 char long, we used "ACER_SPP." Could it be a possibility? QC03 species lookup table will need to fit the decision.

**Comment by pedrogit** [comment]
I preferred "_SUBS" over "SSP." because the point is not really common in a code constant.

**Comment by edwardsmarc** [comment]
Replaced by #453
