### ISSUE TITLE
Switch species codes to use official Canadian species code list

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#453]
Currently there are some cases where species info is lost because the CASFRI coding system is limited to 9 characters made up of genus and species.

For example, the VRI codes a coastal variety of Douglas-fir (Pseudotsuga menziesii var. menziesii), but we are limited to recording this as PSEU_MENG so the variety info is lost.

We could switch to use the offical Canadian species list: https://nfi.nfis.org/resources/general/3-TreeSpeciesList-Version4.5.pdf

This system codes Genus (4 char), Species (3 char), Var (1-3 char).

We could adopt this system and apply a similar format as the cas id where missing info is simply filled with 'x' characters. For example the coast Douglas-fir variety would be coded as: PSEU_MEN_MEN. Whereas the regular Douglas-fir code would be PSEU_MEN_xxx.

This would also accommodate the fairly common case of generic codes such Acer_spp which could be coded as ACER_xxx_xxx.

**Comment by pedrogit** [comment]
The fact that the length of the code is limited to 9 characters does not really prevent the encoding of sub varieties. Something like "PSEU_MEMM" could have been used.

However I tend to agree with the proposition. It is more flexible, it uses a fixed lenght coding scheme and will prevent us from having to invent new codes for new species (what do we do if a species is not in the provided list?).

I would rather uses capital Xs instead of lower case ones.

**Comment by edwardsmarc** [comment]
Everyone agrees on making this change.

Steps to implement:
- Change the CASFRI codes in species_code_mapping and the qc prg3 lookup table to use the new coding system.
- Review all inventories for cases where we could add the variant in using our new code. Currently we are only aware of coastal Douglas-fir.

**Comment by edwardsmarc** [comment]
X is not a good character because the NFI coding system uses X to indicate hybrids. We could use # instead.

@MelinaHoule will figure out if this proposed new system can work for all our cases. There are some exceptions that will need to accommodated such as:

- Acer spp. could be: ACER_SPP_###
- Generic hardwood could be: HARD_###_###
- Region specific combinations of hardwood could be: HARD_###_#QC
- Or if there are multiple hardwood combinations in a region they could be: HARD_###_QC1, HARD_###_QC2 etc.

I also propose we add a description column to species_code_mapping.csv where we can define these exceptional cases. This can then serve as the documentation for the CASFRI species coding system which can be linked to from the readMe.

**Comment by MelinaHoule** [comment]
Those code are found in species_code_mapping but do not occur in NFI tree species list. Do we add them? Do we translate them using the existing generic spp.? 


CASFRI_code | Latin name | Proposed
-- | -- | --
ABIE_FIRM | Abies firma | ABIE_FIR_###
ABIE_PICE | Mix spruce, balsam fir | ABIE_PIC_###
BETU_MAND | Betula mandschurica var japonica | BETU_MAN_###
FRAX_PROF | Fraxinus profunda | FRAX_PRO_###
HARD_INTO | Intolerant Hardwood | HARD_INT_###
HARD_MOIS | Moist hardwoods | HARD_MOIS_###
HARD_NONC | Non commercial hardwoods | HARD_NON_###
HARD_TOLE | Tolerant hardwood | HARD_TOL_###
LARI_HYBR | Larix x marschlinsii | LARI_MAR_###
LARI_XMAR | Larix x marschlinsii | LARI_MAR_###
MALU_PUMI | Malus pumila | MALU_PUM_###
PICE_KOYA | Picea koyamai | PICE_KOY_###
POPU_CANA | Populus X canadensis | POPU_CAN_###
PRUN_CERA | Prunus cerasus | PRUN_CES_###
TILI_CORD | Tilia cordata | TILI_COR_###
TILI_PLAT | Tilia platyphyllos | TILI_PLA_###
UNCL_SUBS | Species unknown | UNKN_SPP_###

**Comment by edwardsmarc** [comment]
I would say we should add them and mention in the description column that they are not included in the NFI list.

**Comment by MelinaHoule** [comment]
By using the official Canadian species list, do we include in the species_code_mapping all codes found in the list?

The official NFI list has 292 tree species. CASFRI is using 194 codes.

**Comment by edwardsmarc** [comment]
Good question. I would say we add them, that way we don't have to consult the NFI list if we encounter a new species.

**Comment by MelinaHoule** [comment]
Some CASFRI tree species code were not found in NFI tree species list. I investigated the meaning of the code using the respective province manual. Here are the translation I fixed or deleted:

old   CASFRI code | Province | raw data | Scientifc name | Comment | NFI tree specie
-- | -- | -- | -- | -- | --
CARY_OVAT | ON | Hs | Carya Ovata | Mistake. Should have   been CARY_OVAV | CARY_OVA_###
PICE_RUBR | ON | Sr | Picea rubens | Mistake. Should have   been PICE_RUBE | PICE_RUB_###
PILI_AMER | PE | LI | Tilia | Mistake, Should have   been TILI_SPP. | TILI_SPP_###
POPU_BALS | BC | AC | Populus balsamifera | Mistake. Should have   been POPU_BALB | POPU_BAL_###
POPU_BALS | NT | Pb | NA | Code not found in   manual | NOT_IN SET
PRUN_PENN | ON | CP | Prunus pensylvanica | Mistake. Should have   been PRUN_PENS | PRUN_PEN_###
PEU_MENM | BC | FDC | P menzialis var.   menzialis | Mistake. Should have   been PEU_MENZ | PSEU_MEN_###

When forest inventory use species code not defined in the manual, do we translate it as NOT_IN_SET or as UNKN_SPP_### for unknown species?

**Comment by edwardsmarc** [comment]
I would use UNKN_SPP_### as the entry in the species_code_mapping.

NOT_IN_SET should be reserved as the error code that will be returned if the source value is not found in the species_code_mapping during the validation step.

**Comment by edwardsmarc** [comment]
Once #468 is closed, change all species lookup translations from 'casfri_species_codes' to 'nfi_species_codes'. Or rename 'nfi_species_codes' to 'casfri_species_codes' in the species table.

**Comment by edwardsmarc** [comment]
@MelinaHoule has updated qc_ini03_species_lookup to new codes.

Next step is for @edwardsmarc to run tests using new codes.
