### ISSUE TITLE
NL01 test translation fails randomly

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#454]
ERROR:  STOP ON INVALID TRANSLATION PARAMETER: Invalid parameter value passed to rule 'geoIntersectionInt(wkb_geometry='010300002032BF0D000100000018000000CC9620E0BBDB434102E973E1C0873F4110EB6F4CB7DB4341E827F7ADBA873F417A10A828B2DB43411C5EE223B6873F41E59E01C1ADDB4341CB1CB298B2873F41DC6FF0C1A9DB4341A0657674B4873F415D48D423A3DB43411B61509CB7873F4100BB77E3A0DB43413D23F041BE873F41DF271BA39EDB43415DF68FE7C4873F4167FBB21A9CDB43414DD8E361CC873F415143D0E19ADB43410CE62C36D3873F4184F2D29699DB434192A3E094DD873F41D942452799DB43419B2FF179E5873F4193D5D2E29CDB4341C22A892BEE873F411A201679A2DB4341BC1BFC29F8873F412F876636A5DB4341537B3A3DF8873F413CA31705A9DB434132648C8CF8873F4168F2B99BAEDB43414A1E0936F5873F416191FB20B3DB4341818072A3F1873F4116D24C19B5DB434181D686D2EB873F415A0E9E11B7DB434199399B01E6873F4144A14E59B8DB43418A1B6F9EDB873F415400B7E1BADB4341DDBF1B24D4873F41C22808DABCDB4341924E3053CE873F41CC9620E0BBDB434102E973E1C0873F41', 'rawfri', 'nl_photoyear', 'wkb_geometry', 'photoyear', 'GREATEST_AREA')' for attribute 'STAND_PHOTO_YEAR'. Revise your translation table...

**Comment by pedrogit** [comment]
This is actaully caused by engine [issue #222](https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/issues/222)

**Comment by edwardsmarc** [comment]
Works
