### ISSUE TITLE
Photo year for NB02 seems to be in the L1DATAYR and the L2DATAYR source attribute

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#460]
NB02 has 886715 STAND_PHOTO_YEAR values at -8888 (NULL_VALUE) and 96 at -9999 (OUT_OF_RANGE). THe values are taken from the DATAYR attribute, which is generally undefined.

However when we compare values that can be found in the NB02 L1DATAYR and the L2DATAYR attributes, they are very frequently the same values as the NB01 DATAYR attribute. 

There are also cases where L1DATAYR and L2DATAYR differs from each other e.g. L1DATAYR = 2009 and L2DATAYR = 2015 and some other cases where L2DATAYR is set but not L1DATAYR (=0).

This query help finding thoses cases:

SELECT l1datayr, l2datayr, count(*) nb
FROM rawfri.nb02
WHERE l1datayr != l2datayr
GROUP BY l1datayr, l2datayr
ORDER BY l1datayr;

So I guess the translation table should use L1DATAYR and L2DATAYR as source value. Note that we have a case here where we have two different photo year per stand when CASFRI supports only one.

Now what to do when L1DATAYR and L2DATAYR are different and  mostly when L1DATAYR is = 0 but not L2DATAYR ?

Your input is welcome.

**Comment by edwardsmarc** [comment]
I would assume 0 is the same as null so if L1DATAYR = 0 and L2DATAYR is a valid value, we should use L2DATAYR.

When they both have valid values, that is tricky. Any info in the manual about the definitions of these attributes?

**Comment by pedrogit** [comment]
In the data dictionary DATASRC is the "Source of stand attribute data" and DATAYR is the ``Year of stand attribute data`. Nothing about L1DATAYR  and L2DATAYR themselves.
