### ISSUE TITLE
Check for cases where height is not ordered by LAYER

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#463]
For example, are there any cases where LAYER 2 height is greater than LAYER 1 height.

We know this is possible in ON02:
`SELECT count(*) FROM rawfri.on02 WHERE oht<uht`

We usually assign LAYER based on the structure of the source data. For example ON02 and AVI have a set of attributes for the overstory and another set of attributes for the understory. We simply assign overstory to LAYER 1 and understory to LAYER 2. But we don't actually check that the overstory has a greater height.

This relates to the definition of LAYER and the ordering of LAYERs within CASFRI. The specs state that LAYER 1 is always the tallest layer, but we don't currently check for that.

What do we in cases where height is not correctly ordered?
Should we be checking height values when assigning LAYER values?

**Comment by pedrogit** [comment]
Is it possible to investigate those ON02 cases to see if they are errors or if they correctly implement some sort of standard rule? If they are errors maybe we can fix them (by assigning them the right LAYER). If they are no error then we might want to revise our own concept of layer.......

**Comment by edwardsmarc** [comment]
I'll look into this today. 

My concern is that you could have a regenerating tree species that is recorded in the overstory slot, that could actually be shorter than the understory veg. The question for us then becomes, do we follow our strict rule of naming the layers in order of height, or do we accept the order provided by the source.

I'll check all the FRIs we have translated so far. I think they all adopt this idea of slots, where they have already assigned layer 1, 2, 3 etc. Or overstory and understory. We simply take the values from each slot but then rename the layers that are actually present starting from 1.

It might be that we just need to refine our definition of how LAYER is assigned.

**Comment by edwardsmarc** [comment]
Here's some comments having looked at the source data and the manuals. Based on this information we have many cases where LAYER 2 height is greater than LAYER 1 height. Most of these are in BC and NB. No explanation for any of these rows and not clear if they are erroneous or if the manuals just don't define layer very well:

ON
- 2 layers
- Attributes are repeated for overstorey and understorey.
- Doesn't explicitly state the overstorey has to be taller than understorey.
- But does describe overstorey as the uppermost layer: "The overstorey height attribute contains the average height in meters of the dominant and co-dominant trees of the leading species in the stand (or in just the uppermost canopy layer if the stand canopy contains two or more distinct layers)."
- There are 231 polygons in ON02 where understorey height > overstorey height. Of those, 38 polygons do not follow the above rules for distinguishing layers (neither height nor age differences between layers are met).

BC
- 2 layers
- The entire source table is repeated for each layer. We combine these into one wide table during loading.
- "The VRI simply lists each layer present from tallest to shortest."
- However, many L2 are taller than L1. No explanation for this.

AB
- 2 layers
- Attributes are repeated for overstorey and understorey.
- Doesn't explicitly state the overstorey has to be taller than understorey.
- "In polygons where tree species are present in the overstorey and understorey, AVI requires the average height of the top layer to differ from the average height of the lower layer by at least 3 m."
- Only one row in AB06 and AB16 where understorey height is > overstorey. I'm guesing its an error.

NB
- 2 layers
- Can't find any explanation of how layer is assigned in the FRI. L1 is just described as the 'dominant' and L2 as the 'secondary' layer
- Many rows in both nb01 and nb02 where L2 height > L1 height

NT 
- 2 layers
- Described as "dominant storey" and "under storey" but no mention of how these are defined.
- 7 rows in nt01 and 38 rows in nt02 where understorey height > overstorey

SK SFVI
- 3 layers
- Always in correct height order

**Comment by edwardsmarc** [comment]
Here are some possible solutions to this issue:

Option 1. We follow our general principle of reporting the data as it is presented. We leave all LAYER translations as they are. We edit the specs to state that LYR LAYER iterates from the topmost to lowest canopy layer, as defined in the source data. We also acknowledge that the source data gets this wrong in many cases which results in "understorey" layers being taller than "overstorey" layers.


Option 2. We think that LAYER should be strictly enforced such that LAYER numbers should always progress from tallest to shortest in CASFRI.

Option 2a. We edit the existing LAYER assignment method to be based on height instead of simply grabbing the data from the 'overstorey' or 'understorey' slots. This would require all LYR translations to first order the heights of the available layers, then select the correct source value to run through the translation function based on the layer being processed. We could probably use the minIndex***() and maxIndex***() functions for this. We would only need to apply them in cases where the source layers and not already ordered by height (BC, NB, NT, ON).

Option 2b. We assign LAYER to the translated database by ordering based on HEIGHT_UPPER as a post-translation assignment.

**Comment by edwardsmarc** [comment]
Based on the following comment from JC, it seems option 2 (probably 2a) might be our best path forward:

"You are correct in that the tallest is always layer one. There are two situations for Layer 1 being taller than Layer 2. The first is there could have been an attribute listing error in the original data; however, this would have been a minor situation because there is an error check for this in the mandatory validation procedure. The second is there may be confusion with Layer Rank (order of importance). In this case Layer 2 could have been ranked 1 (considered more important than Layer 1). If you go with Layer 1 as always the tallest and so on for subsequent layers, then that would eliminate the problem."

**Comment by edwardsmarc** [comment]
Proposal for new function to calculate LAYER in LYR tables for inventories where understorey can be taller than overstorey (we could also just use this for all LYR LAYER calculations).

Currently we use:
`countOfNotNull(L1, L2, max_return_value)` where max_return_value is set to 1, or 2 corresponding to the layer being translated. The function counts the number of non-null values then returns the lower of either count or max_return_layer.
- This method does not account for height, it assumes that the arguments are already ordered by height (i.e. L1 is taller that L2). 
- In the scenario that L2 is taller than L1, this function would still return LAYER = 1 for L1 and LAYER = 2 for L2. Not the desired behavior.

New function:
`reorderGetIndex({L1_sp1, L2_sp1}, {L1_height, L2_height}, source_index_to_translate)`
- Record the species value corresponding to the source_index_to_translate being translated (this would set to the 'layer' value in the VIEW, set by attribute_dependencies). If it's NULL, there is no layer to process, return NULL. This case should be filtered out by ROW_TRANSLATION_RULE.
- Remove any NULLs from the species string list, and their corresponding heights from the heights string list.
- Reorder the species string list so they are in height order.
- Return the index of species being translated.
- Can add check that string lists are same length.
- These arguments assume a single attribute can be used to decide if layer is present (i.e. sp1). Check if this works in all inventories, if not, might need to switch to using string lists for each layer. Will then need to write multiple signatures to deal with different numbers of layers (same as countOfNotNull does).

What to do if height values are null or 0: set nulls to zero so they are always the bottom layer.
What if height values are tied: maintain original order. This needs to work in cases where only a subset of the height values are tied. Copy code from TT_qc_prg5_species_code_to_reordered_array() to do the ordering.

For NFL we can probably keep using countOfNotNull(), this is assuming we always want to report NFL layers below canopy layers. We don't have any cases where NFL rows would have height values that can be greater than a LYR height value.

For BC we would have to make a custom function to first calculate the height values for each layer then pass them to reorderGetIndex().

**Comment by pedrogit** [comment]
This function looks very similar to MinIndexCopyText() and MaxIndexCopyText() where you return the value corresponding to the samllest and the biggest values. Maybe it could become even more generic by being able to specify which one we want: 'MIN' (which is the same as MinIndexCopyText()), 2NDMIN, 3RDMIN, MAX (which is the same as MaxIndexCopyText()).

Make sense?

**Comment by edwardsmarc** [comment]
Agreed this could replace MinIndexCopyText() and MaxIndexCopyText(). We'd need to add another argument 'tiesRule' to decide which value to select in the case of ties.

**Comment by edwardsmarc** [comment]
We should add a constraint that checks that all LYR layers are in height order from tallest to shortest.

Currently this constraint will fail until we apply this rule to the translation tables.

**Comment by edwardsmarc** [comment]
Actually looking at this closer, it's not as simple as making  MinIndexCopyText() and MaxIndexCopyText() more generic.

The function we need for assigning LAYER needs to order the height values, but first it needs to drop any height values that correspond to a null species value. This is an important distinction, we only want to order height values for the layers that are actually present in the polygon.

Another important point is that we need to be able to define whether a layer exists based on numerous attribute values that can be tested for notNull. This is the same functionality we use in countOfNotNull().

I think this is so specific it should be a CASFRI helper function just used for assigning LAYER. I'll attempt to describe the function again:

```
layer_translation(heights _stringlist_, layer1NotNull _stringlist_, layer2NotNull _stringlist_, getIndex int)
layer_translation(heights _stringlist_, layer1NotNull _stringlist_, layer2NotNull _stringlist_, layer3NotNull _stringlist_, getIndex int)

etc. with signatures to support 6 layers
```
- heights - stringlist of height values for each layer
- layer1NotNull - stringlist of values to test for notNull. If any are notNull then the layer corresponding to the first height value is present. Species values are usually used here.
- layer2NotNull - stringlist of values to test for notNull. If any are notNull then the layer corresponding to the second height value is present.
- layer3NotNull etc. etc.
- getIndex - This will be set to the _layer_ value from the attribute dependencies table. The height values need to match the order of the notNull stringlists, and the order of the layers in the attribute dependencies table. So the row with layer = 1 in attribute dependencies needs to be first in the _height_ stringlist and correspond to layer1NotNull

1. Construct a testArray iterating for the number of layers being processed - e.g. [1, 2, 3]
2. Check length of _heights_ stinglist matches the length of testArray.
3. Run each notNull test. If layer1NotNull is FALSE, remove the first height value from the _height_ stringlist, and remove '1' from testArray. Repeat for each notNull test.
4. Order the testArray by their corresponding height values. If there are ties, maintain the original order from the testArray.
5. Return the index of the getIndex value in the testArray.

Any inventories where height is not numeric will need their own wrapper that first converts the height code to a numeric, then passes the heights to layer_translation().

BC will need to calculate the heights using its weighted averaging function then pass them to layer_translation() in a wrapper.

We have 3 options for the NFL LAYER translations:
1. Add NFL into layer_translation() and hardcode their height values to -1, -2 etc. This will make sure they are always reported in the same order, and always below the LYR layers.
    - The problem with this is that determining NFL layer presence is often a matchList test and not a notNull test. This has caused us to write many custom versions of countOfNotNull() where NFL layer is tested using matchList.
    - **1a**. We could replicate this here and have inventory specific versions of layer_translation() with inventory specific NFL tests.
    - **1b**. Or we could make a single large function, taking inventory_id as an argument and run all the NFL tests internally.
2. The other option is leave NFL translation as it is using countOfNotNull() and the inventory specific versions of countOfNotNull that we've already written. As long as the string lists of values to test with notNull are the same between the layer_translation() function in the LYR table, and the countOfNotNull() function in the NFL table, then the results will be correct.

**Comment by edwardsmarc** [comment]
New function will only be applied in lyr tables for inventories that have >1 LYR layers. Otherwise we can just stick with the countOfNotNull() functions we had before where NFL will always be reported below LYR.
