### ISSUE TITLE
QC05 has 289 rows with missing info

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#465]
Rows have a cl_age value but sup_eta_ess_pc and inf_eta_ess_pc are null.

All these rows are labelled as using the AIPF standard so they get included in QC05 during loading. But in fact they are actually using the INITIALE standard. The result is that these rows all get a row in the CAS table indicating SINGLE_LAYERED, but they don't have any rows in the LYR table.

Temporary fix is to change the ROW_TRANSLATION_RULE for QC05 LYR table from:

`notEmpty(species_1)`

to

`isLessThanLookupDouble(layer, cl_age, 'translation', 'qc_standstructure_lookup', 'source_val', 'num_of_layers', TRUE)`

as used in qc03 and qc04. This means all valid cl_age values will get a LYR row. So these rows will get a CAS entry labelled as SINGEL_LAYERED and a LYR row with species values labelled as NULL_VALUE.

We expect these rows will get fixed in future inventories.

**Comment by edwardsmarc** [comment]
Q for @pedrogit:

This issue causes constraint 4.39 to fail because of -3333 values. This happens because all values in these rows are NULL so the LAYER translation rule fails.

We can catch these rows (by adding validation rule notEmpty(sp1)) and return an error code. What should it be? NULL_VALUE?

We would also need to allow this error code in constraint 4.39.

**Comment by pedrogit** [comment]
If all the values are NULL doesn't it mean there is no LAYER? So LAYER = 0?

**Comment by edwardsmarc** [comment]
There is a mismatch between the age_cl attribute which says there are LYR layers, and the actual species columns which are NULL.

We use the cl_age attribute to get the NUM_OF_LAYERS reported in the CAS table. Usually the NUM_OF_LAYERS from cl_age matches the species data in the table. But in these rows species are all NULL.

So our options are:
1. We drop these LYR rows using ROW_TRANSLATION_RULE. Problem here is we then have CAS rows with NUM_OF_LAYERS = 1 and STAND_STRUCTURE = SINGLE_LAYERED, but no matching LYR record.
2. We keep the LYR rows and report error codes (probably NULL_VALUE) for attribute LAYER. Problem here is that NULL_VALUE is not a meaningful LAYER value.
3. We could also use a validation rule to catch these rows and assign LAYER = 1 which is the correct value we need to assign. It's ugly because we a using a validation to do a translation, but I think it's the only way to get LYR LAYER = 1.
4. Last option would be to drop these polygons completely either using a ROW_TRANSLATION_RULE in the CAS table, or during loading.

**Comment by pedrogit** [comment]
Seems that cl_age is not sufficient to determine NUM_OF_LAYERS. If the translation would also take the other attributes into account then those rows would get NUM_OF_LAYERS=0 and we would not try to create a LYR row for them. Make sense?

**Comment by edwardsmarc** [comment]
OK seems like we need to drop cl_age for qc05. This would deviate from how qc03 and qc04 are translated, but I think that's OK given that only qc05 will be used moving forward.

Changes needed:
- qc_countofnotnull should count not null sup_eta_ess_pc and inf_eta_ess_pc, and any NFL values. This will changes how NUM_OF_LAYERS and NLF LAYER is assigned.
- STAND_STRUCTURE should use IfElseCountOfNotNull({sup_eta_ess_pc, inf_eta_ess_pc}, 2, 1, 'SINGLE_LAYERED', 'MULTI_LAYERED')

**Comment by edwardsmarc** [comment]
Update:
Since all co_ter values are valid NFL codes in qc05, we don't need custom countOfNotNull and hasCountOfNotNull functions. We can just count the number of notNull attributes using the regular countOfNotNull and hasCountOfNotNull functions.

**Comment by edwardsmarc** [comment]
Done.

Check constraint 4.39 passes before closing this issue

**Comment by edwardsmarc** [comment]
Constraint passes
