### ISSUE TITLE
qc_standstructure_lookup is missing some cl_age values from QC05

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#466]
Values not included that appear in QC05:

90VIN
VIN90
VINVI

**Comment by edwardsmarc** [comment]
@MelinaHoule - I just pushed these changes. Can you check the values I entered are correct. I added them to the bottom of the table.

**Comment by MelinaHoule** [comment]
The values entered are correct and follow the definition given by the manual.
