### ISSUE TITLE
Translation of dead species

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#467]
For species translation, when a specie is identified as dead, should it be translated using the same code as the alive one. For example, in NB, their are code for merchantable dead fir and merchantable dead spruce. We translated them as ABIE_SPP_### and  PICE_SPP_###. As the ones that are alive. 

Do we keep it like that or do we add some new codes to distinguish the deads from the alives

**Comment by edwardsmarc** [comment]
I think we should add a new code to indicate they are dead.

**Comment by MelinaHoule** [comment]
I propose adding ABIE_SPP_DEA and PICE_SPP_DEA to species_code_mapping and will comment the addition. 

Agreed?

**Comment by prvernier** [comment]
Are we limited to 3 characters? Why not ABID_SPP_DEAD?

**Comment by MelinaHoule** [comment]
We agreed to follow the NFI species list and map their standard (issue #453). 

The species structure is now Genus (4 char), Species (3 char), Var (1-3 char). Parsing mask used between elements is "_". Missing info is filled with '#' characters.

**Comment by prvernier** [comment]
Ah, yes, I remember. Thanks.
