### ISSUE TITLE
Drop SPECIES_2 interpretation from NS

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#469]
@prvernier  - in the NS translations there are some rules specific to the understorey species layer which are not listed in the manual. I'm guessing these cam from Cosco or the Perl code. They are listed under "species (layer 2)" in this issue:

#367 

Can you confirm where these rules came from? @MelinaHoule has suggested we should drop them because they are interpretations and  not explicitly stated in the source data.

@MelinaHoule - do you think we should still report SPECIES_1 for the understorey layer as either HARD_UNKN or SOFT_UNKN based on the source values of S, SH, HS and H?

**Comment by MelinaHoule** [comment]
Yes,  I propose we intregrate understory species into specis_code_mapping AS HARD_UNK_### and SOFT_UNK_###, but we drop the translation of species 2. 

I think we should stick with information given from formal source. I consider that deriving species_2 from species_1 is outside of our task. CASFRI translate information that is there.   

For example, when understory code is H ( <20% softwood, which happen), we're making the assumption that species 2 is S (80% softwood). If that was really  the case, don't you think the province would have put species 1 as S?  

So I don't think our assumption make sense anyway.

**Comment by edwardsmarc** [comment]
I can think of one other case where we have made similar extrapolations based on rules that JC developed that were not included in the manual. That was SK01 where we did quite a bit of work to figure out the rules. I think that case it a bit different because that is an old standard where we would have lost a lot of information.
