### ISSUE TITLE
NL01 - many polygons where photoyear = 0

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#478]
In the NL photoyear file there are many polygons where photo year is 0. These are mostly areas outside the inventory but some polygons intersect these areas leading to STAND_PHOTO_YEAR values of zero in CASFRI.

Ideally we would would catch these cases with a validation function. I could write geoIntersectionMatchList() which would allow us to catch the zero's and return an error code. However this is a costly solution because it requires running every intersection twice, once for the validation and once for the translation.

Is there any other solution here?

**Comment by pedrogit** [comment]
Add a "treatZeroAsNULL" parameter to TT_GeoIsValid()

**Comment by edwardsmarc** [comment]
Actually we are already using the geoIntersects() validation rule so the intersection is already being done twice.

Best solution is therefore to replace geoIntersects() with geoIntersectsMatchList().

**Comment by edwardsmarc** [comment]
Correction, we need geoIntersectionGreaterThan().

Runs geoIntersectionText(), passes the interseting photo year to isGreaterThan()
