### ISSUE TITLE
AB ECO table

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#488]
First line of TT_avi01_wetland_code is:

`WHEN moisture='w' AND nonfor_veg!='NA' THEN NULL`

but there are no NA values in the nonfor_veg column.

There are NULLs, but catching all cases where cells are not NULL would negate the following lines.

**Comment by edwardsmarc** [comment]
Other than the above comment, functions appear to work.

Remaining is ECO_SITE attribute.

**Comment by prvernier** [comment]
That first line should be dropped - it's not needed.

**Comment by prvernier** [comment]
ECO_SITE wasn't used in the Perl code. There's some mention of it for PHASE3 Alberta data but not for AVI, at least as far as I can tell. Maybe Steve or @MelinaHoule have an idea.
