### ISSUE TITLE
Name source value column in lookup table "source_val".

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#49]
This is necessary since the TT_lookup() code check for the first column but after loading with ogr, the first column is the ogc_fid one, not the one containing the value to match.

**Comment by prvernier** [comment]
I've changed the first column name to source_val although I'm not sure why fri_value was a problem. Won't source_val still be after ogc_fid?

**Comment by edwardsmarc** [comment]
source_val matches the readMe documentation. We don't want casfri specific col names like fri_val. The engine will now look for the source_val column instead of just using the first column since ogc_fid is always the first column after loading with ogr.

**Comment by prvernier** [comment]
Makes sense.
