### ISSUE TITLE
NT03 - Acquisition of the new NT v4 inventory

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#491]
Following conversation with the territories about species description missing in NT01, they sent us their new inventory (v4). We previously had v2 and v3. Data, manual and license agreement will be stored under NT/NT03.

**Comment by pedrogit** [comment]
While we are in close contact with the data provider, it would be important to make sure the new inventory has valid photo years.

**Comment by MelinaHoule** [comment]
NT03 has valid photo years. Photo years are given at the polygon level. There are no polygon with missing photo year.

**Comment by MelinaHoule** [comment]
NT03 is the same inventory as NT02, but the territory fixed many errors in the database over the last 5 years. We will thus use NT03 for CASFRI v5 release.
