### ISSUE TITLE
Write .bat conversion script for NT03

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#493]
NT03 is the same inventory as NT02, but with errors fixed. The structure of the data is not the same as NT02 that required a join between the geometry and attributes table. It is a geodatabase with 2 tables: inventory extent and inventory data (NT_FROCOV). Thus, a new loading script will be required. Once the loading script is created. We will upload the data and test if translation tables created for NT02 can be used.

**Comment by edwardsmarc** [comment]
Labelling this as medium priority as it is not a deliverable in the contract.

**Comment by edwardsmarc** [comment]
@MelinaHoule do you have any info on what errors were fixed? TheNT03 appears to have more errors in terms of duplicated polygons that NT02! (#580)

Just curious, no need to contact them if you don't already have this info.

**Comment by edwardsmarc** [comment]
.bat still needed
