### ISSUE TITLE
PC02 -Need custom helper function to translate ECO table

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#495]
PC02 has 7 layers. Cosco rules use 2 fields (v#pcm, v#str) to derive the four wetlands attributes (WETLAND_TYPE, WET_VEG_COVER, WET_LANDFORM_MOD and WET_LOCAL_MOD). # should be replaced by value 1 to 7 that represent the layer number. That means, in the original table attributes v1pcm, v2pcm, v3pcm,.... are present. 

The rules are:
if v#pcm = 7 or 98, eco attributes = SWAMP, OPEN_NON_TREED_FRESHWATER, NO_PERMAFROST_PATTERNING, SHRUB_COVER (SONS)
if v#pcm = 1,2,3,4 or 99, eco attributes = MARSH, OPEN_NON_TREED_FRESHWATER, NO_PERMAFROST_PATTERNING, GRAMINOIDS (MONG)
if v#pcm = 20, eco attributes = SWAMP, WOODED, NO_PERMAFROST_PATTERNING, NO_LAWN (STNN)
if v#pcm = 17, eco attributes = FEN, OPEN_NON_TREED_FRESHWATER, NO_PERMAFROST_PATTERNING, GRAMINOIDS (FONG)
if v#pcm = 18, eco attributes = SWAMP, OPEN_NON_TREED_FRESHWATER, NO_PERMAFROST_PATTERNING, SHRUB_COVER (SONS)
if v#pcm = 19 AND v#str = N, eco attributes = FEN, WOODED, NO_PERMAFROST_PATTERNING, NO_LAWN (FTNN)
if v#pcm = 19 AND v#str = P, eco attributes = BOG, WOODED, NO_PERMAFROST_PATTERNING, NO_LAWN (BTNN)

**Comment by edwardsmarc** [comment]
Since the ECO table does not have a LAYER attribute, we do not need to assign ECO attribute to the layer they came from (1-7). We should just write a function that loops over the source layers and runs the logic above. As soon as a valid wetland row is found the 4-letter wetland code should be returned.

@MelinaHoule - This assumes there will only ever be one wetland layer to return. Is it possible to have wetland entries for multiple layers in a polygon? If so, what should we do? We can only return one ECO value per polygon.

**Comment by MelinaHoule** [comment]
_This assumes there will only ever be one wetland layer to return. Is it possible to have wetland entries for multiple layers in a polygon? _

According to the manual, multiple ECO value can be identified in one polygon in PC02: "Each polygon can have up to seven vegetation plant communities described of which any number can be wetland types". I looked at the data to confirm that can happen. The manual specify the translation rules, but not how to deal with multiple ECO value. Vegetation plant communities have a percent assigned to them. Maybe we could report the one with the highest percent?

**Comment by edwardsmarc** [comment]
The other option would be to change the schema and add a LAYER attribute to the ECO table.

Maybe @pedrogit has thoughts on this?

**Comment by pedrogit** [comment]
They are horizontal layers right? This is why there can be many different ECO status per polygons. Then yes there should be a way to refer to the layer in the ECO table. (Another argument in favor of the new schema).

**Comment by edwardsmarc** [comment]
OK so we should add LAYER to all ECO tables and to the specs. All other translation tables would assign LAYER = 1.
PC02 would run the translation table 7 times, so there would 7 rows in attribute dependences.
The custom function would apply the logic above and the v#pcm attribute corresponding to the layer being translated would be provided as the function source value.

@edwardsmarc will apply these changes.

**Comment by edwardsmarc** [comment]
Add LAYER to all ECO tables
