### ISSUE TITLE
PC02 translation of Stand_Structure

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#497]
According to Cosco manual, stand_structure should be translated as unknown. Previous version of CASFRI used to translate Stand_Structure as Horizontal. By looking at the data and manual, each polygon can have up to 7 biophysical vegetation value (meadow, willow, aspen, white pine, wet muskeg, ... ). We also have 3 value that represent percent of covers (pcnt1, pcnt2, pcnt3). Percent of cover add up to 100%. I was expecting getting only one biophysical vegetation value if pcnt1 = 100%, but it isn't the case. pcnt1=100% gets sometimes 4-5 biophysical vegetation  and the values are really different (meadow with pine). Also sometimes we have polygons with only 1 biophysical vegetation value but has 3 value of percent of covers. Hard to know how percent of covers are related to biophysical vegetation, but they don't match.

Polygons also have up to 7 layers and each one can have up to 4 species. percent of covers do not match layers within a strata or species either.

Should we translate STAND_STRUCTURE as HORIZONTAL or should we put it as UNKNOWN?

**Comment by edwardsmarc** [comment]
We can only assign HORIZONTAL if we know the percent of each horizontal component which gets reported in STRUCTURE_PER. It sounds like we don't have that information. So I would use UNKNOWN_VALUE for STAND_STRUCTURE.

**Comment by MelinaHoule** [comment]
Close with commit 8c497723bf4a443371155f1d792d04f899c3e158

**Comment by MelinaHoule** [comment]
Forest inventory manual from PC02 has really short field description which could have cause a misinterpretation of the data. In the Cosco manual, field "vegct" is used to determine the number of layers. Nothing describes STAND_STRUCTURE. Definition of "vegct" is:  Identifies number of  vegetation plant community. Valid values are 0 to 7. Each vegetation plant community has a percent assigned. They add up to 100%. I think vegetation plant community represent the horizontal structure of the polygon. For example, one polygon has vegct=4. 

v1pcm: wet muskeg 30%
v2pcm: shrub muskeg 30%
v3pcm: black spruce on sphagnum 20%
v4pcm: black spruce dominated forest 20%

We could thus discrimated between SINGLE STAND_STRUCTURE (vegct=1) and HORIZONTAL STAND_STRUCTURE (vegct >1) using the number of vegetation plant community. Each one would get a STRUCTURE_PER value and a LAYER value. Each vegetation plant community has vegetation species assigned (1-4 species) with rules to assign %. 

Does that make sense?

**Comment by edwardsmarc** [comment]
Yes. In polygons with horizontal structure, the LAYER number indicates the sub-polygon, or sub-component. i.e. all the LAYERs are next to each instead of on top of each other.

I think your proposal is the correct way to do it.

The only decision I see is for vegct=1. We could either label that as a SINGLE_STORIED stand structure, or we could assign HORIZONTAL with STRUCTURE_PER=100. I would lean towards using HORIZONTAL because this is clearly a horizontal schema that doesn't have any vertical structure (is this correct? There is never any vertical structure?).

**Comment by MelinaHoule** [comment]
That is correct. There is no indication of any vertical structure.
