### ISSUE TITLE
Constraints - Do not allow error codes for STAND_PHOTO_YEAR

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#498]
Many rows where STAND_PHOTO_YEAR returns an error code.

For example in NL01, there are 5,116 rows that do not intersect with the photo year table and return -9999.
In QC04 there are 102,011 rows that have NULL photo year and return -8888.

Constraint requires STAND_PHOTO_YEAR > 0

**Comment by pedrogit** [comment]
Right. I will update the constraint as soon as my complete translation finally finishes.

**Comment by pedrogit** [comment]
Constraint was relaxed and info about erroneous STAND_PHOTO_YEAR was reported to #248. Closing.
