### ISSUE TITLE
Constraint 3.14 - ECO_SITE is not always available

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#499]
Constraint 3.14 requires that ECO_SITE is not NOT_APPLCABLE.

This attribute is only copied when available in the source data. Many inventories do not have it. I think NOT_APPLICABLE is the correct error code to return here so it should be allowed in the constraints.

**Comment by pedrogit** [comment]
So is there any other kind of constraint we can apply to ECO_SITE?

**Comment by edwardsmarc** [comment]
Remove the constraint. It's similar to LAYER_RANK in that we only copy the value when available. Usually it is not available.
