### ISSUE TITLE
PC02 - DST translation and assignation of LAYER

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#500]
In PC02, polygons are defined using 3 level of geological stratification and 7 level of plant communities. Both within their respective categories sum up to 100%. Plant communities are not nested within geological stratification. There is no indication how they are related. 

Disturbance (OTHERS, SLIDE, FIRE) are derived using 3 fields related to geological stratification (eros1, eros2, eros3) and 7 fields related to the plant communities (v1pcm, v2pcm, v3pcm, ...). CASFRI retains only 3 disturbances. 

How to prioritize the order between geological stratification and plant communities? How to assign LAYER if layer is derived from plant community as described in issue #497?

**Comment by edwardsmarc** [comment]
Do you mean LAYER in the DST table?

Unless the disturbance can be assigned to a specific horizontal component (it sounds like this is not possible since you state that geological and plant community are not linked), then DST LAYER should just be UNKNOWN_VALUE.

i.e. the disturbances are recorded at the polygon level. We don't know which horizontal components they affected.

**Comment by MelinaHoule** [comment]
From geological stratification, Cosco extract SLIDE and OTHER disturbances. From plant communities, Cosco extract FIRE. 
If 4 disturbances are recorded in one polygon, all  with unknown year, how to prioritize between disturbance coming from geological stratification and plant communities. The translation rules will need to look into 10 fields for specific values. Do we prioritize FIRE over SLIDE and OTHERS? Year of disturbance is always unknown.

**Comment by edwardsmarc** [comment]
I would say we prioritize FIRE.

**Comment by MelinaHoule** [comment]
Let's create MapTextCoalesce(). It will run multiple individual mapText calls and returns the first non-null value. That's what we want but we need to return the first value for DIST_TYPE_1, the second non-null value for DIST_TYPE_2, and the third for DIST_TYPE_3. We can then simply provide the source columns in the order we want to prioritize them. So: FIRE, then geological attributes. The first valid DST type will be returned for DIST_TYPE_1, the second for DIST_TYPE_2 etc.

**Comment by edwardsmarc** [comment]
Note: the validation rule here would use matchList() for each of the 10 disturbances individually. The _acceptNull_ argument for the first 9 calls would be set to TRUE. The 10th call would be set to FALSE. This way if a NULL value is encountered it doesn't report an error code, it simply moves on to the next validation. Only if all 10 matchList calls are NULL will the error code be reported. We can use this to make sure at least one disturbance exists before running the translation.

**Comment by edwardsmarc** [comment]
Function MapTextNotNullIndex() is now written. See the engine documentation for its use. It runs up to 10 mapText calls internally and then returns the result matching the requested index.

**Comment by MelinaHoule** [comment]
Changes in validation rules. We used  HasCountOfMatchList().

It's similar to mapTextNotNullIndex(). It runs all 10 matchList calls internally, counts how many returned TRUE, then compares the number of TRUEs to the count argument (using '=' if exact is TRUE, and '>=' if exact is FALSE). Default error code is INVALID_VALUE.  If HasCountOfMatchList() found only 1 disturbance, on dist_type_2 validation doesn't pass, then gets me INVALID_VALUE. But in fact, their is not dist_type_2. The value is not invalid. It just doesn't occur. I thus force the validationerror code it to be NOT_APPLICABLE. 

Close with commit 2c4ac77b5f2d6d42985444257a85b60d1a4d81b8
