### ISSUE TITLE
Uncommon error codes are used only in QC

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#504]
See https://github.com/edwardsmarc/CASFRI/commit/b861555d10c4c2a365cab35bfb5cc9d498868ada

UNUSED_VALUE is used for a SOIL_MOISTURE value that doesn't fit into the specs. We could replace it with NOT_IN_SET.

WRONG_TYPE does not seems to be returned by any validation function. To be checked.

**Comment by edwardsmarc** [comment]
Changed UNUSED_VALUE to NOT_IN_SET. Changed a WRONG_TYPE to INVALID_VALUE.

WRONG_TYPE is a valid error code for isInt() and isNumeric() so can occur in the translated database.

I fixed a couple of bugs by searching for WRONG_TYPE error codes in the translated tables.
