### ISSUE TITLE
PC02 - Should alder and willow translated in NFL or LYR?

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#506]
In PC02, LYR is translated according to species fields (v1sp1, v1sp2, v1sp3, ..). Alder and willow are valid species and are translated by the species_code_mapping table. NFL values are translated using the vegetation structure fields (v1str). Value ST has a translation rule (TALL_SHRUB), but always have species code associated with it. 90% are willow  and alder. The polygon has a HORIZONTAL structure, but in this case, information belongs to the same layer. Species mentionned allow to specify what type of tall shrubs there are. Which one should be prioritized? Should we translate those layers as LYR when species are specified or should we drop willow and alder from the species_code_mapping in the case of PC02 and consider those layer as NFL TALL_SHRUB?

**Comment by MelinaHoule** [comment]
When vegetation structure = TALL_SHRUB (species Alder and Willow),  height is 0-9m. There is no info on productivity or if a polygon is forest / non_forest (probably because of the horizontale structure).

**Comment by edwardsmarc** [comment]
I think our options are:

1. Report as NFL, we can retain the height info because NFL table records height. But we would lose the species info.
2. Report as LYR, we retain species info and height info, but we lose the TALL_SHRUB label. We can however record PRODUCTIVITY_TYPE as ALDER. (PRODUCTIVITY would be UNKNOWN_VALUE).

I would go with option 2, but document this decision in the description column for NFL NON_FOR_VEG.

**Comment by MelinaHoule** [comment]
To apply ALDER, I will need to use the validation function MatchList() and translation function MapText(). Should I change the default error NOT_IN_SET to NOT_APPLICABLE for all the others that are not ALDER?

**Comment by edwardsmarc** [comment]
For PRODUCTIVITY_TYPE?

Use: |NOT_APPLICABLE

**Comment by edwardsmarc** [comment]
And for PRODUCTIVITY, I would use UNKNOWN_VALUE for the alder rows, and NOT_APPLICABLE for everything else.

You could do that using validation:

notMatchList(sp1, {'alder', 'willow' etc.}|UNKNOWN_VALUE);false(|NOT_APPLICABLE)

**Comment by MelinaHoule** [comment]
Closed with issue 9b6dfb24d42882ffcc98f329b84b154e941f1f9a
