### ISSUE TITLE
PC01 - LYR Need custom function to translate SPECIES_PER

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#511]
In PC01, species_per is translated according to number of species and species value. Species value are concatenated in one field. 
(Layer1_species: PM (1 species), LL (1 species), PMLL (2 species), LLPM (2 species), LLPMBP (3 species)....

If 1 species, species_per = 100%
If 2 species and species are pine (PB) and black spruce (PM),  species_per 1st=60% and 2nd=40%
If 2 species with any other combinations, species_per 1st=70% and  2nd=30%
If 3 species, any combination, species_per 1st=50%, 2nd=30% and 3rd=20%

**Comment by edwardsmarc** [comment]
Will need a validation rule to catch case where c1spec is 0. These look to be NULL values.
notMatchList(c1spec, '0'|NULL_VALUE)

**Comment by edwardsmarc** [comment]
In addition to catching the zero values as NULL_VALUE, all species and species_per validations should use LengthMatchList to check the species being translated actually exists. Error code should be NOT_APPLICABLE. This is similar to ON02 and QC04.

e.g.
SPECIES_1: lengthMatchList(species_1, {2, 4, 6}, 'TRUE'|-8887)
SPECIES_2: lengthMatchList(species_1, {4, 6}, 'TRUE'|-8887)
SPECIES_3: lengthMatchList(species_1, {6}, 'TRUE'|-8887)

**Comment by edwardsmarc** [comment]
Added function pc01_species_per_translation(val, speciesNumber)

e.g.
pc01_species_per_translation(species_1,'1')
pc01_species_per_translation(species_2,'2')
pc01_species_per_translation(species_3,'3')

**Comment by MelinaHoule** [comment]
Close with commit e0e6c545ee148a6035798e0ccd5e2b0f2be51094
