### ISSUE TITLE
PC01 - LYR ORIGIN_LOWER: Do we use lower bound when value is unknown?

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#513]
PC01 has PHOTO_YEAR = 1968. When a stand has age > 80 years, ORIGIN_UPPER will be 1888, but what about ORIGIN_LOWER? Do we use lower bound 1000 as found in the doc? OR do we translate it as unknown value?

**Comment by edwardsmarc** [comment]
I would say UNKNOWN_VALUE. We did the same thing in NL01.
