### ISSUE TITLE
notEmpty() is not working

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#53]

**Comment by pedrogit** [comment]
It,s working but the values is a space. We could add a "ignoreSpaces" option TT_NotEmpty() so that if the value is only spaces, it would treat it as empty and return FALSE. the option would be TRUE by default.

**Comment by edwardsmarc** [comment]
* Current behaviour is to return FALSE for spaces. Both "" and "  " should return FALSE. 
* I like the idea of adding IsBlank in a future release.

**Comment by edwardsmarc** [comment]
@prvernier will test if this is fixed and close issue.

**Comment by pedrogit** [comment]
To be closed?

**Comment by edwardsmarc** [comment]
This needs to be tested. If spaces are not returning FALSE, something is wrong.
