### ISSUE TITLE
AB10 has some unknown disturbance codes

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#530]
Disturbance codes CW, TL, FL, PI, FT, AS, MT.

@prvernier can you check the Perl code to see if these have translations?

**Comment by prvernier** [comment]
In the Perl code, these are all translated as "OT" and part of an "illegal disturbance list". There is no description for any of the codes.

**Comment by edwardsmarc** [comment]
Also AB07 has NFL codes AIW, CIU, AIU which are not in the manual.
AB08 has nat_non code NMG which is not in the manual.

Any ideas what these are?

**Comment by prvernier** [comment]
According to the Perl code:

- AIW -> FA
- CIU -> OT
- AIU -> OT
- NMG -> SA (or SD - this is commented out with a mention to "verify this")

**Comment by edwardsmarc** [comment]
Details from JC in 2012:
Here is the answer from one of our collaborator:
Applies to overstory and understory
CIU=OT
AIW=FA
NMG=SD
NMM=RK
AIU=OT
AIL=HG
The UMoistREG#0 should be the same moisture as the over story in all cases but for horizontal polygons. So, should only need to look at overstory moisture regime to get the answer.
MoistRg#N. You will need to look at species 1. If a wetland species (Lt or Sb) go with W or 6 depending if inventory has alfa or numeric. If upland species (Sw, Pj, Pl, Aw, Pb, Fb, Bw) go with M or 4.
NFL#AS=0 go with SL. This one is just a guess.
