### ISSUE TITLE
Productivity and Productivity_type (Ontario)

### ISSUE THREAD

**Issue by sgautam2076** [edwardsmarc/CASFRI#532]
Ontario data (that CFS has access) have a field “formod” and carries values RP, MR and PF. The following screen shot (Page 28 of Forest Management Planning Technical Specifications - October 2018) indicates that RP, MR and PF are productive forest, but differs in management restrictions. The MR and PF are restricted for normal forest practice, while RP has no limitations. 
In CASFRI, these values are used to derive PRODUCTIVITY and PRODUCTIVITY_TYPE (PRODUCTIVE_FOR earlier). I think that the PRODUCTIVITY values in CASFRI for all three types (RP, MR and PF) can be mapped as PRODUCTIVE_FOREST, not only RP. In case of PRODUCTIVITY_TYPE, the RP should be mapped as HARVESTABLE, while PF and MR as PROTECTION_FOREST.
 
![image](https://user-images.githubusercontent.com/65095356/105080736-402cc180-5a5f-11eb-9b98-1d6bf27ed0ee.png)

**Comment by sgautam2076** [comment]
I think we can we add "OMS" to this list matchListTwice(formod, polytype, {'PF', 'RP'}, {'BSH','RCK','TMS'}|UNKNOWN_VALUE)
![image](https://user-images.githubusercontent.com/65095356/105222013-e512d180-5b27-11eb-87ac-3f3be46b2313.png)

**Comment by edwardsmarc** [comment]
@sgautam2076 We currently report OMS as OPEN_MUSKEG in the NFL table. I see that they are cassifying OMS as a forested polygon though so maybe it should be removed from NFL and reported as a PRODUCTIVITY_TYPE as you suggest.
