### ISSUE TITLE
Run full translation test for PC01 and PC02

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#538]

**Comment by edwardsmarc** [comment]
Failing constraints:

3.2 - cas_id is not the same across all translation tables. @MelinaHoule which is correct?

4.** - a few constraints fail because error code not_in_set is not valid for numeric or integer attributes. Change the validation rules from matchList to isBetween or isGreaterThan

**Comment by edwardsmarc** [comment]
PC01 is complete and all constraints pass.

**Comment by edwardsmarc** [comment]
@pedrogit - can I close this, did PC02 pass the constraints?

**Comment by pedrogit** [comment]
I will open a more specific issue if it does not. Closing.
