### ISSUE TITLE
Add QC02, QC06 and QC07 in inventories list and attributes dependencies tables

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#541]
The current QC02 holds 3 differents standard (same as QC03).  To allow translation we will split them during the upload and fill the inventories list and attributes dependencies table accordingly.

**Comment by MelinaHoule** [comment]
In inventory_list_cas05, PHOTO_YEAR_START and PHOTO_YEAR_END need to be filled once the inventories are loaded in the db.

**Comment by edwardsmarc** [comment]
@MelinaHoule I added the photo years using an_saisie values for QC02 and an_pro_ori for QC06 and WC07. If those are correct we can close this issue.
