### ISSUE TITLE
Constraint 1.21 about stand_photo_year is too strict

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#543]
Constraint 1.21 fails if any photo year has an error code. Many photo years will have error codes if they don't intersect the photo year shapefiles, or if they have a value of zero.

Can the constraint be relaxed?

**Comment by pedrogit** [comment]
The constraint now ensure that stand_photo_year > 0 OR stand_photo_year = ANY(TT_IsMissingOrInvalidRange()
