### ISSUE TITLE
PC02 - Should Ericaceous, graminoids and herbs species added to species_code_mapping

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#545]
In species description, PC02 uses specific code to define Ericaceous species (ER), Graminoid species (GR) and Herb species (GC). Those were translated in CASFRI v4 as LYR using species code WBNP_ERAC, WBNP_GRAM and WBNP_HERB. 

They all have height (0-9m) and crown_closure assigned. 

Those species also have NFL code (ER = LOW_SHRUB, GR= GRAMINOID and GC =HERBS)

Should we add those species to the species_code_mapping and keep translation in LYR? or should we translate them as NFL?

**Comment by edwardsmarc** [comment]
I would vote to translate these as NFL since they are clearly not forested layers.

**Comment by MelinaHoule** [comment]
closed with commit 85682477bd1f69c9f21f63ef81cb080ed343f157
