### ISSUE TITLE
Review LAYER assignment in PC01

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#547]
Might need custom function to count layers now that wetland has a layer assignment. More info to come...

**Comment by MelinaHoule** [comment]
No. Right now, wetland type is assigned for non forested polygon (wetland grass or herb from wetland shrub). Each ECO PC01 entries correspond to a specific wetland type of NFL. They thus use the same layering than NFL. They are not layer (or part of polygon) by themselves.

**Comment by edwardsmarc** [comment]
OK I think I understand. Whenever a wetland layer is identified, it's values comes from g1spec which is also the attribute for NFL values. So the ECO row would have the same LAYER as it's associated NFL row.

And for LAYER and NUM_OF_LAYERS you caught the zeros in g1spec using TRUE in countOfNotNull which means whenever g1spec has a non-null, non-zero value it can be counted as a layer. Great.
