### ISSUE TITLE
PC02 - Fix CountOfNotNull() and HasCountOfNOtNullOr Zero() to take 8 SrcVal

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#551]
In PC02, layer is calculated based on a possible 7 vegetation strata and 1 non_forested strata. Right now, helper function CountOfNotNull(), HasCountOfNotNullOrZero() and HasCountOfNotNull() take a maximum of 7srcVal. I would need the function to take 8 argument in order to account for non-forest strata as a possible layer.

**Comment by edwardsmarc** [comment]
Is every value in the non-forested attribute always an NFL value? i.e. if the column is not empty, is there always an NFL layer to count?

If yes, I'll add an extra srcVal to the functions.
If no, we would need a custom countOfNotNull function to count the NFL layers.

**Comment by MelinaHoule** [comment]
The non-forest column I want is related to shoreline. It has 3 possible value: Z and M that are translated has WATER according to the manual and NULL where it is not applicable. So I think an extra srcVal would do.
