### ISSUE TITLE
PC02- Problem with layer calculation in ECO table

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#566]
Translation function for LAYER attribute now use pc02_countOfNotNull() (#557 ). In the ECO table, the translation returns LAYER=0. Translation of LAYER in others translation tables are ok.  

pc02_countOfNotNull(v1sp1, v2sp1, v3sp1, v4sp1, v5sp1, v6sp1, v7sp1, v1pcm, v2pcm, v3pcm, v4pcm, v5pcm, v6pcm, v7pcm, shrln, 'translation', 'species_code_mapping', 'pc02_species_codes', layer)

pc02_countOfNotNull() uses species table, nfl_string_list, lake_string_list. All source values are found in either one of the list. Don't know what is going on.

**Comment by edwardsmarc** [comment]
The wetland layers are defined using the same columns as NFL right? I think you therefore need to use the same _layer_ values as NFL in the attribute dependencies table. Right now the wetland layers look to be using _layers_ 1-7. Try moving them down and using 8-14. I think this should solve the problem. You'll also need to change your createMappingView calls to use these different layer numbers.

**Comment by MelinaHoule** [comment]
ECO is not necessarily NFL. 2 eco type  refer to species (some wooded black spruce wetland). Specific cases I checked should have had LAYER = 1 because black spruce is the species 1, thus   pc02_countOfNotNull(**v1sp1**, v2sp1, v3sp1, v4sp1, v5sp1, v6sp1, v7sp1, v1pcm, v2pcm, v3pcm, v4pcm, v5pcm, v6pcm, v7pcm, shrln, 'translation', 'species_code_mapping', 'pc02_species_codes', layer) should have been catch in the LYR row

**Comment by edwardsmarc** [comment]
The wetland rules including species are for example `WHEN v_pcm ='19' AND v_str = 'N' THEN 'FTNN'`.

So an ECO layer in this case should only be counted if veg is N and pcm is 19. Just counting the notNull values is therefore insufficient for identifying a wetland row. It needs to identify this specific combination of values. I think I need to edit pc02_countOfNotNull to account for the wetland translations. That, combined with my suggestion of moving the wetland translations down to rows 8-14 should fix the issue.

Do you agree?

**Comment by MelinaHoule** [comment]
I agree as long as a wooded ECO get the same LAYER number of it's associated LYR (because they represent the same strata). v_pcm = 18 is also  wooded in case that was a problem too.

**Comment by edwardsmarc** [comment]
Just to make sure I understand:

- ECO can have a value that is associated with the LYR value, or associated with the NFL value.
- The horizontal layer would have information in the LYR table for example, and the matching cas_id x LAYER would also have an ECO entry. So the LAYER values have to match.
- The same could occur for an NFL entry.

Is it true that every ECO value is associated with either an NFL layer, or a LYR layer?

**Comment by MelinaHoule** [comment]
Yes, ECO can have a value that is associated with either LYR or NFL
Yes, when ECO is from a LYR source value, LAYER value have to match
Same for NFL, if ECO is derived from a NFL source value, LAYER in ECO needs to match LAYER value assigned in NFL. 

Yes every ECO value is either NFL or LYR. 

ECO value are derived from v_cpm. Source value 1, 2, 3, 4, 7, 17, 18, 98, 99 are NFL. Source value 19 and 20 are LYR with species associated. It cannot be anything else than LYR or NFL. 

When ECO is LYR with source value = 19, the custom function distinguish the structure (v_str) 'N' from 'P' to apply the proper translation.

**Comment by edwardsmarc** [comment]
Great, I now realise we don't need a custom function, because ECO only translates if ROW_TRANSLATION_RULE passes. 

The problem is that for every row, 1 to 14, it is possible to have an ECO row that is associated with the LYR or NFL row. ECO needs to return the same LAYER value as it's associated row, which means the ECO LAYER translation rule needs to exactly match the one run for LYR or NFL (including the _layer_ value used in the function).

So I think our solution is to run the ECO table translation for every row in attribute_dependencies. This will mean you run ECO translation 14 times in the workflow! Seems ridiculous but I think it's the only way.
