### ISSUE TITLE
orig_stand_id is set to ogc_fid in QC

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#567]
ogc_fid is not in the source tables, is there another value we can use?

**Comment by MelinaHoule** [comment]
orig_stand_id in QC is GEOCODE which use this format: "-736960,07+301906,47". Not sure how to store that information into the CAS_ID.

**Comment by edwardsmarc** [comment]
We don't need it in the cas_id, but the CAS table has an attribute ORIG_STAND_ID that should record the GEOCODE. It's not limited to 10 characters like the cas_id. I'll make the change.

Looking at the cas_id though, there is no way to link back to the original source polygon. Maybe we should split geocode into 2 attributes like we did for ON02. I'll look into it.

**Comment by MelinaHoule** [comment]
Wouldn't be more intuitive to split using the comma?

GEOCODE represent the coordinate of the centroid.

**Comment by edwardsmarc** [comment]
Each cas_id slot only takes 10 characters. So if the geocode is 20 characters the only way to maintain the full value is to split into 2 strings, each 10 characters long. Otherwise we can't recreate the original id.

It is true in this case we can trace back to the original polygon using the orig_stand_id which will contain the full geocode value. But that means the cas_id is basically useless in QC.

**Comment by edwardsmarc** [comment]
Many geocodes have commas which disrupts the parsing of the ca_id function. Convert these to periods when creating split geocode columns.

**Comment by edwardsmarc** [comment]
Note I left ogc_fid out of the cas_id. I was finding that everytime the QC data was reloaded the ogc_fid would change. Probably because it is added using SQL code after load. This was causing the test files to change every time the data was loaded. ogc_fid isn't needed in the cas_id, geocode is a unique id and traces back to the source polygon.

**Comment by pedrogit** [comment]
That is strange because ogc_fid is used in other CAS_ID and it never broke the test tables.
