### ISSUE TITLE
NS01 and NS02 do not have age attribute

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#594]
How was origin calculated in CAS04?

**Comment by MelinaHoule** [comment]
From what I see in the old script, origin_upper and lower were translated as undefined: 

$Origin=UNDEF

The data also confirmed that translation. origin_upper and lower value is -8888, which is the undefined code.

**Comment by prvernier** [comment]
Yes, age is only available from 2006 on according to Cosco specs.

**Comment by edwardsmarc** [comment]
Age values of 999 in NS03 are used for uneven aged stands where age is not known. We catch them during validation and return UNKNOWN_VALUE.

We currently report unknown values for the NS01, NS02 and NS03 layer 2 rows by mapping age to 999.
