### ISSUE TITLE
QC07- species and species percent not translated by qc_prg5_species_translation()

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#597]
QC07 is not translated by custom function qc_prg5_species_translation().  In QC07, species_per  is represented by one number, not two. For example:

QC07:  "BJ3EO2ES2SB2EB1"
QC05: "EN50SB40BP10" 

Right now, the qc_prg5_species_translation() function translate species as NOT_IN_SET or NOT_APPLICABLE and species_per as one single number. 

I don't know why species translation gives NOT_IN_SET or NOT_APPLICABLE. I think odd character string return NOT_APPLICABLE and even character string return NOT_IN_SET. I extracted all DISTINCT species source values by parsing the string and species are all listed in  the species_mapping for QC. So NOT_IN_SET should never happen.  

Two examples: The translation of  source value 'BJ5ER2SB3' returns species_1 : NOT_APPLICABLE and species_per_1: 5  and source value 'BJ3BP2EO1SB4' returns species_1: NOT_IN_SET and species_per_1: 3. 

When inventory id = QC07, percent should be multiplied by 10. Not sure what is going on with species translation. If possible I would suggest to adpat the function instead of creating a new one so QC07 can still use QC05 translation tables.

**Comment by edwardsmarc** [comment]
I think the NOT_APPLICABLE is returned based on the different string lengths. And NOT_IN_SET is returned when the string length is acceptable, but the parsing for species code is wrong due to the wrong characters being selected. I should be able to adapt the function to deal with both cases.

**Comment by edwardsmarc** [comment]
@MelinaHoule - Can you confirm that in QC07, when a single species covers 100%, the percent is indicated as a zero.

For example, BP0, EB0, FX0 should all return species percent of 100.

**Comment by edwardsmarc** [comment]
Working on QC05 and QC07 species validations.

- if we continue using lengthMatchList we'll need to write a custom function that runs the correct list of acceptable lengths based on the inventory_id. For example, for species_1, QC05 would use {5, 8, 12, 16, 20, 24, 28, 32, 36, 40} and QC07 would use {3, 6, 9, 12, 15, 18, 21}.
- We would also need to catch the 6 character codes in QC07 that do not have percent values (e.g. FXRNRZ).

An alternative would be to write a new generic function named tt_matchAlphaNumeric() which would convert all letters to 'x' and all integers to '0', then test the resulting string against a list of acceptable codes. This would allow all acceptable patterns to be included in one function.

For species 1 this would look like:
matchAlphaNumeric(species_1, {'xx000', 'xx0', 'xx00xx00', 'xx0xx0', 'xx00xx00xx00', 'xx0xx0xx0' etc.etc.}|NOT_APPLICABLE)

**Comment by MelinaHoule** [comment]
Yes, I confirm single species with 0 = 100% in QC07. 

 For the custom function, I don't know what would be best. In QC05, we also have the occurrence of format 'FXRXRZ'. Those should be translated as 35%, 35% and 30% based on the manual definition that says : To be described a species group (FX, FZ, FN, FT, RX, RZ) occupies at least 25%. 'Format 'FXRX' should be 65% and 35%. 

RN is not a species code recognized by the manual. 

If the validation custom function is dealing with too many exceptions, maybe we should switch to matchAlphaNumeric().

**Comment by edwardsmarc** [comment]
I think matchAlphaNumeric() is the way to go. That way we can deal with the species and the species groups. Any RN would get caught by the matchTable and would return NOT_IN_SET. But they would get a % value.

I'll write matchAlphaNumeric(). And I'll need to update the species and percent custom functions to process the species group codes.

**Comment by edwardsmarc** [comment]
Here are logic rules that will be applied when translating the codes to species and percentages:

- Does the string contain integers (i.e. is it a valid QC05 or QC07 code such as BS10BF90 or BS1BF9)
  - Parse out the codes into species-percent pairings (e.g. BF1, BF9)
  - Reorder by percent (e.g. BF9, BS1)
  - For species, get the character code and translate using lookup table
  - For percent, if code is 0, return 100. If code is <10, multiple it by 10, otherwise just return the value.
- If no integers, it's a species group code (e.g. FXFN)
  - For species, get the character code and translate using lookup table
  - For percent: 
    - if length is 6, return percent's as 35%, 35%, 30% 
    - if length is 4, return percent's as 65%, 35%
    - if length is 2, return percent as 100%
