### ISSUE TITLE
geocode is not unique in QC03

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#600]
Should we be using geoc_maj instead?

Which QC inventories should use geocode and which should use geoc_maj?

Fixing this should add back some layer 1 LYR rows in the test tables for QC03.

**Comment by edwardsmarc** [comment]
QC03, QC04, QC05, should use geoc_maj

**Comment by MelinaHoule** [comment]
GEOC_MAJ was identified as the unique identifier in the loading script. Geocode is the unique identifier when the inventory goes for a first release. Then, every year or so, the province  incorporate disturbance which cut the original polygon. They update Geocode in a new column callled GEOC_MAJ. So if the user load QC inv using  PEE_ORI_PROV, GEOCODE is the unique identifier. If the user load QC inv using PEE_MAJ_PROV, GEOC_MAJ is the unique identifier.
