### ISSUE TITLE
QC01 - GEOCODE is not a unique identifier. Need to union geometry during conversion 

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#601]
In QC01, geocode is supposed to be the unique identifier. However, for storage purposes, inventory was splitted by mapsheet. The combination of mapsheet + geocode was evaluated  to be the unique identifier but unfortunately, when a polygon have a U shape, polygon get split into 3 pieces where the geocode is the same for all 3 parts and mapsheet is the same for two of them. 

I checked if attributes used by the translation were the same for distinct geocode. Only the field mapsheet and area make them to be different. The rest is the same. 

This problem was raised in issue #580 for NT. It correspond to Case 1. 

- Original polygon is intersected by grid.
- Resulting polygons occur on both sides of the intersect.
- Each polygon is assigned it's area after the intersect (****Note most of the time, it's true area, but some as weird area that do not correspond to the geometry or the some of all geometry for a distinct GEOCODE. Don't know how it was computed)

I suggest during the loading that we union geometry based on GEOCODE keeping only the first occurence of attributes.

**Comment by edwardsmarc** [comment]
Done, bat file still needs updating

**Comment by pedrogit** [comment]
Replaced with #683. Closing.
