### ISSUE TITLE
Constraints - Five rows produce NUM_OF_LAYERS = 0

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#609]
"PC02-WBNP_BIOPHYSICA-xxxxxxx84P-0000000462-0000390"
"PC02-WBNP_BIOPHYSICA-xxxxxxx74L-0000000279-0000217"
"PC02-WBNP_BIOPHYSICA-xxxxxxx84P-0000000704-0000897"
"PC02-WBNP_BIOPHYSICA-xxxxxxx85B-0000000880-0000668"
"PC02-WBNP_BIOPHYSICA-xxxxxxx85B-0000000882-0000669"

**Comment by edwardsmarc** [comment]
Check constraint 1.15 passes before closing
