### ISSUE TITLE
Constraints - LOWER_HEIGHT and UPPER_HEIGHT generate TRANSLATION_ERROR in BC08 and BC10

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#613]
```
SELECT left(cas_id, 4) inv, height_upper, count(*) nb
FROM casfri50.lyr_all
WHERE height_upper < 0 AND NOT height_upper = ANY(TT_IsMissingOrInvalidRange())
GROUP BY left(cas_id, 4), height_upper
```

**Comment by edwardsmarc** [comment]
Validation function
```
hasCountOfNotNullOrZero({species_pct_1, height_1}, {species_pct_2, height_2}, 1, FALSE|-8888)
```
is not appropriate. We need to check that both species 1 and height 1 have valid values (or species and height 2). HasCountOfNotNullOrZero passes if only one has a value.

I don't think we can solve this with an existing helper function. Writing bc_height_validation().

**Comment by edwardsmarc** [comment]
Don't need custom validation function. Updated bc_height() so it only returns null when both height values are null. Changed validation to check at least one height value is available.

**Comment by pedrogit** [comment]
Still have to pass the constraints.
