### ISSUE TITLE
Constraints - -8886 is used as SPECIES_1-3 error code instead of UNKNOWN_VALUE in QC03 and QC04

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#614]
Note that UNKNOWN_VALUE should be added in the NFI_SPECIES_CODE column of the species_code_mapping.csv table to make constraint work.

**Comment by edwardsmarc** [comment]
Error code is fixed.

NFI_SPECIES_CODE is now named casfri_species_codes. What is needed here? An empty row with UNKNOWN_VALUE specified in casfri_species_codes?
