### ISSUE TITLE
Translate YT03

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#615]
YT03 looks quite different from YT02 (e.g., additional layer and different attribute names with different values) and will need a new set of translation tables.

**Comment by edwardsmarc** [comment]
Stand structure needs to use a custom function.

**Comment by edwardsmarc** [comment]
NFL can all three values in the same row. Can also have graminoid and shrub together. These need to run on separate translations so we could have up to 6 layers: 2 LYR and 4 NFL.

Use HasNFL Info for ROW_TRANSLATION_RULE.
