### ISSUE TITLE
Review src_filename column and CAS ID structure

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#62]
* src_filename column is added during loading, it becomes a string of the filename for each loaded dataset.
* Depending on the filetype this could be the same for all rows (e.g. gdb) or different (e.g. Coverages).
* In the case of Coverages for AB16 it becomes the mapsheet value since this is how the files are labelled.
* src_filename was originally added for use in the cas id but we can also just enter this as a string in the transaltion rules since it's the same for all rows (e.g. 'CANFOR').
* Therefore src_filename might not be needed.

* We did use to add the AB16 mapsheets, so it could still be useful in some cases, and can be useful for verifying all source tables were appended to the loaded table.

**Comment by pedrogit** [comment]
True that when there is no filename variation (i.e. there is only one file) src_filename is useless.

**Comment by edwardsmarc** [comment]
Possible duplicate of #214

**Comment by pedrogit** [comment]
Marc's comments copied to #214. Closing.
