### ISSUE TITLE
Constraints - Two NS01 and NS02 rows are not translated

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#622]
Number of loaded rows for NS01 = 1127926
Number of translated rows for NS01 = 1127924

Number of loaded rows for NS02 = 1090671
Number of translated rows for NS02 = 1090669

**Comment by edwardsmarc** [comment]
I don't understand how this is possible. CAS table should include all rows.

**Comment by edwardsmarc** [comment]
Same issue as #623

**Comment by pedrogit** [comment]
Duplicate of #623. Closing
