### ISSUE TITLE
CASFRI translation (Layer, Productivity) to VRI of Nova Scotia 

### ISSUE THREAD

**Issue by sgautam2076** [edwardsmarc/CASFRI#627]
I think we may have to revisit CASFRI translation for Nova Scotia on assigning layer and populating “productivity” attribute.
A.	Layer
The photo interpretation Specifications (https://novascotia.ca/natr/library/FORESTRY/inventory/Photointerpspecs.pdf, page 14, point 12.1) for Nova Scotia indicates that the “**a second layer is a distinct layer either above or below the main stand with at least 2 m difference in height and each layer has at least 10% crown closure**”. Additional information, I was referring is found at https://novascotia.ca/natr/forestry/gis/pdf/Forest_metadata_web_attrib.pdf.

This indicates that making a decision about main layer or second layer based on height (as in some other jurisdictions) is not valid in the case of Nova Scotia. In this case, populating layer as it is in the original data would be good.

B.	Productivity
In the current CASFRI, only 33, 38 and 39 codes are mapped as non-productive forest and the rest were considered as unknown_value. However, I think it would be nice to populate other values as well. My suggestions would be the following.

First Step
Check if the polygon is forest or non-forest (i.e., if lndclass = 99 it is Main Land Forested, if lndclass = 98 it is Main Land non-forest).

Second Step
If polygon is identified as forest, then we may populate productivity based on fornon values. 
•	productive if fornon values listed in 0,1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20,60,61,62 and 
•	non-productive if fornon values listed in 33, 38 and 39
  
C.	Productivity_type
In this case, it is not quite clear for all codes but at least we can populate a few harvestable polygons. If fornon values listed in 0, 1, 12 then it looks like harvestable.

**Comment by edwardsmarc** [comment]
B and C make sense and I can make those changes.

For A. The CASFRI definition of LAYER is that they are ordered by height. So LAYER 1 is always the tallest. This is to accommodate the different standards from the various jurisdictions, and combine them into one standard. This way you always know LAYER 1 is the tallest across the entire CASFRI, you don't have to lookup the manual for each jurisdiction when you query the data. It wouldn't make sense for PEI to be ordered by height, but then across the border in NS the tallest layer could be LAYER 2.

I do appreciate that in NS we might want to record the fact that the "main" layer might not always be layer 1. We could use LAYER_RANK for this. All of the "main" layer info would be assigned LAYER_RANK = 1, and the "secondary" layers would be labelled LAYER_RANK = 2. 

So a user could reconstruct the original dataset layers by querying WHERE  LAYER_RANK = 1.

**Comment by pedrogit** [comment]
How is layer_rank currently assigned for NS? Is it?

**Comment by edwardsmarc** [comment]
Currently LAYER_RANK is not assigned because no explicit ranking attribute is included in the source data. We had previously agreed that LAYER_RANK would only be populated if the source inventory had a rank attribute. Currently only BC and MB FLI have such an attribute.

This raises the question of whether LAYER_RANK should be populated for inventories that have 2 data slots, where the first slot tends to be "overstory" or "primary" layers, and the second slot tends to be "understory" or "secondary" layers. I would suggest that in AB, NB, NT, ON, SK SKVI, and NS, we could apply this system as a way to reference the original data structure.

"Overstory" or "primary" layers would be assigned LAYER_RANK = 1, and "understory" or "secondary" layers would be LAYER_RANK = 2.

**Comment by edwardsmarc** [comment]
Decision - add LAYER_RANK to AB, NB, NT, ON, SK SKVI, and NS.

Document this decision in the specs for LAYER and LAYER_RANK

**Comment by sgautam2076** [comment]
Not sure, what will be populated for a fornon with value 73 (which is classified as Treed bogs)

**Comment by edwardsmarc** [comment]
73 is included in non-forested in the manual, but it also states >25% forest cover. So I think we should add this as a non-productive LYR record with PRODUCTIVITY_TYPE of TREED_MUSKEG.

**Comment by sgautam2076** [comment]
Yes, you are right.

**Comment by edwardsmarc** [comment]
I've updated the PRODUCTIVITY translation to use:

```
mapText(productivity, {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20,60,61,62, 33,38,39, 73}, {'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'PRODUCTIVE', 'NON_PRODUCTIVE_FOREST','NON_PRODUCTIVE_FOREST','NON_PRODUCTIVE_FOREST','NON_PRODUCTIVE_FOREST'})
```

and the PRODUCTIVITY_TYPE to use:
```
mapText(productivity, {0,1,12, 33,38,39, 73}, {'HARVESTABLE','HARVESTABLE','HARVESTABLE', 'SCRUB_SHRUB','ALDER','ALDER', 'TREED_MUSKEG'})
```
