### ISSUE TITLE
NB01 validation rule doesn't match translation rule

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#63]
* NB01 is failing because there are 0's in the source data crown closure attribute.
* The TT_Map() helper function cannot return anything because 0 is not included in the translation list.
* This should be caught by the validation rules
* Translation rule is:
  * map(l1cc, '1,2,3,4,5', '30,50,70,90,100')
* Validation rule should be changed from:
  * between(l1cc,0,100|-9999)
  * to:
  * match(l1cc, '1,2,3,4,5')
  * I think the error code in this case should be -9998 (not in set)

**Comment by prvernier** [comment]
The value 0 is not expected but does occur less than 0.1% of the time on a random sample. The translation rule is now fixed.
