### ISSUE TITLE
Complete organization of specifications folder

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#64]
The following needs to be completed by March 31, 2019:
  * organize folder structure including subfolders and files
  * update and revise readme.md so that it has the same structure as the other readme.md files
  * update cas_attributes.md to include all individual attributes md files
  * remove all "NA" rows from error tables for each attribute
  * create archive folder for original (converted) specifications document and appendices

**Comment by edwardsmarc** [comment]
@prvernier I have removed all readme's from sub folders. So the only readme's are in the root of the repo's. I've left the one in the translation folder for you to delete.

**Comment by prvernier** [comment]
Okay, I have deleted from my laptop - it will be reflected when I commit and push later today.

**Comment by prvernier** [comment]
@edwardsmarc should I remove the readme from the specifications folder as well?

**Comment by edwardsmarc** [comment]
I think we can leave that one since it provides useful context.
