### ISSUE TITLE
QC01 loading script introduce line with all NULL value (including geocode)

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#643]
QC01 new loading script that union geometry with the same geocode introduce 1 line with geocode = NULL. In the previous version of the loading (the one not unioning polygon be geocode) did not have any NULL geocode. All attributes for that line are NULL. When I run ST_AREA on the geometry, I get an area of 33 000km².  Not sure how to investigate the problem.

**Comment by edwardsmarc** [comment]
NULL geocodes are edges around inventory. Some are rivers that have valid data. Why are they getting set to NULL during loading?

**Comment by MelinaHoule** [comment]
Correction: By exploring the source data, those polygons have NULL geocode from the source file. The first previous loading script did not load them, that is why I didn't went over the issue before. The example about the St-Lawrence river was erronous. Polygons with attribute being only water are well loaded.  Now if we don't change anything we create a huge polygon really complex. Do we want thta. That polygon will obviously only have a CAS and GEO entry. Or do we load the geoemtry when geocode IS NOT NULL?

![qc01_geocode](https://user-images.githubusercontent.com/10730242/109552295-94d04d00-7a9f-11eb-8546-3c6fe6b3f522.png)

**Comment by edwardsmarc** [comment]
That's a question for @pedrogit 

I would vote to drop that giant polygon during loading.

**Comment by MelinaHoule** [comment]
It is not a giant polygon. They are many polygons with no geocode (they haven't being interpreted) representing the edge that we transform as a giant polygon by making a union on geocode.

**Comment by edwardsmarc** [comment]
Agreed, it is a complex polygon that will slow down the temporalization procedure but doesn't provide any data. We should probably drop all the original polygons during loading, this will also make the loading script faster because it won't need to union all these together.
