### ISSUE TITLE
Replace minIndex and maxIndex functions with getIndex versions in translation tables

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#647]
minIndex can be replaced with getIndex and an indexToReturn of 1.

maxIndex can be replaced with getIndex, indexToReturn would be set to the length of the input stringLists.

**Comment by edwardsmarc** [comment]
Correction, maxIndex behaves slightly different in that it returns the max non null value. This is slightly different than the getIndex version.

e.g.
TT_GetIndexCopyInt('{null,null,null}', '{1,2,null}', '3') returns null
TT_MaxIndexCopyInt('{null,null,null}', '{1,2,null}') returns 2

So we probably want to keep the maxIndex functions.

**Comment by pedrogit** [comment]
Both functions were scraped from the engine helper function. Was this converted and now working?

**Comment by pedrogit** [comment]
Closing...
