### ISSUE TITLE
Conversion scripts end with /bin/bash

### ISSUE THREAD

**Issue by kdarndt** [edwardsmarc/CASFRI#653]
In common_processing.sh, the script ends with "/bin/bash".  This interferes with the normal execution flow of the conversion scripts and makes it appear as though the script is still running.  If conversion and translation were further automated, it would interfere with automation.

As I understand it, this was put in place to help keep a terminal window open in order to view the output of the commands.  I suggest using syntax similar to the following to write the output to a log file which provides more flexibility and tracking and does not interfere with the execution of the script:

```
{ # begin code block in which all output will be redirected to a logfile
...code...goes...here....
} >> myLogFile.txt 2>&1
```

**Comment by pedrogit** [comment]
Closed at the same time as #653. There is now a configuration variable (leaveConvShellOpen) to control if parallel shells should close when done (false by default).
