### ISSUE TITLE
QC06 - out of range values for ORIGIN and PHOTO_YEAR

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#664]
This may have been fixed by now, but based on a review of casfri50_pierrer_release on 2021-03-12, there is one invalid value in STAND_PHOTO_YEAR (6003) and one ORIGIN_UPPER / ORIGIN_LOWER (5953).

**Comment by MelinaHoule** [comment]
I think it's issue #651

**Comment by prvernier** [comment]
Great, so it should show up as fixed in the next update.
