### ISSUE TITLE
HEIGHT_UPPER and HEIGHT_LOWER - some inventories have >1 decimal place

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#665]
According to Appendix 6 in the Cosco specs source attributes are measured to the "Nearest 1m", "Nearest 0.1m", or can be a "Class". Currently, values for HEIGHT_UPPER and HEIGHT_LOWER have between 0-15 decimal places. One example is BC10. However, looking at the source data for BC10, there are no height values with more >1 decimal place.

**Comment by edwardsmarc** [comment]
Height in BC is calculated by us using a weighted average which would explain the decimal places. I'll edit the function to return 1dp.

In other cases I think we previously agreed to just copy the source values, regardless of dps.

**Comment by prvernier** [comment]
That should probably take care of most (if not all) of the values with >1 dp across all inventories.

**Comment by edwardsmarc** [comment]
Check this on most recent release using the summary statistics

**Comment by edwardsmarc** [comment]
All height values to 1 dp in last release. Closing
