### ISSUE TITLE
WET_LOCAL_MOD "Translation_Error" in NB01 and NB02

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#667]
The error code "TRANSLATION_ERROR" occurs 843 and 2311 times in NB01 and NB02, respectively. This error code is not listed as a specific code for WET_LOCAL_MOD. Is there a reason this code was used rather than one of the specific ones?

**Comment by pedrogit** [comment]
This is a duplicate of #612. Closing.
