### ISSUE TITLE
PC02 structure_per uses a range of values

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#668]
Add the ranges into the description.

In 767 polygons the sum of v1pct to v7pct is 10.
In 114 polygons the sum is 9.

I think it's better not to go over 100%, so I'd vote to just multiply each value by 10. This would be equivalent to taking the lower bound of each range.

**Comment by edwardsmarc** [comment]
I've changed the translation rule to:

```
mapInt(structure_per, {0,1,2,3,4,5,6,7,8,9}, {0,10,20,30,40,50,60,70,80,90})
```
and the description to 
```
Map structure percent to lower bound of range. The defined ranges are 0: 0-9%, 1: 10-19%, 2: 20-29%, 3: 30-39%, 4: 40-49%, 5: 50-59%, 6: 60-69%, 7: 70-79%, 8: 80-89%, 9: 90-100%. Many polygons source values sum to 10 so we take the lower bound to avoid exceeding 100% cover. Note that some layers will therefore have a value of zero, even though they could have some coverage (0-10%).
```

**Comment by MelinaHoule** [comment]
PC02 uses 0 as a filler. But when species are present, species_per = 0 means 0-9%. If we define the range in the description the way you proposed, I would suggest the translation to be {5,10,20,30,40,50,60,70,80,90}.  From my test, we would never go over 100% (max value would be 95%) and it would be more informative for user. Most of them won't go into the translation description per inventory. Having a 0 could be interpreted as an error not cover by the engine and thus be dropped. By putting the value to 5, we make sure the value would be considered.

**Comment by edwardsmarc** [comment]
Based on this query I expect we could have some rows summing to 105% using {5,10,20,30,40,50,60,70,80,90}.
```
select v1sp1, v1pct, v2sp1, v2pct, v3sp1, v3pct, v4sp1, v4pct, v5sp1, v5pct, v6sp1, v6pct, v7sp1, v7pct from rawfri.pc02 group by v1sp1, v1pct, v2sp1, v2pct, v3sp1, v3pct, v4sp1, v4pct, v5sp1, v5pct, v6sp1, v6pct, v7sp1, v7pct
```

I think this is a problem in the source data. They use zero to indicate null but also to indicate 0-10%. We can assume if there is a species present then the zero indicates 0-10%. But if a species is present it obviously doesn't have a cover of 0%. It must be >0%. In most rows this leads to a total percent cover of >100% because the sum of the source values is 10.

So our options are:
- Use mapInt(structure_per, {0,1,2,3,4,5,6,7,8,9}, {0,10,20,30,40,50,60,70,80,90}) to avoid going over 100%
- Use mapInt(structure_per, {0,1,2,3,4,5,6,7,8,9}, {5,10,20,30,40,50,60,70,80,90}) to correctly indicate that the first group does in fact have some coverage
- Make our own ranges that fulfill both requirements but break the rules in the documentation: mapInt(structure_per, {0,1,2,3,4,5,6,7,8,9}, {1,9,19,29,39,49,59,69,79,89})

**Comment by MelinaHoule** [comment]
Option 1 would bring confusion. MOst of the user won't read the documentation and will misinterpret the output. 

The problem is from the source value, but I the user will expected some rigour from the database like not having species_per going above 100% when added. 

I will vote for option 3. It's one percent below the doc and documentation will be given in the description column if the user wants to understand why we derived from the source.
