### ISSUE TITLE
Switch to using newest BC data

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#67]
* Copy new BC FRI and add a row for it in inventory list. 
* @prvernier will compare BC08 on server to newest BC FRI using WinMerge. 
* If no changes we will call it BC08. 
* If changes we call it BC09.

**Comment by edwardsmarc** [comment]
Note BC has released another new inventory: https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-inventory/data-management-and-access

**Comment by edwardsmarc** [comment]
We decided to stick with the same version used in CAS04 so we can compare the final tables. New FRIs will be loaded and processed at a later date.

**Comment by prvernier** [comment]
We can re-open this when we decide to work with BC09
