### ISSUE TITLE
Comparing SRC_INV_AREA to CASFRI_AREA

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#673]
The poly_area.csv table located in the summary_statistics folder provides a quick comparison of area values calculated by the source inventory and by the translation engine. The attributes are defined as follows:

  - inventory: inventory code
  - src_area: area reported by the source inventory (SRC_INV_AREA), presumably converted to hectares
  - src_area_8888: number of occurrences of error code -8888
  - src_area_8887: number of occurrences of error code -8887
  - src_area_8886: number of occurrences of error code -8886
  - src_area_9997: number of occurrences of error code -9997
  - cas_area: area in hectares calculated by the translation engine (CASFRI_AREA)
  - area_diff: percentage difference between src_area and cas_area: (src_area - cas_area) / src_area *100

Small differences (area_diff) are indicative that both area values have been calculated in a similar way. Large differences may indicate an issue e.g., SRC_INV_AREA was not properly converted to hectares.

**Comment by edwardsmarc** [comment]
All identified errors have been fixed. Leave open to check after next release.

**Comment by edwardsmarc** [comment]
Areas are correct in release 5.3.0. Closing.
