### ISSUE TITLE
Row Translation Rule - Lyr_all (PEI-01)

### ISSUE THREAD

**Issue by sgautam2076** [edwardsmarc/CASFRI#675]
Having “Row Translation Rule” is very powerful one in CASFRI translation. But the rule for PE01 seems to be revised slightly. It indicated that if there is spec1 is present and matches the list, the row is included and excluded otherwise. However, it missed number of rows that should be included in lyr_all table.
Number of rows having spec2 and height information, which seems to be forest, were excluded from lyr_all table in CASFRI translation. The reason for that is that while running the Row Translation Rule it passes the first condition (i.e., presence of spec1) but fails another condition (i.e., Matches to the provided list). 
I believe that having a complete species list or ensuring it as complete one all the time would be very difficult. In addition, there is always a chance that new species could be reported in the future. Hence, I see that having the condition (matching spec1 with the species list) could be problematic while making a decision on row translation. 
We understand that PEI includes non-species in the column species and seems problematic to decide based on the absence or presence of species only. My solution around this would be as follows (see the attached spreadsheet – TranslationRule_lyr_all sheet).
•	Excludes code that are not species code (i.e., AG, AL, BO, EP, PL, RD, RN, RR, SD, SO, WW)
•	Further assess for some codes that are not clear if they are in forest or not (i.e., BR, BU, CL, FL, PC) using information about height or spec2. If values for height or spec2 present populate that in lyr_all table.
[RowTranlationRule_PEI.xlsx](https://github.com/edwardsmarc/CASFRI/files/6156777/RowTranlationRule_PEI.xlsx)

**Comment by edwardsmarc** [comment]
Based on my queries which I'll copy below, I think we can simply use ```notEmpty(spec1)``` as the row_translation_rule. This should select the same rows as your proposed method.

Using this query you can see that spec1 is always present when other species are present. i.e. you never have spec2 without spec1.
```
select tt_notEmpty(spec1) a, tt_notEmpty(spec2) b, tt_notEmpty(spec3) c, tt_notEmpty(spec3) d, tt_notEmpty(spec3) e from rawfri.pe01 group by a, b, c, d, e
```
And you never get rows that are all unknown species
```
select spec1 IN ('BF','RM','SM','AL','YB','WB','GB','BE','WA','BN','EL','LA','MA','NS','WS','BS','RS','JP','LP','AP','RP','WP','SP','PO','PC','DF','RO','CE','LI','HE','EM') a, 
       spec2 IN ('BF','RM','SM','AL','YB','WB','GB','BE','WA','BN','EL','LA','MA','NS','WS','BS','RS','JP','LP','AP','RP','WP','SP','PO','PC','DF','RO','CE','LI','HE','EM') b, 
	   spec3 IN ('BF','RM','SM','AL','YB','WB','GB','BE','WA','BN','EL','LA','MA','NS','WS','BS','RS','JP','LP','AP','RP','WP','SP','PO','PC','DF','RO','CE','LI','HE','EM') c,
	   spec4 IN ('BF','RM','SM','AL','YB','WB','GB','BE','WA','BN','EL','LA','MA','NS','WS','BS','RS','JP','LP','AP','RP','WP','SP','PO','PC','DF','RO','CE','LI','HE','EM') d,
	   spec5 IN ('BF','RM','SM','AL','YB','WB','GB','BE','WA','BN','EL','LA','MA','NS','WS','BS','RS','JP','LP','AP','RP','WP','SP','PO','PC','DF','RO','CE','LI','HE','EM') e,
	   count(*)
	   from rawfri.pe01 group by a, b, c, d, e
```

So I propose we use notEmpty(spec1) as the row_translation_rule and we set any species that are not in lookup table to UNKNOWN_VALUE.

As a side note that last query shows some gaps in the species assignments that I have created a new issue for (#676 ).

**Comment by sgautam2076** [comment]
Yes, ideally we never have spec2 without spec1 but realized some strange cases in the data we have. In this case, the your proposed rule will definitely is good.
Does this exclude rows with codes AG, AL, BO, EP, PL, RD, RN, RR, SD, SO, WW? Because they are not the forest species and if these code present we could exclude.
However, there are still problem to deal code like "PC" which has two meanings. It could be Partial cut or Pin Cherry. But I do not think we can fix this issue at the moment. In that case, if we capture other information then user can decide about that.

**Comment by sgautam2076** [comment]
It makes sense to use notEmpty(spec1)- if every row where species 1 is not null contains some valid species information for at least one species. 
Thank you, Marc for this clarification.

**Comment by edwardsmarc** [comment]
One case I didn't account for is the case where we only have spec1 info and it is not a valid species code. Spec2, 3 etc. are null.

For example I just found a case where spec1 is CC, the associated percent is 0, and all other species are NULL. This creates a CASFRI row wher spec1 is UNKNOWN_VALUE and everything else is NULL.

Does it make sense to include these? It tells the user that there is something in that polygon that was labelled as a species in the source data. But we don't know what it is.

We can easily drop these cases by adapting the row_translation_rule.

**Comment by sgautam2076** [comment]
Good catch. Once the forest is clear-cut (i.e., CC - not a valid species code) we don't have other information for lyr_all table. Yes, we can drop that case.
