### ISSUE TITLE
QC DST extent error codes

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#693]
hasCountOfNotNull call should use -8887 to indicate not applicable. Followed by false to indicate unknown.
```
hasCountOfNotNull({mod_1, mod_1_year}, {mod_2, mod_2_year}, 2, TRUE|-8887);false(|-8886)
```
So if there are 2 disturbances, hasCountOfNotNull passes and false() returns -8886 (unknown). If there is 1 disturbance, hasCOuntOfNotNull() fails and returns -8887 (not applicable)

**Comment by MelinaHoule** [comment]
We should also update DIST_EXT_UPPER_1 and DIST_EXT_LOWER_1 descriptions with "Disturbance extent is unknown" instead of "Attributes does not occur" to clarify the use of the error code.

**Comment by MelinaHoule** [comment]
Close with commit: 9bea25e049bc614a4ba0e2d2bca583804a45256e
