### ISSUE TITLE
Translation unit test and random sample for BC

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#70]
* Make unit test for full translation process. 
* Need random table for BC that we will use for testing. 
* Named BC08_test. 
* Randomly selected rows. 
* We produce it once and reuse it for testing. 
* Build either comparison test in PostgreSQL or externally in R or WinMerge. 
* Preference is PostgreSQL if we can figure out how to compare two tables.

**Comment by edwardsmarc** [comment]
This issue replaces #38

**Comment by pedrogit** [comment]
Apperently TABLESAMPLE... ...REPEATABLE does not recreate the same sample when the source table is reloaded. Will have to generate the randomness another way.

**Comment by pedrogit** [comment]
Pushed a replacement for TABLESAMPLE... ...REPEATABLE. Still need to be tested and new random tables to be pushed.

**Comment by pedrogit** [comment]
Closing...
