### ISSUE TITLE
Add IsInt and IsNumeric validation rules when appropriate to existing translation files

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#78]
I guess we forgot to add those validation rules for the attributes we did for the beta.

**Comment by prvernier** [comment]
Does the order matter?
1. isInt(crown_closure);notNull(crown_closure|-8888);between(crown_closure,0,100|-9999)
2. notNull(crown_closure|-8888);between(crown_closure,0,100|-9999);isInt(crown_closure)

**Comment by edwardsmarc** [comment]
* I think the order matters for assigning error values correctly. 
* For example, if we ran TT_IsInt first, a null row would fail the validation and return the IsInt error code. But in this case we would want to return the NotNull error code.
* I would suggest the order should go from general to specific. i.e. is there data? Of the type we expect? In the range we expect?
  * In this case notNull, isInt, between.

**Comment by prvernier** [comment]
Thanks Marc. What about for a text field, should I validate with isString?

**Comment by edwardsmarc** [comment]
Not necessary since all validation functions will now accept only text.

**Comment by prvernier** [comment]
Thanks. This is done and working with the engine.
