### ISSUE TITLE
Fill in DATE_PUBLISHED in inventory list for initial four FRIs

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#83]
@prvernier, I'm not sure if we have this information, but if we do, please fill in the table with the production date of each FRI. This will be especially important in BC for tracking versions.

**Comment by prvernier** [comment]
Does the production date refer to the date the data was produced or published as a whole? Not, by inventory regions or some other attribute? For example, for the latest BC data this date would be June 11, 2018 (date published).

**Comment by edwardsmarc** [comment]
Yes I think this should be date published, a single date for the whole FRI.

**Comment by prvernier** [comment]
Okay, I'll those as I go along.

**Comment by prvernier** [comment]
Appart from BC08 and the new NB inventory which we're not using yet, I can't find the DATE_PUBLISHED in the old CASFRI docs. Maybe we can ask Melina for help?

**Comment by edwardsmarc** [comment]
Would this info be in the meta data for each FRI? We added this attribute in CAS05 so it won't be mentioned in the older CAS docs.

**Comment by prvernier** [comment]
We have it for BC, but the other inventories are older and can't find it in any of the documents I've looked at. The new NB inventory is listed as 2019-04-23, so that one is okay but we're not yet using it.

**Comment by edwardsmarc** [comment]
I guess we can put UNKNOWN or something similar for rows where we don't have the information. If it's not in the docs I don't think it will be recorded anywhere else.

**Comment by prvernier** [comment]
I'll put UNKNOWN until we have more information. Pierre R forwarded my query to Melina, so hopefully she will know.

**Comment by MelinaHoule** [comment]
I would say unknown. We never had that information. The standard gave us an idea of the production date.

**Comment by prvernier** [comment]
This table will be populated as we work thru inventories. I've added unknown where needed for the first few inventories.
