### ISSUE TITLE
helperFunctionCASFRITest.sql fails

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#85]
ERROR:  function tt_pad(text, integer, unknown) does not exist
LINE 1: SELECT TT_Pad(upper(inventoryId),4,'x')
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT TT_Pad(upper(inventoryId),4,'x')
CONTEXT:  PL/pgSQL function tt_casid(text,text,text,text,text) line 9 at assignment
SQL state: 42883

**Comment by edwardsmarc** [comment]
* This has been replaced with TT_PadConcat.
* I'll remove it.
