### ISSUE TITLE
Test with PostGIS 3 and PostgreSQL 12

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#87]
* We need to use latest versions to get parallel processing features.
* PostgreSQL 12 is not available yet for Windows so we will use 11 for the time being.

**Comment by pedrogit** [comment]
PostgreSQL 12 Windows installer is not yet available. Now the new server is installed with PostgreSQL 11 and PostGIS 2.5.

**Comment by edwardsmarc** [comment]
I have updated to PostgreSQL 11 and PostGIS 2.5. Also now using pgAdmin 4.

**Comment by pedrogit** [comment]
Removed all "WITH OIDS" 18111a1286b2dc3728d2f85b5a5b7f7505bc96bd

**Comment by pedrogit** [comment]
Only problam found was "WIT OIDS". Closed by  18111a1.
