### ISSUE TITLE
Write custom helper functions for BC LYR file

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#95]
ORIGIN UPPER and ORIGIN LOWER need custom validation function to check substring year is valid. Then need custom translation function.

SITE_INDEX needs a custom translation function.

**Comment by pedrogit** [comment]
To me looks like a specialisation of TT_IsInt in which only a substring of the main string is validated as an int.

**Comment by edwardsmarc** [comment]
@pedrogit 
Correct. Do you think we should make this a generic helper function? Right now it only exists as a custom CASFRI function.

**Comment by pedrogit** [comment]
That was my point. A variant of TT_IsInt() with a start and an end character position.

IsInt({ORIGIN UPPER}, 1, 4) would check if the 4 first characters represent an int.

Could also be simply StartWithInt() ensuring that first charaters are digits. Then we could just pass a required minimal number of them:

StartWithInt({ORIGIN UPPER}, 4)

but that solve less cases.
