### ISSUE TITLE
Review error code logic for custom validation functions

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#97]
* Many custom helper functions will use values from multiple columns.
* An example is returning value from colA if it's not null, otherwise returning value from colB.
* In these cases we cannot validate colA and colB as normal in the translation table using e.g.
  * notNull(colA|-9999);notNull(colB|-9999)
  * If colA fails the error code is returned.
  * This is not the desired behaviour because we could still return colB value if present.
* Current solution is to write a single custom helper function that validates both columns as needed and returns FALSE if any validations fail.
* Limitation is we will only get a single generic error code, so we don't know why the validation failed or which column caused the validation.
* Solution is to log the reason for failure, currently by using RAISE NOTICE messages, but later we will print these to the log file.

**Comment by pedrogit** [comment]
So what is the proposed function name and signature?

**Comment by edwardsmarc** [comment]
An example is TT_vri01_site_index_validation(site_index, site_index_est) in the helperFunctionsCASFRI.sql file.

It returns FALSE if both site_index and site_index_est are null.

**Comment by pedrogit** [comment]
Why not a generic engine fonction like TT_NotNullOr() returning FALSE only if all values are null (val1 is not null OR val2 is not null OR val3 is not null OR etc...).

**Comment by edwardsmarc** [comment]
I'll convert this one to the generic function you suggest. We may have more complex examples come up which we can review in the future.

**Comment by edwardsmarc** [comment]
* Actually, this function is more complex than just checking the nulls.
* Once a value is detected it also checks its numeric, and that its between 0-99.
* These checks need to be inside a custom validation function because they are applied to different columns depending on the row being processed.
