### ISSUE TITLE
Add BetweenSubstring validation to BC ORIGIN rows

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#99]
Once TT_BetweenSubstring has been written, add to translation table.
To validate year substring is between two valid years.

@prvernier please comment here with the range of years that should be used. 1800-2200 was mentioned for AB, is BC the same?

**Comment by prvernier** [comment]
This one is a bit confusing to me with all the functions. Looking at the BC08 data, the projected_year is always 2016, so maybe there is no need to extract a substring. But even if we did, the value that is extracted should be converted to an integer. Does this new function check for that? And where in the chain should it go.

The alternative is just to calculate the values as:

- origin_lower = 2016 - proj_age_1
- origin_upper = 2016 - proj_age_1

**Comment by edwardsmarc** [comment]
We should probably include the substring extraction so we can reuse the table on other VRI datasets where the projected_year might not always be 2016. 

Currently the translation rule takes 2 inputs: 
projected_date, which is a string of the date, and 
proj_age_1, which is an integer age. 

The translation rule substracts the age from the year to get the origin. But first it has to extract the year as a substring from the date string.

The validation rules currently do the following:
1. Check the proj_age_1 value is not null
2. Check the proj_age_1 value is an integer
3. Check the proj_age_1 value greater than 1
4. Check the proj_age_1 value is less than 999

5. Check the projected_date string is not null
6. Extract the year substring and check it's a valid integer

We want to add:
7. Extract the year substring and check it's between x and y. This is what the new function TT_SubstringBetween() will do.

We could probably replace 3 and 4 with TT_Between().

All that said, if we don't have any existing bounds between which the projection_date should fall, there's not much point in including this new function. We may as well leave it as it is.

**Comment by prvernier** [comment]
I suspect the projected_date will always be a constant and incremented with future versions. We could created arbitrary limits e.g., 2000-2020 or something similar. So, should we leave it alone or add the new function? Not sure...

As for the earlier (much earlier comment) on bounds. Origin_upper and origin_lower a specified to be bounded between 0-2020.

**Comment by edwardsmarc** [comment]
Yes maybe an arbitrary year range of say 1900 - 2020? Really we just want to catch any integers that clearly don't represent valid years (e.g. 9999).

@pedrogit Any thoughts on this?

**Comment by edwardsmarc** [comment]
@prvernier 

FYI we now have the TT_betweenSubstring() function
